/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module axi4_to_ahb(clk, rst_n, s_awvalid, s_awready, s_awaddr, s_awid, s_wvalid, s_wready, s_wdata, s_wstrb, s_bvalid, s_bready, s_bresp, s_bid, s_arvalid, s_arready, s_araddr, s_arid, s_rvalid, s_rready, s_rdata
, s_rresp, s_rlast, haddr, hwrite, htrans, hsize, hburst, hwdata, hrdata, hready, hresp);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire [1:0] bstate;
  input clk;
  wire clk;
  output [31:0] haddr;
  wire [31:0] haddr;
  output [2:0] hburst;
  wire [2:0] hburst;
  input [31:0] hrdata;
  wire [31:0] hrdata;
  input hready;
  wire hready;
  input hresp;
  wire hresp;
  output [2:0] hsize;
  wire [2:0] hsize;
  output [1:0] htrans;
  wire [1:0] htrans;
  output [31:0] hwdata;
  wire [31:0] hwdata;
  output hwrite;
  wire hwrite;
  wire is_wr;
  input rst_n;
  wire rst_n;
  input [39:0] s_araddr;
  wire [39:0] s_araddr;
  input [3:0] s_arid;
  wire [3:0] s_arid;
  output s_arready;
  wire s_arready;
  input s_arvalid;
  wire s_arvalid;
  input [39:0] s_awaddr;
  wire [39:0] s_awaddr;
  input [3:0] s_awid;
  wire [3:0] s_awid;
  output s_awready;
  wire s_awready;
  input s_awvalid;
  wire s_awvalid;
  output [3:0] s_bid;
  wire [3:0] s_bid;
  input s_bready;
  wire s_bready;
  output [1:0] s_bresp;
  wire [1:0] s_bresp;
  output s_bvalid;
  wire s_bvalid;
  output [31:0] s_rdata;
  wire [31:0] s_rdata;
  output s_rlast;
  wire s_rlast;
  input s_rready;
  wire s_rready;
  output [1:0] s_rresp;
  wire [1:0] s_rresp;
  output s_rvalid;
  wire s_rvalid;
  input [31:0] s_wdata;
  wire [31:0] s_wdata;
  output s_wready;
  wire s_wready;
  input [3:0] s_wstrb;
  wire [3:0] s_wstrb;
  input s_wvalid;
  wire s_wvalid;
  INVX1 _280_ (
    .A(bstate[0]),
    .Y(_106_)
  );
  INVX1 _281_ (
    .A(is_wr),
    .Y(_107_)
  );
  INVX1 _282_ (
    .A(rst_n),
    .Y(_108_)
  );
  INVX1 _283_ (
    .A(hready),
    .Y(_109_)
  );
  INVX1 _284_ (
    .A(s_bready),
    .Y(_110_)
  );
  INVX1 _285_ (
    .A(s_rready),
    .Y(_111_)
  );
  NAND2X1 _286_ (
    .A(bstate[1]),
    .B(bstate[0]),
    .Y(_112_)
  );
  NOR2X1 _287_ (
    .A(is_wr),
    .B(_112_),
    .Y(_113_)
  );
  NOR2X1 _288_ (
    .A(_105_),
    .B(bstate[0]),
    .Y(_114_)
  );
  NAND2X1 _289_ (
    .A(bstate[1]),
    .B(_106_),
    .Y(_115_)
  );
  NOR2X1 _290_ (
    .A(is_wr),
    .B(_109_),
    .Y(_116_)
  );
  NAND2X1 _291_ (
    .A(_107_),
    .B(hready),
    .Y(_117_)
  );
  OAI22X1 _292_ (
    .A(is_wr),
    .B(_112_),
    .C(_115_),
    .D(_117_),
    .Y(_279_)
  );
  NAND2X1 _293_ (
    .A(is_wr),
    .B(hready),
    .Y(_118_)
  );
  NOR2X1 _294_ (
    .A(_112_),
    .B(_118_),
    .Y(_000_)
  );
  NOR2X1 _295_ (
    .A(_105_),
    .B(_118_),
    .Y(_119_)
  );
  NOR2X1 _296_ (
    .A(_106_),
    .B(_119_),
    .Y(_120_)
  );
  AND2X1 _297_ (
    .A(s_wvalid),
    .B(is_wr),
    .Y(_121_)
  );
  NAND2X1 _298_ (
    .A(s_wvalid),
    .B(is_wr),
    .Y(_122_)
  );
  NOR3X1 _299_ (
    .A(_105_),
    .B(bstate[0]),
    .C(_121_),
    .Y(_123_)
  );
  NAND3X1 _300_ (
    .A(bstate[1]),
    .B(_106_),
    .C(_121_),
    .Y(_124_)
  );
  AOI21X1 _301_ (
    .A(_107_),
    .B(hready),
    .C(_115_),
    .Y(_125_)
  );
  OAI21X1 _302_ (
    .A(_120_),
    .B(_125_),
    .C(htrans[1]),
    .Y(_126_)
  );
  NOR2X1 _303_ (
    .A(s_awvalid),
    .B(s_arvalid),
    .Y(_127_)
  );
  NOR2X1 _304_ (
    .A(bstate[1]),
    .B(bstate[0]),
    .Y(_128_)
  );
  OR2X1 _305_ (
    .A(bstate[1]),
    .B(bstate[0]),
    .Y(_129_)
  );
  OAI21X1 _306_ (
    .A(_127_),
    .B(_129_),
    .C(_126_),
    .Y(_001_)
  );
  NOR2X1 _307_ (
    .A(_107_),
    .B(_112_),
    .Y(_130_)
  );
  OAI21X1 _308_ (
    .A(_109_),
    .B(_110_),
    .C(_130_),
    .Y(_131_)
  );
  AOI22X1 _309_ (
    .A(_111_),
    .B(_113_),
    .C(_117_),
    .D(_123_),
    .Y(_132_)
  );
  AND2X1 _310_ (
    .A(_131_),
    .B(_132_),
    .Y(_133_)
  );
  NAND2X1 _311_ (
    .A(_127_),
    .B(_128_),
    .Y(_134_)
  );
  NAND3X1 _312_ (
    .A(_131_),
    .B(_132_),
    .C(_134_),
    .Y(_135_)
  );
  AOI21X1 _313_ (
    .A(s_rready),
    .B(_122_),
    .C(_115_),
    .Y(_136_)
  );
  INVX1 _314_ (
    .A(_136_),
    .Y(_137_)
  );
  MUX2X1 _315_ (
    .A(_106_),
    .B(_137_),
    .S(_135_),
    .Y(_002_)
  );
  NOR2X1 _316_ (
    .A(_128_),
    .B(_136_),
    .Y(_138_)
  );
  OAI21X1 _317_ (
    .A(_135_),
    .B(_138_),
    .C(_133_),
    .Y(_003_)
  );
  OAI21X1 _318_ (
    .A(bstate[1]),
    .B(bstate[0]),
    .C(s_awready),
    .Y(_139_)
  );
  NOR2X1 _319_ (
    .A(s_awvalid),
    .B(_129_),
    .Y(_140_)
  );
  OAI21X1 _320_ (
    .A(s_awvalid),
    .B(_129_),
    .C(_139_),
    .Y(_004_)
  );
  OAI21X1 _321_ (
    .A(_105_),
    .B(_121_),
    .C(_106_),
    .Y(_141_)
  );
  OR2X1 _322_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  MUX2X1 _323_ (
    .A(s_wready),
    .B(_115_),
    .S(_142_),
    .Y(_143_)
  );
  INVX1 _324_ (
    .A(_143_),
    .Y(_005_)
  );
  NOR2X1 _325_ (
    .A(s_arready),
    .B(_128_),
    .Y(_144_)
  );
  AOI21X1 _326_ (
    .A(s_arvalid),
    .B(_140_),
    .C(_144_),
    .Y(_006_)
  );
  NAND3X1 _327_ (
    .A(rst_n),
    .B(_116_),
    .C(_123_),
    .Y(_145_)
  );
  MUX2X1 _328_ (
    .A(s_rdata[0]),
    .B(hrdata[0]),
    .S(_145_),
    .Y(_146_)
  );
  INVX1 _329_ (
    .A(_146_),
    .Y(_007_)
  );
  MUX2X1 _330_ (
    .A(s_rdata[1]),
    .B(hrdata[1]),
    .S(_145_),
    .Y(_147_)
  );
  INVX1 _331_ (
    .A(_147_),
    .Y(_008_)
  );
  MUX2X1 _332_ (
    .A(s_rdata[2]),
    .B(hrdata[2]),
    .S(_145_),
    .Y(_148_)
  );
  INVX1 _333_ (
    .A(_148_),
    .Y(_009_)
  );
  MUX2X1 _334_ (
    .A(s_rdata[3]),
    .B(hrdata[3]),
    .S(_145_),
    .Y(_149_)
  );
  INVX1 _335_ (
    .A(_149_),
    .Y(_010_)
  );
  MUX2X1 _336_ (
    .A(s_rdata[4]),
    .B(hrdata[4]),
    .S(_145_),
    .Y(_150_)
  );
  INVX1 _337_ (
    .A(_150_),
    .Y(_011_)
  );
  MUX2X1 _338_ (
    .A(s_rdata[5]),
    .B(hrdata[5]),
    .S(_145_),
    .Y(_151_)
  );
  INVX1 _339_ (
    .A(_151_),
    .Y(_012_)
  );
  MUX2X1 _340_ (
    .A(s_rdata[6]),
    .B(hrdata[6]),
    .S(_145_),
    .Y(_152_)
  );
  INVX1 _341_ (
    .A(_152_),
    .Y(_013_)
  );
  MUX2X1 _342_ (
    .A(s_rdata[7]),
    .B(hrdata[7]),
    .S(_145_),
    .Y(_153_)
  );
  INVX1 _343_ (
    .A(_153_),
    .Y(_014_)
  );
  MUX2X1 _344_ (
    .A(s_rdata[8]),
    .B(hrdata[8]),
    .S(_145_),
    .Y(_154_)
  );
  INVX1 _345_ (
    .A(_154_),
    .Y(_015_)
  );
  MUX2X1 _346_ (
    .A(s_rdata[9]),
    .B(hrdata[9]),
    .S(_145_),
    .Y(_155_)
  );
  INVX1 _347_ (
    .A(_155_),
    .Y(_016_)
  );
  MUX2X1 _348_ (
    .A(s_rdata[10]),
    .B(hrdata[10]),
    .S(_145_),
    .Y(_156_)
  );
  INVX1 _349_ (
    .A(_156_),
    .Y(_017_)
  );
  MUX2X1 _350_ (
    .A(s_rdata[11]),
    .B(hrdata[11]),
    .S(_145_),
    .Y(_157_)
  );
  INVX1 _351_ (
    .A(_157_),
    .Y(_018_)
  );
  MUX2X1 _352_ (
    .A(s_rdata[12]),
    .B(hrdata[12]),
    .S(_145_),
    .Y(_158_)
  );
  INVX1 _353_ (
    .A(_158_),
    .Y(_019_)
  );
  MUX2X1 _354_ (
    .A(s_rdata[13]),
    .B(hrdata[13]),
    .S(_145_),
    .Y(_159_)
  );
  INVX1 _355_ (
    .A(_159_),
    .Y(_020_)
  );
  MUX2X1 _356_ (
    .A(s_rdata[14]),
    .B(hrdata[14]),
    .S(_145_),
    .Y(_160_)
  );
  INVX1 _357_ (
    .A(_160_),
    .Y(_021_)
  );
  MUX2X1 _358_ (
    .A(s_rdata[15]),
    .B(hrdata[15]),
    .S(_145_),
    .Y(_161_)
  );
  INVX1 _359_ (
    .A(_161_),
    .Y(_022_)
  );
  MUX2X1 _360_ (
    .A(s_rdata[16]),
    .B(hrdata[16]),
    .S(_145_),
    .Y(_162_)
  );
  INVX1 _361_ (
    .A(_162_),
    .Y(_023_)
  );
  MUX2X1 _362_ (
    .A(s_rdata[17]),
    .B(hrdata[17]),
    .S(_145_),
    .Y(_163_)
  );
  INVX1 _363_ (
    .A(_163_),
    .Y(_024_)
  );
  MUX2X1 _364_ (
    .A(s_rdata[18]),
    .B(hrdata[18]),
    .S(_145_),
    .Y(_164_)
  );
  INVX1 _365_ (
    .A(_164_),
    .Y(_025_)
  );
  MUX2X1 _366_ (
    .A(s_rdata[19]),
    .B(hrdata[19]),
    .S(_145_),
    .Y(_165_)
  );
  INVX1 _367_ (
    .A(_165_),
    .Y(_026_)
  );
  MUX2X1 _368_ (
    .A(s_rdata[20]),
    .B(hrdata[20]),
    .S(_145_),
    .Y(_166_)
  );
  INVX1 _369_ (
    .A(_166_),
    .Y(_027_)
  );
  MUX2X1 _370_ (
    .A(s_rdata[21]),
    .B(hrdata[21]),
    .S(_145_),
    .Y(_167_)
  );
  INVX1 _371_ (
    .A(_167_),
    .Y(_028_)
  );
  MUX2X1 _372_ (
    .A(s_rdata[22]),
    .B(hrdata[22]),
    .S(_145_),
    .Y(_168_)
  );
  INVX1 _373_ (
    .A(_168_),
    .Y(_029_)
  );
  MUX2X1 _374_ (
    .A(s_rdata[23]),
    .B(hrdata[23]),
    .S(_145_),
    .Y(_169_)
  );
  INVX1 _375_ (
    .A(_169_),
    .Y(_030_)
  );
  MUX2X1 _376_ (
    .A(s_rdata[24]),
    .B(hrdata[24]),
    .S(_145_),
    .Y(_170_)
  );
  INVX1 _377_ (
    .A(_170_),
    .Y(_031_)
  );
  MUX2X1 _378_ (
    .A(s_rdata[25]),
    .B(hrdata[25]),
    .S(_145_),
    .Y(_171_)
  );
  INVX1 _379_ (
    .A(_171_),
    .Y(_032_)
  );
  MUX2X1 _380_ (
    .A(s_rdata[26]),
    .B(hrdata[26]),
    .S(_145_),
    .Y(_172_)
  );
  INVX1 _381_ (
    .A(_172_),
    .Y(_033_)
  );
  MUX2X1 _382_ (
    .A(s_rdata[27]),
    .B(hrdata[27]),
    .S(_145_),
    .Y(_173_)
  );
  INVX1 _383_ (
    .A(_173_),
    .Y(_034_)
  );
  MUX2X1 _384_ (
    .A(s_rdata[28]),
    .B(hrdata[28]),
    .S(_145_),
    .Y(_174_)
  );
  INVX1 _385_ (
    .A(_174_),
    .Y(_035_)
  );
  MUX2X1 _386_ (
    .A(s_rdata[29]),
    .B(hrdata[29]),
    .S(_145_),
    .Y(_175_)
  );
  INVX1 _387_ (
    .A(_175_),
    .Y(_036_)
  );
  MUX2X1 _388_ (
    .A(s_rdata[30]),
    .B(hrdata[30]),
    .S(_145_),
    .Y(_176_)
  );
  INVX1 _389_ (
    .A(_176_),
    .Y(_037_)
  );
  MUX2X1 _390_ (
    .A(s_rdata[31]),
    .B(hrdata[31]),
    .S(_145_),
    .Y(_177_)
  );
  INVX1 _391_ (
    .A(_177_),
    .Y(_038_)
  );
  NOR2X1 _392_ (
    .A(_108_),
    .B(_127_),
    .Y(_178_)
  );
  NAND2X1 _393_ (
    .A(_128_),
    .B(_178_),
    .Y(_179_)
  );
  MUX2X1 _394_ (
    .A(s_awaddr[0]),
    .B(s_araddr[0]),
    .S(s_awvalid),
    .Y(_180_)
  );
  NAND2X1 _395_ (
    .A(haddr[0]),
    .B(_179_),
    .Y(_181_)
  );
  OAI21X1 _396_ (
    .A(_179_),
    .B(_180_),
    .C(_181_),
    .Y(_039_)
  );
  MUX2X1 _397_ (
    .A(s_awaddr[1]),
    .B(s_araddr[1]),
    .S(s_awvalid),
    .Y(_182_)
  );
  NAND2X1 _398_ (
    .A(haddr[1]),
    .B(_179_),
    .Y(_183_)
  );
  OAI21X1 _399_ (
    .A(_179_),
    .B(_182_),
    .C(_183_),
    .Y(_040_)
  );
  MUX2X1 _400_ (
    .A(s_awaddr[2]),
    .B(s_araddr[2]),
    .S(s_awvalid),
    .Y(_184_)
  );
  NAND2X1 _401_ (
    .A(haddr[2]),
    .B(_179_),
    .Y(_185_)
  );
  OAI21X1 _402_ (
    .A(_179_),
    .B(_184_),
    .C(_185_),
    .Y(_041_)
  );
  MUX2X1 _403_ (
    .A(s_awaddr[3]),
    .B(s_araddr[3]),
    .S(s_awvalid),
    .Y(_186_)
  );
  NAND2X1 _404_ (
    .A(haddr[3]),
    .B(_179_),
    .Y(_187_)
  );
  OAI21X1 _405_ (
    .A(_179_),
    .B(_186_),
    .C(_187_),
    .Y(_042_)
  );
  MUX2X1 _406_ (
    .A(s_awaddr[4]),
    .B(s_araddr[4]),
    .S(s_awvalid),
    .Y(_188_)
  );
  NAND2X1 _407_ (
    .A(haddr[4]),
    .B(_179_),
    .Y(_189_)
  );
  OAI21X1 _408_ (
    .A(_179_),
    .B(_188_),
    .C(_189_),
    .Y(_043_)
  );
  MUX2X1 _409_ (
    .A(s_awaddr[5]),
    .B(s_araddr[5]),
    .S(s_awvalid),
    .Y(_190_)
  );
  NAND2X1 _410_ (
    .A(haddr[5]),
    .B(_179_),
    .Y(_191_)
  );
  OAI21X1 _411_ (
    .A(_179_),
    .B(_190_),
    .C(_191_),
    .Y(_044_)
  );
  MUX2X1 _412_ (
    .A(s_awaddr[6]),
    .B(s_araddr[6]),
    .S(s_awvalid),
    .Y(_192_)
  );
  NAND2X1 _413_ (
    .A(haddr[6]),
    .B(_179_),
    .Y(_193_)
  );
  OAI21X1 _414_ (
    .A(_179_),
    .B(_192_),
    .C(_193_),
    .Y(_045_)
  );
  MUX2X1 _415_ (
    .A(s_awaddr[7]),
    .B(s_araddr[7]),
    .S(s_awvalid),
    .Y(_194_)
  );
  NAND2X1 _416_ (
    .A(haddr[7]),
    .B(_179_),
    .Y(_195_)
  );
  OAI21X1 _417_ (
    .A(_179_),
    .B(_194_),
    .C(_195_),
    .Y(_046_)
  );
  MUX2X1 _418_ (
    .A(s_awaddr[8]),
    .B(s_araddr[8]),
    .S(s_awvalid),
    .Y(_196_)
  );
  NAND2X1 _419_ (
    .A(haddr[8]),
    .B(_179_),
    .Y(_197_)
  );
  OAI21X1 _420_ (
    .A(_179_),
    .B(_196_),
    .C(_197_),
    .Y(_047_)
  );
  MUX2X1 _421_ (
    .A(s_awaddr[9]),
    .B(s_araddr[9]),
    .S(s_awvalid),
    .Y(_198_)
  );
  NAND2X1 _422_ (
    .A(haddr[9]),
    .B(_179_),
    .Y(_199_)
  );
  OAI21X1 _423_ (
    .A(_179_),
    .B(_198_),
    .C(_199_),
    .Y(_048_)
  );
  MUX2X1 _424_ (
    .A(s_awaddr[10]),
    .B(s_araddr[10]),
    .S(s_awvalid),
    .Y(_200_)
  );
  NAND2X1 _425_ (
    .A(haddr[10]),
    .B(_179_),
    .Y(_201_)
  );
  OAI21X1 _426_ (
    .A(_179_),
    .B(_200_),
    .C(_201_),
    .Y(_049_)
  );
  MUX2X1 _427_ (
    .A(s_awaddr[11]),
    .B(s_araddr[11]),
    .S(s_awvalid),
    .Y(_202_)
  );
  NAND2X1 _428_ (
    .A(haddr[11]),
    .B(_179_),
    .Y(_203_)
  );
  OAI21X1 _429_ (
    .A(_179_),
    .B(_202_),
    .C(_203_),
    .Y(_050_)
  );
  MUX2X1 _430_ (
    .A(s_awaddr[12]),
    .B(s_araddr[12]),
    .S(s_awvalid),
    .Y(_204_)
  );
  NAND2X1 _431_ (
    .A(haddr[12]),
    .B(_179_),
    .Y(_205_)
  );
  OAI21X1 _432_ (
    .A(_179_),
    .B(_204_),
    .C(_205_),
    .Y(_051_)
  );
  MUX2X1 _433_ (
    .A(s_awaddr[13]),
    .B(s_araddr[13]),
    .S(s_awvalid),
    .Y(_206_)
  );
  NAND2X1 _434_ (
    .A(haddr[13]),
    .B(_179_),
    .Y(_207_)
  );
  OAI21X1 _435_ (
    .A(_179_),
    .B(_206_),
    .C(_207_),
    .Y(_052_)
  );
  MUX2X1 _436_ (
    .A(s_awaddr[14]),
    .B(s_araddr[14]),
    .S(s_awvalid),
    .Y(_208_)
  );
  NAND2X1 _437_ (
    .A(haddr[14]),
    .B(_179_),
    .Y(_209_)
  );
  OAI21X1 _438_ (
    .A(_179_),
    .B(_208_),
    .C(_209_),
    .Y(_053_)
  );
  MUX2X1 _439_ (
    .A(s_awaddr[15]),
    .B(s_araddr[15]),
    .S(s_awvalid),
    .Y(_210_)
  );
  NAND2X1 _440_ (
    .A(haddr[15]),
    .B(_179_),
    .Y(_211_)
  );
  OAI21X1 _441_ (
    .A(_179_),
    .B(_210_),
    .C(_211_),
    .Y(_054_)
  );
  MUX2X1 _442_ (
    .A(s_awaddr[16]),
    .B(s_araddr[16]),
    .S(s_awvalid),
    .Y(_212_)
  );
  NAND2X1 _443_ (
    .A(haddr[16]),
    .B(_179_),
    .Y(_213_)
  );
  OAI21X1 _444_ (
    .A(_179_),
    .B(_212_),
    .C(_213_),
    .Y(_055_)
  );
  MUX2X1 _445_ (
    .A(s_awaddr[17]),
    .B(s_araddr[17]),
    .S(s_awvalid),
    .Y(_214_)
  );
  NAND2X1 _446_ (
    .A(haddr[17]),
    .B(_179_),
    .Y(_215_)
  );
  OAI21X1 _447_ (
    .A(_179_),
    .B(_214_),
    .C(_215_),
    .Y(_056_)
  );
  MUX2X1 _448_ (
    .A(s_awaddr[18]),
    .B(s_araddr[18]),
    .S(s_awvalid),
    .Y(_216_)
  );
  NAND2X1 _449_ (
    .A(haddr[18]),
    .B(_179_),
    .Y(_217_)
  );
  OAI21X1 _450_ (
    .A(_179_),
    .B(_216_),
    .C(_217_),
    .Y(_057_)
  );
  MUX2X1 _451_ (
    .A(s_awaddr[19]),
    .B(s_araddr[19]),
    .S(s_awvalid),
    .Y(_218_)
  );
  NAND2X1 _452_ (
    .A(haddr[19]),
    .B(_179_),
    .Y(_219_)
  );
  OAI21X1 _453_ (
    .A(_179_),
    .B(_218_),
    .C(_219_),
    .Y(_058_)
  );
  MUX2X1 _454_ (
    .A(s_awaddr[20]),
    .B(s_araddr[20]),
    .S(s_awvalid),
    .Y(_220_)
  );
  NAND2X1 _455_ (
    .A(haddr[20]),
    .B(_179_),
    .Y(_221_)
  );
  OAI21X1 _456_ (
    .A(_179_),
    .B(_220_),
    .C(_221_),
    .Y(_059_)
  );
  MUX2X1 _457_ (
    .A(s_awaddr[21]),
    .B(s_araddr[21]),
    .S(s_awvalid),
    .Y(_222_)
  );
  NAND2X1 _458_ (
    .A(haddr[21]),
    .B(_179_),
    .Y(_223_)
  );
  OAI21X1 _459_ (
    .A(_179_),
    .B(_222_),
    .C(_223_),
    .Y(_060_)
  );
  MUX2X1 _460_ (
    .A(s_awaddr[22]),
    .B(s_araddr[22]),
    .S(s_awvalid),
    .Y(_224_)
  );
  NAND2X1 _461_ (
    .A(haddr[22]),
    .B(_179_),
    .Y(_225_)
  );
  OAI21X1 _462_ (
    .A(_179_),
    .B(_224_),
    .C(_225_),
    .Y(_061_)
  );
  MUX2X1 _463_ (
    .A(s_awaddr[23]),
    .B(s_araddr[23]),
    .S(s_awvalid),
    .Y(_226_)
  );
  NAND2X1 _464_ (
    .A(haddr[23]),
    .B(_179_),
    .Y(_227_)
  );
  OAI21X1 _465_ (
    .A(_179_),
    .B(_226_),
    .C(_227_),
    .Y(_062_)
  );
  MUX2X1 _466_ (
    .A(s_awaddr[24]),
    .B(s_araddr[24]),
    .S(s_awvalid),
    .Y(_228_)
  );
  NAND2X1 _467_ (
    .A(haddr[24]),
    .B(_179_),
    .Y(_229_)
  );
  OAI21X1 _468_ (
    .A(_179_),
    .B(_228_),
    .C(_229_),
    .Y(_063_)
  );
  MUX2X1 _469_ (
    .A(s_awaddr[25]),
    .B(s_araddr[25]),
    .S(s_awvalid),
    .Y(_230_)
  );
  NAND2X1 _470_ (
    .A(haddr[25]),
    .B(_179_),
    .Y(_231_)
  );
  OAI21X1 _471_ (
    .A(_179_),
    .B(_230_),
    .C(_231_),
    .Y(_064_)
  );
  MUX2X1 _472_ (
    .A(s_awaddr[26]),
    .B(s_araddr[26]),
    .S(s_awvalid),
    .Y(_232_)
  );
  NAND2X1 _473_ (
    .A(haddr[26]),
    .B(_179_),
    .Y(_233_)
  );
  OAI21X1 _474_ (
    .A(_179_),
    .B(_232_),
    .C(_233_),
    .Y(_065_)
  );
  MUX2X1 _475_ (
    .A(s_awaddr[27]),
    .B(s_araddr[27]),
    .S(s_awvalid),
    .Y(_234_)
  );
  NAND2X1 _476_ (
    .A(haddr[27]),
    .B(_179_),
    .Y(_235_)
  );
  OAI21X1 _477_ (
    .A(_179_),
    .B(_234_),
    .C(_235_),
    .Y(_066_)
  );
  MUX2X1 _478_ (
    .A(s_awaddr[28]),
    .B(s_araddr[28]),
    .S(s_awvalid),
    .Y(_236_)
  );
  NAND2X1 _479_ (
    .A(haddr[28]),
    .B(_179_),
    .Y(_237_)
  );
  OAI21X1 _480_ (
    .A(_179_),
    .B(_236_),
    .C(_237_),
    .Y(_067_)
  );
  MUX2X1 _481_ (
    .A(s_awaddr[29]),
    .B(s_araddr[29]),
    .S(s_awvalid),
    .Y(_238_)
  );
  NAND2X1 _482_ (
    .A(haddr[29]),
    .B(_179_),
    .Y(_239_)
  );
  OAI21X1 _483_ (
    .A(_179_),
    .B(_238_),
    .C(_239_),
    .Y(_068_)
  );
  MUX2X1 _484_ (
    .A(s_awaddr[30]),
    .B(s_araddr[30]),
    .S(s_awvalid),
    .Y(_240_)
  );
  NAND2X1 _485_ (
    .A(haddr[30]),
    .B(_179_),
    .Y(_241_)
  );
  OAI21X1 _486_ (
    .A(_179_),
    .B(_240_),
    .C(_241_),
    .Y(_069_)
  );
  MUX2X1 _487_ (
    .A(s_awaddr[31]),
    .B(s_araddr[31]),
    .S(s_awvalid),
    .Y(_242_)
  );
  NAND2X1 _488_ (
    .A(haddr[31]),
    .B(_179_),
    .Y(_243_)
  );
  OAI21X1 _489_ (
    .A(_179_),
    .B(_242_),
    .C(_243_),
    .Y(_070_)
  );
  OAI21X1 _490_ (
    .A(_127_),
    .B(_129_),
    .C(hwrite),
    .Y(_244_)
  );
  OAI21X1 _491_ (
    .A(_114_),
    .B(_142_),
    .C(_244_),
    .Y(_071_)
  );
  NOR2X1 _492_ (
    .A(_108_),
    .B(_124_),
    .Y(_245_)
  );
  MUX2X1 _493_ (
    .A(s_wdata[0]),
    .B(hwdata[0]),
    .S(_245_),
    .Y(_246_)
  );
  INVX1 _494_ (
    .A(_246_),
    .Y(_072_)
  );
  MUX2X1 _495_ (
    .A(s_wdata[1]),
    .B(hwdata[1]),
    .S(_245_),
    .Y(_247_)
  );
  INVX1 _496_ (
    .A(_247_),
    .Y(_073_)
  );
  MUX2X1 _497_ (
    .A(s_wdata[2]),
    .B(hwdata[2]),
    .S(_245_),
    .Y(_248_)
  );
  INVX1 _498_ (
    .A(_248_),
    .Y(_074_)
  );
  MUX2X1 _499_ (
    .A(s_wdata[3]),
    .B(hwdata[3]),
    .S(_245_),
    .Y(_249_)
  );
  INVX1 _500_ (
    .A(_249_),
    .Y(_075_)
  );
  MUX2X1 _501_ (
    .A(s_wdata[4]),
    .B(hwdata[4]),
    .S(_245_),
    .Y(_250_)
  );
  INVX1 _502_ (
    .A(_250_),
    .Y(_076_)
  );
  MUX2X1 _503_ (
    .A(s_wdata[5]),
    .B(hwdata[5]),
    .S(_245_),
    .Y(_251_)
  );
  INVX1 _504_ (
    .A(_251_),
    .Y(_077_)
  );
  MUX2X1 _505_ (
    .A(s_wdata[6]),
    .B(hwdata[6]),
    .S(_245_),
    .Y(_252_)
  );
  INVX1 _506_ (
    .A(_252_),
    .Y(_078_)
  );
  MUX2X1 _507_ (
    .A(s_wdata[7]),
    .B(hwdata[7]),
    .S(_245_),
    .Y(_253_)
  );
  INVX1 _508_ (
    .A(_253_),
    .Y(_079_)
  );
  MUX2X1 _509_ (
    .A(s_wdata[8]),
    .B(hwdata[8]),
    .S(_245_),
    .Y(_254_)
  );
  INVX1 _510_ (
    .A(_254_),
    .Y(_080_)
  );
  MUX2X1 _511_ (
    .A(s_wdata[9]),
    .B(hwdata[9]),
    .S(_245_),
    .Y(_255_)
  );
  INVX1 _512_ (
    .A(_255_),
    .Y(_081_)
  );
  MUX2X1 _513_ (
    .A(s_wdata[10]),
    .B(hwdata[10]),
    .S(_245_),
    .Y(_256_)
  );
  INVX1 _514_ (
    .A(_256_),
    .Y(_082_)
  );
  MUX2X1 _515_ (
    .A(s_wdata[11]),
    .B(hwdata[11]),
    .S(_245_),
    .Y(_257_)
  );
  INVX1 _516_ (
    .A(_257_),
    .Y(_083_)
  );
  MUX2X1 _517_ (
    .A(s_wdata[12]),
    .B(hwdata[12]),
    .S(_245_),
    .Y(_258_)
  );
  INVX1 _518_ (
    .A(_258_),
    .Y(_084_)
  );
  MUX2X1 _519_ (
    .A(s_wdata[13]),
    .B(hwdata[13]),
    .S(_245_),
    .Y(_259_)
  );
  INVX1 _520_ (
    .A(_259_),
    .Y(_085_)
  );
  MUX2X1 _521_ (
    .A(s_wdata[14]),
    .B(hwdata[14]),
    .S(_245_),
    .Y(_260_)
  );
  INVX1 _522_ (
    .A(_260_),
    .Y(_086_)
  );
  MUX2X1 _523_ (
    .A(s_wdata[15]),
    .B(hwdata[15]),
    .S(_245_),
    .Y(_261_)
  );
  INVX1 _524_ (
    .A(_261_),
    .Y(_087_)
  );
  MUX2X1 _525_ (
    .A(s_wdata[16]),
    .B(hwdata[16]),
    .S(_245_),
    .Y(_262_)
  );
  INVX1 _526_ (
    .A(_262_),
    .Y(_088_)
  );
  MUX2X1 _527_ (
    .A(s_wdata[17]),
    .B(hwdata[17]),
    .S(_245_),
    .Y(_263_)
  );
  INVX1 _528_ (
    .A(_263_),
    .Y(_089_)
  );
  MUX2X1 _529_ (
    .A(s_wdata[18]),
    .B(hwdata[18]),
    .S(_245_),
    .Y(_264_)
  );
  INVX1 _530_ (
    .A(_264_),
    .Y(_090_)
  );
  MUX2X1 _531_ (
    .A(s_wdata[19]),
    .B(hwdata[19]),
    .S(_245_),
    .Y(_265_)
  );
  INVX1 _532_ (
    .A(_265_),
    .Y(_091_)
  );
  MUX2X1 _533_ (
    .A(s_wdata[20]),
    .B(hwdata[20]),
    .S(_245_),
    .Y(_266_)
  );
  INVX1 _534_ (
    .A(_266_),
    .Y(_092_)
  );
  MUX2X1 _535_ (
    .A(s_wdata[21]),
    .B(hwdata[21]),
    .S(_245_),
    .Y(_267_)
  );
  INVX1 _536_ (
    .A(_267_),
    .Y(_093_)
  );
  MUX2X1 _537_ (
    .A(s_wdata[22]),
    .B(hwdata[22]),
    .S(_245_),
    .Y(_268_)
  );
  INVX1 _538_ (
    .A(_268_),
    .Y(_094_)
  );
  MUX2X1 _539_ (
    .A(s_wdata[23]),
    .B(hwdata[23]),
    .S(_245_),
    .Y(_269_)
  );
  INVX1 _540_ (
    .A(_269_),
    .Y(_095_)
  );
  MUX2X1 _541_ (
    .A(s_wdata[24]),
    .B(hwdata[24]),
    .S(_245_),
    .Y(_270_)
  );
  INVX1 _542_ (
    .A(_270_),
    .Y(_096_)
  );
  MUX2X1 _543_ (
    .A(s_wdata[25]),
    .B(hwdata[25]),
    .S(_245_),
    .Y(_271_)
  );
  INVX1 _544_ (
    .A(_271_),
    .Y(_097_)
  );
  MUX2X1 _545_ (
    .A(s_wdata[26]),
    .B(hwdata[26]),
    .S(_245_),
    .Y(_272_)
  );
  INVX1 _546_ (
    .A(_272_),
    .Y(_098_)
  );
  MUX2X1 _547_ (
    .A(s_wdata[27]),
    .B(hwdata[27]),
    .S(_245_),
    .Y(_273_)
  );
  INVX1 _548_ (
    .A(_273_),
    .Y(_099_)
  );
  MUX2X1 _549_ (
    .A(s_wdata[28]),
    .B(hwdata[28]),
    .S(_245_),
    .Y(_274_)
  );
  INVX1 _550_ (
    .A(_274_),
    .Y(_100_)
  );
  MUX2X1 _551_ (
    .A(s_wdata[29]),
    .B(hwdata[29]),
    .S(_245_),
    .Y(_275_)
  );
  INVX1 _552_ (
    .A(_275_),
    .Y(_101_)
  );
  MUX2X1 _553_ (
    .A(s_wdata[30]),
    .B(hwdata[30]),
    .S(_245_),
    .Y(_276_)
  );
  INVX1 _554_ (
    .A(_276_),
    .Y(_102_)
  );
  MUX2X1 _555_ (
    .A(s_wdata[31]),
    .B(hwdata[31]),
    .S(_245_),
    .Y(_277_)
  );
  INVX1 _556_ (
    .A(_277_),
    .Y(_103_)
  );
  NOR2X1 _557_ (
    .A(s_awvalid),
    .B(_179_),
    .Y(_278_)
  );
  AOI21X1 _558_ (
    .A(_107_),
    .B(_179_),
    .C(_278_),
    .Y(_104_)
  );
  INVX1 _559_ (
    .A(bstate[1]),
    .Y(_105_)
  );
  DFFSR _560_ (
    .CLK(clk),
    .D(_001_),
    .Q(htrans[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _561_ (
    .CLK(clk),
    .D(_002_),
    .Q(bstate[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _562_ (
    .CLK(clk),
    .D(_003_),
    .Q(bstate[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _563_ (
    .CLK(clk),
    .D(_004_),
    .Q(s_awready),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _564_ (
    .CLK(clk),
    .D(_000_),
    .Q(s_bvalid),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _565_ (
    .CLK(clk),
    .D(_005_),
    .Q(s_wready),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _566_ (
    .CLK(clk),
    .D(_279_),
    .Q(s_rvalid),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _567_ (
    .CLK(clk),
    .D(_006_),
    .Q(s_arready),
    .R(1'h1),
    .S(rst_n)
  );
  DFFPOSX1 _568_ (
    .CLK(clk),
    .D(_007_),
    .Q(s_rdata[0])
  );
  DFFPOSX1 _569_ (
    .CLK(clk),
    .D(_008_),
    .Q(s_rdata[1])
  );
  DFFPOSX1 _570_ (
    .CLK(clk),
    .D(_009_),
    .Q(s_rdata[2])
  );
  DFFPOSX1 _571_ (
    .CLK(clk),
    .D(_010_),
    .Q(s_rdata[3])
  );
  DFFPOSX1 _572_ (
    .CLK(clk),
    .D(_011_),
    .Q(s_rdata[4])
  );
  DFFPOSX1 _573_ (
    .CLK(clk),
    .D(_012_),
    .Q(s_rdata[5])
  );
  DFFPOSX1 _574_ (
    .CLK(clk),
    .D(_013_),
    .Q(s_rdata[6])
  );
  DFFPOSX1 _575_ (
    .CLK(clk),
    .D(_014_),
    .Q(s_rdata[7])
  );
  DFFPOSX1 _576_ (
    .CLK(clk),
    .D(_015_),
    .Q(s_rdata[8])
  );
  DFFPOSX1 _577_ (
    .CLK(clk),
    .D(_016_),
    .Q(s_rdata[9])
  );
  DFFPOSX1 _578_ (
    .CLK(clk),
    .D(_017_),
    .Q(s_rdata[10])
  );
  DFFPOSX1 _579_ (
    .CLK(clk),
    .D(_018_),
    .Q(s_rdata[11])
  );
  DFFPOSX1 _580_ (
    .CLK(clk),
    .D(_019_),
    .Q(s_rdata[12])
  );
  DFFPOSX1 _581_ (
    .CLK(clk),
    .D(_020_),
    .Q(s_rdata[13])
  );
  DFFPOSX1 _582_ (
    .CLK(clk),
    .D(_021_),
    .Q(s_rdata[14])
  );
  DFFPOSX1 _583_ (
    .CLK(clk),
    .D(_022_),
    .Q(s_rdata[15])
  );
  DFFPOSX1 _584_ (
    .CLK(clk),
    .D(_023_),
    .Q(s_rdata[16])
  );
  DFFPOSX1 _585_ (
    .CLK(clk),
    .D(_024_),
    .Q(s_rdata[17])
  );
  DFFPOSX1 _586_ (
    .CLK(clk),
    .D(_025_),
    .Q(s_rdata[18])
  );
  DFFPOSX1 _587_ (
    .CLK(clk),
    .D(_026_),
    .Q(s_rdata[19])
  );
  DFFPOSX1 _588_ (
    .CLK(clk),
    .D(_027_),
    .Q(s_rdata[20])
  );
  DFFPOSX1 _589_ (
    .CLK(clk),
    .D(_028_),
    .Q(s_rdata[21])
  );
  DFFPOSX1 _590_ (
    .CLK(clk),
    .D(_029_),
    .Q(s_rdata[22])
  );
  DFFPOSX1 _591_ (
    .CLK(clk),
    .D(_030_),
    .Q(s_rdata[23])
  );
  DFFPOSX1 _592_ (
    .CLK(clk),
    .D(_031_),
    .Q(s_rdata[24])
  );
  DFFPOSX1 _593_ (
    .CLK(clk),
    .D(_032_),
    .Q(s_rdata[25])
  );
  DFFPOSX1 _594_ (
    .CLK(clk),
    .D(_033_),
    .Q(s_rdata[26])
  );
  DFFPOSX1 _595_ (
    .CLK(clk),
    .D(_034_),
    .Q(s_rdata[27])
  );
  DFFPOSX1 _596_ (
    .CLK(clk),
    .D(_035_),
    .Q(s_rdata[28])
  );
  DFFPOSX1 _597_ (
    .CLK(clk),
    .D(_036_),
    .Q(s_rdata[29])
  );
  DFFPOSX1 _598_ (
    .CLK(clk),
    .D(_037_),
    .Q(s_rdata[30])
  );
  DFFPOSX1 _599_ (
    .CLK(clk),
    .D(_038_),
    .Q(s_rdata[31])
  );
  DFFPOSX1 _600_ (
    .CLK(clk),
    .D(_039_),
    .Q(haddr[0])
  );
  DFFPOSX1 _601_ (
    .CLK(clk),
    .D(_040_),
    .Q(haddr[1])
  );
  DFFPOSX1 _602_ (
    .CLK(clk),
    .D(_041_),
    .Q(haddr[2])
  );
  DFFPOSX1 _603_ (
    .CLK(clk),
    .D(_042_),
    .Q(haddr[3])
  );
  DFFPOSX1 _604_ (
    .CLK(clk),
    .D(_043_),
    .Q(haddr[4])
  );
  DFFPOSX1 _605_ (
    .CLK(clk),
    .D(_044_),
    .Q(haddr[5])
  );
  DFFPOSX1 _606_ (
    .CLK(clk),
    .D(_045_),
    .Q(haddr[6])
  );
  DFFPOSX1 _607_ (
    .CLK(clk),
    .D(_046_),
    .Q(haddr[7])
  );
  DFFPOSX1 _608_ (
    .CLK(clk),
    .D(_047_),
    .Q(haddr[8])
  );
  DFFPOSX1 _609_ (
    .CLK(clk),
    .D(_048_),
    .Q(haddr[9])
  );
  DFFPOSX1 _610_ (
    .CLK(clk),
    .D(_049_),
    .Q(haddr[10])
  );
  DFFPOSX1 _611_ (
    .CLK(clk),
    .D(_050_),
    .Q(haddr[11])
  );
  DFFPOSX1 _612_ (
    .CLK(clk),
    .D(_051_),
    .Q(haddr[12])
  );
  DFFPOSX1 _613_ (
    .CLK(clk),
    .D(_052_),
    .Q(haddr[13])
  );
  DFFPOSX1 _614_ (
    .CLK(clk),
    .D(_053_),
    .Q(haddr[14])
  );
  DFFPOSX1 _615_ (
    .CLK(clk),
    .D(_054_),
    .Q(haddr[15])
  );
  DFFPOSX1 _616_ (
    .CLK(clk),
    .D(_055_),
    .Q(haddr[16])
  );
  DFFPOSX1 _617_ (
    .CLK(clk),
    .D(_056_),
    .Q(haddr[17])
  );
  DFFPOSX1 _618_ (
    .CLK(clk),
    .D(_057_),
    .Q(haddr[18])
  );
  DFFPOSX1 _619_ (
    .CLK(clk),
    .D(_058_),
    .Q(haddr[19])
  );
  DFFPOSX1 _620_ (
    .CLK(clk),
    .D(_059_),
    .Q(haddr[20])
  );
  DFFPOSX1 _621_ (
    .CLK(clk),
    .D(_060_),
    .Q(haddr[21])
  );
  DFFPOSX1 _622_ (
    .CLK(clk),
    .D(_061_),
    .Q(haddr[22])
  );
  DFFPOSX1 _623_ (
    .CLK(clk),
    .D(_062_),
    .Q(haddr[23])
  );
  DFFPOSX1 _624_ (
    .CLK(clk),
    .D(_063_),
    .Q(haddr[24])
  );
  DFFPOSX1 _625_ (
    .CLK(clk),
    .D(_064_),
    .Q(haddr[25])
  );
  DFFPOSX1 _626_ (
    .CLK(clk),
    .D(_065_),
    .Q(haddr[26])
  );
  DFFPOSX1 _627_ (
    .CLK(clk),
    .D(_066_),
    .Q(haddr[27])
  );
  DFFPOSX1 _628_ (
    .CLK(clk),
    .D(_067_),
    .Q(haddr[28])
  );
  DFFPOSX1 _629_ (
    .CLK(clk),
    .D(_068_),
    .Q(haddr[29])
  );
  DFFPOSX1 _630_ (
    .CLK(clk),
    .D(_069_),
    .Q(haddr[30])
  );
  DFFPOSX1 _631_ (
    .CLK(clk),
    .D(_070_),
    .Q(haddr[31])
  );
  DFFSR _632_ (
    .CLK(clk),
    .D(_071_),
    .Q(hwrite),
    .R(rst_n),
    .S(1'h1)
  );
  DFFPOSX1 _633_ (
    .CLK(clk),
    .D(_072_),
    .Q(hwdata[0])
  );
  DFFPOSX1 _634_ (
    .CLK(clk),
    .D(_073_),
    .Q(hwdata[1])
  );
  DFFPOSX1 _635_ (
    .CLK(clk),
    .D(_074_),
    .Q(hwdata[2])
  );
  DFFPOSX1 _636_ (
    .CLK(clk),
    .D(_075_),
    .Q(hwdata[3])
  );
  DFFPOSX1 _637_ (
    .CLK(clk),
    .D(_076_),
    .Q(hwdata[4])
  );
  DFFPOSX1 _638_ (
    .CLK(clk),
    .D(_077_),
    .Q(hwdata[5])
  );
  DFFPOSX1 _639_ (
    .CLK(clk),
    .D(_078_),
    .Q(hwdata[6])
  );
  DFFPOSX1 _640_ (
    .CLK(clk),
    .D(_079_),
    .Q(hwdata[7])
  );
  DFFPOSX1 _641_ (
    .CLK(clk),
    .D(_080_),
    .Q(hwdata[8])
  );
  DFFPOSX1 _642_ (
    .CLK(clk),
    .D(_081_),
    .Q(hwdata[9])
  );
  DFFPOSX1 _643_ (
    .CLK(clk),
    .D(_082_),
    .Q(hwdata[10])
  );
  DFFPOSX1 _644_ (
    .CLK(clk),
    .D(_083_),
    .Q(hwdata[11])
  );
  DFFPOSX1 _645_ (
    .CLK(clk),
    .D(_084_),
    .Q(hwdata[12])
  );
  DFFPOSX1 _646_ (
    .CLK(clk),
    .D(_085_),
    .Q(hwdata[13])
  );
  DFFPOSX1 _647_ (
    .CLK(clk),
    .D(_086_),
    .Q(hwdata[14])
  );
  DFFPOSX1 _648_ (
    .CLK(clk),
    .D(_087_),
    .Q(hwdata[15])
  );
  DFFPOSX1 _649_ (
    .CLK(clk),
    .D(_088_),
    .Q(hwdata[16])
  );
  DFFPOSX1 _650_ (
    .CLK(clk),
    .D(_089_),
    .Q(hwdata[17])
  );
  DFFPOSX1 _651_ (
    .CLK(clk),
    .D(_090_),
    .Q(hwdata[18])
  );
  DFFPOSX1 _652_ (
    .CLK(clk),
    .D(_091_),
    .Q(hwdata[19])
  );
  DFFPOSX1 _653_ (
    .CLK(clk),
    .D(_092_),
    .Q(hwdata[20])
  );
  DFFPOSX1 _654_ (
    .CLK(clk),
    .D(_093_),
    .Q(hwdata[21])
  );
  DFFPOSX1 _655_ (
    .CLK(clk),
    .D(_094_),
    .Q(hwdata[22])
  );
  DFFPOSX1 _656_ (
    .CLK(clk),
    .D(_095_),
    .Q(hwdata[23])
  );
  DFFPOSX1 _657_ (
    .CLK(clk),
    .D(_096_),
    .Q(hwdata[24])
  );
  DFFPOSX1 _658_ (
    .CLK(clk),
    .D(_097_),
    .Q(hwdata[25])
  );
  DFFPOSX1 _659_ (
    .CLK(clk),
    .D(_098_),
    .Q(hwdata[26])
  );
  DFFPOSX1 _660_ (
    .CLK(clk),
    .D(_099_),
    .Q(hwdata[27])
  );
  DFFPOSX1 _661_ (
    .CLK(clk),
    .D(_100_),
    .Q(hwdata[28])
  );
  DFFPOSX1 _662_ (
    .CLK(clk),
    .D(_101_),
    .Q(hwdata[29])
  );
  DFFPOSX1 _663_ (
    .CLK(clk),
    .D(_102_),
    .Q(hwdata[30])
  );
  DFFPOSX1 _664_ (
    .CLK(clk),
    .D(_103_),
    .Q(hwdata[31])
  );
  DFFPOSX1 _665_ (
    .CLK(clk),
    .D(_104_),
    .Q(is_wr)
  );
  assign hburst = 3'h0;
  assign hsize = 3'h2;
  assign htrans[0] = 1'h0;
  assign s_bid = 4'h0;
  assign s_bresp = 2'h0;
  assign s_rlast = 1'h1;
  assign s_rresp = 2'h0;
endmodule
