/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module cdc_sync(dst_clk, rst_n, data_in, data_out);
  input data_in;
  wire data_in;
  output data_out;
  wire data_out;
  input dst_clk;
  wire dst_clk;
  input rst_n;
  wire rst_n;
  wire \sync_ff[0] ;
  wire \sync_ff[1] ;
  DFFSR _0_ (
    .CLK(dst_clk),
    .D(data_in),
    .Q(\sync_ff[0] ),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _1_ (
    .CLK(dst_clk),
    .D(\sync_ff[0] ),
    .Q(\sync_ff[1] ),
    .R(rst_n),
    .S(1'h1)
  );
  assign data_out = \sync_ff[1] ;
endmodule
