/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module ddr_phy_if(clk, rst_n, dfi_ck_en, dfi_cs_n, dfi_ras_n, dfi_cas_n, dfi_we_n, dfi_bank, dfi_addr, dfi_wrdata_valid, dfi_wrdata, dfi_wrdata_mask, dfi_rddata, dfi_rddata_valid, ddr_ck_p, ddr_ck_n, ddr_cke, ddr_cs_n, ddr_ras_n, ddr_cas_n, ddr_we_n
, ddr_ba, ddr_addr, ddr_dm, ddr_dq, ddr_dqs_p, ddr_dqs_n);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  input clk;
  wire clk;
  output [15:0] ddr_addr;
  wire [15:0] ddr_addr;
  output [2:0] ddr_ba;
  wire [2:0] ddr_ba;
  output ddr_cas_n;
  wire ddr_cas_n;
  output ddr_ck_n;
  wire ddr_ck_n;
  output ddr_ck_p;
  wire ddr_ck_p;
  output ddr_cke;
  wire ddr_cke;
  output ddr_cs_n;
  wire ddr_cs_n;
  output [7:0] ddr_dm;
  wire [7:0] ddr_dm;
  inout [63:0] ddr_dq;
  wire [63:0] ddr_dq;
  inout [7:0] ddr_dqs_n;
  wire [7:0] ddr_dqs_n;
  inout [7:0] ddr_dqs_p;
  wire [7:0] ddr_dqs_p;
  output ddr_ras_n;
  wire ddr_ras_n;
  output ddr_we_n;
  wire ddr_we_n;
  input [15:0] dfi_addr;
  wire [15:0] dfi_addr;
  input [2:0] dfi_bank;
  wire [2:0] dfi_bank;
  input dfi_cas_n;
  wire dfi_cas_n;
  input dfi_ck_en;
  wire dfi_ck_en;
  input dfi_cs_n;
  wire dfi_cs_n;
  input dfi_ras_n;
  wire dfi_ras_n;
  output [63:0] dfi_rddata;
  wire [63:0] dfi_rddata;
  output dfi_rddata_valid;
  wire dfi_rddata_valid;
  wire dfi_rddata_valid_d;
  input dfi_we_n;
  wire dfi_we_n;
  input [63:0] dfi_wrdata;
  wire [63:0] dfi_wrdata;
  input [7:0] dfi_wrdata_mask;
  wire [7:0] dfi_wrdata_mask;
  input dfi_wrdata_valid;
  wire dfi_wrdata_valid;
  wire dqs_drive;
  input rst_n;
  wire rst_n;
  INVX1 _197_ (
    .A(dfi_ck_en),
    .Y(_067_)
  );
  INVX1 _198_ (
    .A(dfi_wrdata[0]),
    .Y(_068_)
  );
  INVX1 _199_ (
    .A(dfi_wrdata[1]),
    .Y(_069_)
  );
  INVX1 _200_ (
    .A(dfi_wrdata[2]),
    .Y(_070_)
  );
  INVX1 _201_ (
    .A(dfi_wrdata[3]),
    .Y(_071_)
  );
  INVX1 _202_ (
    .A(dfi_wrdata[4]),
    .Y(_072_)
  );
  INVX1 _203_ (
    .A(dfi_wrdata[5]),
    .Y(_073_)
  );
  INVX1 _204_ (
    .A(dfi_wrdata[6]),
    .Y(_074_)
  );
  INVX1 _205_ (
    .A(dfi_wrdata[7]),
    .Y(_075_)
  );
  INVX1 _206_ (
    .A(dfi_wrdata[8]),
    .Y(_076_)
  );
  INVX1 _207_ (
    .A(dfi_wrdata[9]),
    .Y(_077_)
  );
  INVX1 _208_ (
    .A(dfi_wrdata[10]),
    .Y(_078_)
  );
  INVX1 _209_ (
    .A(dfi_wrdata[11]),
    .Y(_079_)
  );
  INVX1 _210_ (
    .A(dfi_wrdata[12]),
    .Y(_080_)
  );
  INVX1 _211_ (
    .A(dfi_wrdata[13]),
    .Y(_081_)
  );
  INVX1 _212_ (
    .A(dfi_wrdata[14]),
    .Y(_082_)
  );
  INVX1 _213_ (
    .A(dfi_wrdata[15]),
    .Y(_083_)
  );
  INVX1 _214_ (
    .A(dfi_wrdata[16]),
    .Y(_084_)
  );
  INVX1 _215_ (
    .A(dfi_wrdata[17]),
    .Y(_085_)
  );
  INVX1 _216_ (
    .A(dfi_wrdata[18]),
    .Y(_086_)
  );
  INVX1 _217_ (
    .A(dfi_wrdata[19]),
    .Y(_087_)
  );
  INVX1 _218_ (
    .A(dfi_wrdata[20]),
    .Y(_088_)
  );
  INVX1 _219_ (
    .A(dfi_wrdata[21]),
    .Y(_089_)
  );
  INVX1 _220_ (
    .A(dfi_wrdata[22]),
    .Y(_090_)
  );
  INVX1 _221_ (
    .A(dfi_wrdata[23]),
    .Y(_091_)
  );
  INVX1 _222_ (
    .A(dfi_wrdata[24]),
    .Y(_092_)
  );
  INVX1 _223_ (
    .A(dfi_wrdata[25]),
    .Y(_093_)
  );
  INVX1 _224_ (
    .A(dfi_wrdata[26]),
    .Y(_094_)
  );
  INVX1 _225_ (
    .A(dfi_wrdata[27]),
    .Y(_095_)
  );
  INVX1 _226_ (
    .A(dfi_wrdata[28]),
    .Y(_096_)
  );
  INVX1 _227_ (
    .A(dfi_wrdata[29]),
    .Y(_097_)
  );
  INVX1 _228_ (
    .A(dfi_wrdata[30]),
    .Y(_098_)
  );
  INVX1 _229_ (
    .A(dfi_wrdata[31]),
    .Y(_099_)
  );
  INVX1 _230_ (
    .A(dfi_wrdata[32]),
    .Y(_100_)
  );
  INVX1 _231_ (
    .A(dfi_wrdata[33]),
    .Y(_101_)
  );
  INVX1 _232_ (
    .A(dfi_wrdata[34]),
    .Y(_102_)
  );
  INVX1 _233_ (
    .A(dfi_wrdata[35]),
    .Y(_103_)
  );
  INVX1 _234_ (
    .A(dfi_wrdata[36]),
    .Y(_104_)
  );
  INVX1 _235_ (
    .A(dfi_wrdata[37]),
    .Y(_105_)
  );
  INVX1 _236_ (
    .A(dfi_wrdata[38]),
    .Y(_106_)
  );
  INVX1 _237_ (
    .A(dfi_wrdata[39]),
    .Y(_107_)
  );
  INVX1 _238_ (
    .A(dfi_wrdata[40]),
    .Y(_108_)
  );
  INVX1 _239_ (
    .A(dfi_wrdata[41]),
    .Y(_109_)
  );
  INVX1 _240_ (
    .A(dfi_wrdata[42]),
    .Y(_110_)
  );
  INVX1 _241_ (
    .A(dfi_wrdata[43]),
    .Y(_111_)
  );
  INVX1 _242_ (
    .A(dfi_wrdata[44]),
    .Y(_112_)
  );
  INVX1 _243_ (
    .A(dfi_wrdata[45]),
    .Y(_113_)
  );
  INVX1 _244_ (
    .A(dfi_wrdata[46]),
    .Y(_114_)
  );
  INVX1 _245_ (
    .A(dfi_wrdata[47]),
    .Y(_115_)
  );
  INVX1 _246_ (
    .A(dfi_wrdata[48]),
    .Y(_116_)
  );
  INVX1 _247_ (
    .A(dfi_wrdata[49]),
    .Y(_117_)
  );
  INVX1 _248_ (
    .A(dfi_wrdata[50]),
    .Y(_118_)
  );
  INVX1 _249_ (
    .A(dfi_wrdata[51]),
    .Y(_119_)
  );
  INVX1 _250_ (
    .A(dfi_wrdata[52]),
    .Y(_120_)
  );
  INVX1 _251_ (
    .A(dfi_wrdata[53]),
    .Y(_121_)
  );
  INVX1 _252_ (
    .A(dfi_wrdata[54]),
    .Y(_122_)
  );
  INVX1 _253_ (
    .A(dfi_wrdata[55]),
    .Y(_123_)
  );
  INVX1 _254_ (
    .A(dfi_wrdata[56]),
    .Y(_124_)
  );
  INVX1 _255_ (
    .A(dfi_wrdata[57]),
    .Y(_125_)
  );
  INVX1 _256_ (
    .A(dfi_wrdata[58]),
    .Y(_126_)
  );
  INVX1 _257_ (
    .A(dfi_wrdata[59]),
    .Y(_127_)
  );
  INVX1 _258_ (
    .A(dfi_wrdata[60]),
    .Y(_128_)
  );
  INVX1 _259_ (
    .A(dfi_wrdata[61]),
    .Y(_129_)
  );
  INVX1 _260_ (
    .A(dfi_wrdata[62]),
    .Y(_130_)
  );
  INVX1 _261_ (
    .A(dfi_wrdata[63]),
    .Y(_131_)
  );
  OR2X1 _262_ (
    .A(dfi_cs_n),
    .B(dfi_wrdata_valid),
    .Y(_132_)
  );
  NOR2X1 _263_ (
    .A(dfi_cas_n),
    .B(_132_),
    .Y(_002_)
  );
  AND2X1 _264_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[0]),
    .Y(ddr_dm[0])
  );
  AND2X1 _265_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[1]),
    .Y(ddr_dm[1])
  );
  AND2X1 _266_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[2]),
    .Y(ddr_dm[2])
  );
  AND2X1 _267_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[3]),
    .Y(ddr_dm[3])
  );
  AND2X1 _268_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[4]),
    .Y(ddr_dm[4])
  );
  AND2X1 _269_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[5]),
    .Y(ddr_dm[5])
  );
  AND2X1 _270_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[6]),
    .Y(ddr_dm[6])
  );
  AND2X1 _271_ (
    .A(dfi_wrdata_valid),
    .B(dfi_wrdata_mask[7]),
    .Y(ddr_dm[7])
  );
  NOR2X1 _272_ (
    .A(_067_),
    .B(ddr_dqs_n[7]),
    .Y(_000_)
  );
  NOR2X1 _273_ (
    .A(_067_),
    .B(ddr_dqs_p[7]),
    .Y(_001_)
  );
  NAND2X1 _274_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[0]),
    .Y(_133_)
  );
  OAI21X1 _275_ (
    .A(dfi_wrdata_valid),
    .B(_068_),
    .C(_133_),
    .Y(_003_)
  );
  NAND2X1 _276_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[1]),
    .Y(_134_)
  );
  OAI21X1 _277_ (
    .A(dfi_wrdata_valid),
    .B(_069_),
    .C(_134_),
    .Y(_004_)
  );
  NAND2X1 _278_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[2]),
    .Y(_135_)
  );
  OAI21X1 _279_ (
    .A(dfi_wrdata_valid),
    .B(_070_),
    .C(_135_),
    .Y(_005_)
  );
  NAND2X1 _280_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[3]),
    .Y(_136_)
  );
  OAI21X1 _281_ (
    .A(dfi_wrdata_valid),
    .B(_071_),
    .C(_136_),
    .Y(_006_)
  );
  NAND2X1 _282_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[4]),
    .Y(_137_)
  );
  OAI21X1 _283_ (
    .A(dfi_wrdata_valid),
    .B(_072_),
    .C(_137_),
    .Y(_007_)
  );
  NAND2X1 _284_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[5]),
    .Y(_138_)
  );
  OAI21X1 _285_ (
    .A(dfi_wrdata_valid),
    .B(_073_),
    .C(_138_),
    .Y(_008_)
  );
  NAND2X1 _286_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[6]),
    .Y(_139_)
  );
  OAI21X1 _287_ (
    .A(dfi_wrdata_valid),
    .B(_074_),
    .C(_139_),
    .Y(_009_)
  );
  NAND2X1 _288_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[7]),
    .Y(_140_)
  );
  OAI21X1 _289_ (
    .A(dfi_wrdata_valid),
    .B(_075_),
    .C(_140_),
    .Y(_010_)
  );
  NAND2X1 _290_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[8]),
    .Y(_141_)
  );
  OAI21X1 _291_ (
    .A(dfi_wrdata_valid),
    .B(_076_),
    .C(_141_),
    .Y(_011_)
  );
  NAND2X1 _292_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[9]),
    .Y(_142_)
  );
  OAI21X1 _293_ (
    .A(dfi_wrdata_valid),
    .B(_077_),
    .C(_142_),
    .Y(_012_)
  );
  NAND2X1 _294_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[10]),
    .Y(_143_)
  );
  OAI21X1 _295_ (
    .A(dfi_wrdata_valid),
    .B(_078_),
    .C(_143_),
    .Y(_013_)
  );
  NAND2X1 _296_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[11]),
    .Y(_144_)
  );
  OAI21X1 _297_ (
    .A(dfi_wrdata_valid),
    .B(_079_),
    .C(_144_),
    .Y(_014_)
  );
  NAND2X1 _298_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[12]),
    .Y(_145_)
  );
  OAI21X1 _299_ (
    .A(dfi_wrdata_valid),
    .B(_080_),
    .C(_145_),
    .Y(_015_)
  );
  NAND2X1 _300_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[13]),
    .Y(_146_)
  );
  OAI21X1 _301_ (
    .A(dfi_wrdata_valid),
    .B(_081_),
    .C(_146_),
    .Y(_016_)
  );
  NAND2X1 _302_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[14]),
    .Y(_147_)
  );
  OAI21X1 _303_ (
    .A(dfi_wrdata_valid),
    .B(_082_),
    .C(_147_),
    .Y(_017_)
  );
  NAND2X1 _304_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[15]),
    .Y(_148_)
  );
  OAI21X1 _305_ (
    .A(dfi_wrdata_valid),
    .B(_083_),
    .C(_148_),
    .Y(_018_)
  );
  NAND2X1 _306_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[16]),
    .Y(_149_)
  );
  OAI21X1 _307_ (
    .A(dfi_wrdata_valid),
    .B(_084_),
    .C(_149_),
    .Y(_019_)
  );
  NAND2X1 _308_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[17]),
    .Y(_150_)
  );
  OAI21X1 _309_ (
    .A(dfi_wrdata_valid),
    .B(_085_),
    .C(_150_),
    .Y(_020_)
  );
  NAND2X1 _310_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[18]),
    .Y(_151_)
  );
  OAI21X1 _311_ (
    .A(dfi_wrdata_valid),
    .B(_086_),
    .C(_151_),
    .Y(_021_)
  );
  NAND2X1 _312_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[19]),
    .Y(_152_)
  );
  OAI21X1 _313_ (
    .A(dfi_wrdata_valid),
    .B(_087_),
    .C(_152_),
    .Y(_022_)
  );
  NAND2X1 _314_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[20]),
    .Y(_153_)
  );
  OAI21X1 _315_ (
    .A(dfi_wrdata_valid),
    .B(_088_),
    .C(_153_),
    .Y(_023_)
  );
  NAND2X1 _316_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[21]),
    .Y(_154_)
  );
  OAI21X1 _317_ (
    .A(dfi_wrdata_valid),
    .B(_089_),
    .C(_154_),
    .Y(_024_)
  );
  NAND2X1 _318_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[22]),
    .Y(_155_)
  );
  OAI21X1 _319_ (
    .A(dfi_wrdata_valid),
    .B(_090_),
    .C(_155_),
    .Y(_025_)
  );
  NAND2X1 _320_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[23]),
    .Y(_156_)
  );
  OAI21X1 _321_ (
    .A(dfi_wrdata_valid),
    .B(_091_),
    .C(_156_),
    .Y(_026_)
  );
  NAND2X1 _322_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[24]),
    .Y(_157_)
  );
  OAI21X1 _323_ (
    .A(dfi_wrdata_valid),
    .B(_092_),
    .C(_157_),
    .Y(_027_)
  );
  NAND2X1 _324_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[25]),
    .Y(_158_)
  );
  OAI21X1 _325_ (
    .A(dfi_wrdata_valid),
    .B(_093_),
    .C(_158_),
    .Y(_028_)
  );
  NAND2X1 _326_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[26]),
    .Y(_159_)
  );
  OAI21X1 _327_ (
    .A(dfi_wrdata_valid),
    .B(_094_),
    .C(_159_),
    .Y(_029_)
  );
  NAND2X1 _328_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[27]),
    .Y(_160_)
  );
  OAI21X1 _329_ (
    .A(dfi_wrdata_valid),
    .B(_095_),
    .C(_160_),
    .Y(_030_)
  );
  NAND2X1 _330_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[28]),
    .Y(_161_)
  );
  OAI21X1 _331_ (
    .A(dfi_wrdata_valid),
    .B(_096_),
    .C(_161_),
    .Y(_031_)
  );
  NAND2X1 _332_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[29]),
    .Y(_162_)
  );
  OAI21X1 _333_ (
    .A(dfi_wrdata_valid),
    .B(_097_),
    .C(_162_),
    .Y(_032_)
  );
  NAND2X1 _334_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[30]),
    .Y(_163_)
  );
  OAI21X1 _335_ (
    .A(dfi_wrdata_valid),
    .B(_098_),
    .C(_163_),
    .Y(_033_)
  );
  NAND2X1 _336_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[31]),
    .Y(_164_)
  );
  OAI21X1 _337_ (
    .A(dfi_wrdata_valid),
    .B(_099_),
    .C(_164_),
    .Y(_034_)
  );
  NAND2X1 _338_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[32]),
    .Y(_165_)
  );
  OAI21X1 _339_ (
    .A(dfi_wrdata_valid),
    .B(_100_),
    .C(_165_),
    .Y(_035_)
  );
  NAND2X1 _340_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[33]),
    .Y(_166_)
  );
  OAI21X1 _341_ (
    .A(dfi_wrdata_valid),
    .B(_101_),
    .C(_166_),
    .Y(_036_)
  );
  NAND2X1 _342_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[34]),
    .Y(_167_)
  );
  OAI21X1 _343_ (
    .A(dfi_wrdata_valid),
    .B(_102_),
    .C(_167_),
    .Y(_037_)
  );
  NAND2X1 _344_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[35]),
    .Y(_168_)
  );
  OAI21X1 _345_ (
    .A(dfi_wrdata_valid),
    .B(_103_),
    .C(_168_),
    .Y(_038_)
  );
  NAND2X1 _346_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[36]),
    .Y(_169_)
  );
  OAI21X1 _347_ (
    .A(dfi_wrdata_valid),
    .B(_104_),
    .C(_169_),
    .Y(_039_)
  );
  NAND2X1 _348_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[37]),
    .Y(_170_)
  );
  OAI21X1 _349_ (
    .A(dfi_wrdata_valid),
    .B(_105_),
    .C(_170_),
    .Y(_040_)
  );
  NAND2X1 _350_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[38]),
    .Y(_171_)
  );
  OAI21X1 _351_ (
    .A(dfi_wrdata_valid),
    .B(_106_),
    .C(_171_),
    .Y(_041_)
  );
  NAND2X1 _352_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[39]),
    .Y(_172_)
  );
  OAI21X1 _353_ (
    .A(dfi_wrdata_valid),
    .B(_107_),
    .C(_172_),
    .Y(_042_)
  );
  NAND2X1 _354_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[40]),
    .Y(_173_)
  );
  OAI21X1 _355_ (
    .A(dfi_wrdata_valid),
    .B(_108_),
    .C(_173_),
    .Y(_043_)
  );
  NAND2X1 _356_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[41]),
    .Y(_174_)
  );
  OAI21X1 _357_ (
    .A(dfi_wrdata_valid),
    .B(_109_),
    .C(_174_),
    .Y(_044_)
  );
  NAND2X1 _358_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[42]),
    .Y(_175_)
  );
  OAI21X1 _359_ (
    .A(dfi_wrdata_valid),
    .B(_110_),
    .C(_175_),
    .Y(_045_)
  );
  NAND2X1 _360_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[43]),
    .Y(_176_)
  );
  OAI21X1 _361_ (
    .A(dfi_wrdata_valid),
    .B(_111_),
    .C(_176_),
    .Y(_046_)
  );
  NAND2X1 _362_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[44]),
    .Y(_177_)
  );
  OAI21X1 _363_ (
    .A(dfi_wrdata_valid),
    .B(_112_),
    .C(_177_),
    .Y(_047_)
  );
  NAND2X1 _364_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[45]),
    .Y(_178_)
  );
  OAI21X1 _365_ (
    .A(dfi_wrdata_valid),
    .B(_113_),
    .C(_178_),
    .Y(_048_)
  );
  NAND2X1 _366_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[46]),
    .Y(_179_)
  );
  OAI21X1 _367_ (
    .A(dfi_wrdata_valid),
    .B(_114_),
    .C(_179_),
    .Y(_049_)
  );
  NAND2X1 _368_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[47]),
    .Y(_180_)
  );
  OAI21X1 _369_ (
    .A(dfi_wrdata_valid),
    .B(_115_),
    .C(_180_),
    .Y(_050_)
  );
  NAND2X1 _370_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[48]),
    .Y(_181_)
  );
  OAI21X1 _371_ (
    .A(dfi_wrdata_valid),
    .B(_116_),
    .C(_181_),
    .Y(_051_)
  );
  NAND2X1 _372_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[49]),
    .Y(_182_)
  );
  OAI21X1 _373_ (
    .A(dfi_wrdata_valid),
    .B(_117_),
    .C(_182_),
    .Y(_052_)
  );
  NAND2X1 _374_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[50]),
    .Y(_183_)
  );
  OAI21X1 _375_ (
    .A(dfi_wrdata_valid),
    .B(_118_),
    .C(_183_),
    .Y(_053_)
  );
  NAND2X1 _376_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[51]),
    .Y(_184_)
  );
  OAI21X1 _377_ (
    .A(dfi_wrdata_valid),
    .B(_119_),
    .C(_184_),
    .Y(_054_)
  );
  NAND2X1 _378_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[52]),
    .Y(_185_)
  );
  OAI21X1 _379_ (
    .A(dfi_wrdata_valid),
    .B(_120_),
    .C(_185_),
    .Y(_055_)
  );
  NAND2X1 _380_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[53]),
    .Y(_186_)
  );
  OAI21X1 _381_ (
    .A(dfi_wrdata_valid),
    .B(_121_),
    .C(_186_),
    .Y(_056_)
  );
  NAND2X1 _382_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[54]),
    .Y(_187_)
  );
  OAI21X1 _383_ (
    .A(dfi_wrdata_valid),
    .B(_122_),
    .C(_187_),
    .Y(_057_)
  );
  NAND2X1 _384_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[55]),
    .Y(_188_)
  );
  OAI21X1 _385_ (
    .A(dfi_wrdata_valid),
    .B(_123_),
    .C(_188_),
    .Y(_058_)
  );
  NAND2X1 _386_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[56]),
    .Y(_189_)
  );
  OAI21X1 _387_ (
    .A(dfi_wrdata_valid),
    .B(_124_),
    .C(_189_),
    .Y(_059_)
  );
  NAND2X1 _388_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[57]),
    .Y(_190_)
  );
  OAI21X1 _389_ (
    .A(dfi_wrdata_valid),
    .B(_125_),
    .C(_190_),
    .Y(_060_)
  );
  NAND2X1 _390_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[58]),
    .Y(_191_)
  );
  OAI21X1 _391_ (
    .A(dfi_wrdata_valid),
    .B(_126_),
    .C(_191_),
    .Y(_061_)
  );
  NAND2X1 _392_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[59]),
    .Y(_192_)
  );
  OAI21X1 _393_ (
    .A(dfi_wrdata_valid),
    .B(_127_),
    .C(_192_),
    .Y(_062_)
  );
  NAND2X1 _394_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[60]),
    .Y(_193_)
  );
  OAI21X1 _395_ (
    .A(dfi_wrdata_valid),
    .B(_128_),
    .C(_193_),
    .Y(_063_)
  );
  NAND2X1 _396_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[61]),
    .Y(_194_)
  );
  OAI21X1 _397_ (
    .A(dfi_wrdata_valid),
    .B(_129_),
    .C(_194_),
    .Y(_064_)
  );
  NAND2X1 _398_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[62]),
    .Y(_195_)
  );
  OAI21X1 _399_ (
    .A(dfi_wrdata_valid),
    .B(_130_),
    .C(_195_),
    .Y(_065_)
  );
  NAND2X1 _400_ (
    .A(dfi_wrdata_valid),
    .B(dfi_rddata[63]),
    .Y(_196_)
  );
  OAI21X1 _401_ (
    .A(dfi_wrdata_valid),
    .B(_131_),
    .C(_196_),
    .Y(_066_)
  );
  DFFSR _402_ (
    .CLK(clk),
    .D(_003_),
    .Q(dfi_rddata[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _403_ (
    .CLK(clk),
    .D(_004_),
    .Q(dfi_rddata[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _404_ (
    .CLK(clk),
    .D(_005_),
    .Q(dfi_rddata[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _405_ (
    .CLK(clk),
    .D(_006_),
    .Q(dfi_rddata[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _406_ (
    .CLK(clk),
    .D(_007_),
    .Q(dfi_rddata[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _407_ (
    .CLK(clk),
    .D(_008_),
    .Q(dfi_rddata[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _408_ (
    .CLK(clk),
    .D(_009_),
    .Q(dfi_rddata[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _409_ (
    .CLK(clk),
    .D(_010_),
    .Q(dfi_rddata[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _410_ (
    .CLK(clk),
    .D(_011_),
    .Q(dfi_rddata[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _411_ (
    .CLK(clk),
    .D(_012_),
    .Q(dfi_rddata[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _412_ (
    .CLK(clk),
    .D(_013_),
    .Q(dfi_rddata[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _413_ (
    .CLK(clk),
    .D(_014_),
    .Q(dfi_rddata[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _414_ (
    .CLK(clk),
    .D(_015_),
    .Q(dfi_rddata[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _415_ (
    .CLK(clk),
    .D(_016_),
    .Q(dfi_rddata[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _416_ (
    .CLK(clk),
    .D(_017_),
    .Q(dfi_rddata[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _417_ (
    .CLK(clk),
    .D(_018_),
    .Q(dfi_rddata[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _418_ (
    .CLK(clk),
    .D(_019_),
    .Q(dfi_rddata[16]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _419_ (
    .CLK(clk),
    .D(_020_),
    .Q(dfi_rddata[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _420_ (
    .CLK(clk),
    .D(_021_),
    .Q(dfi_rddata[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _421_ (
    .CLK(clk),
    .D(_022_),
    .Q(dfi_rddata[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _422_ (
    .CLK(clk),
    .D(_023_),
    .Q(dfi_rddata[20]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _423_ (
    .CLK(clk),
    .D(_024_),
    .Q(dfi_rddata[21]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _424_ (
    .CLK(clk),
    .D(_025_),
    .Q(dfi_rddata[22]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _425_ (
    .CLK(clk),
    .D(_026_),
    .Q(dfi_rddata[23]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _426_ (
    .CLK(clk),
    .D(_027_),
    .Q(dfi_rddata[24]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _427_ (
    .CLK(clk),
    .D(_028_),
    .Q(dfi_rddata[25]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _428_ (
    .CLK(clk),
    .D(_029_),
    .Q(dfi_rddata[26]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _429_ (
    .CLK(clk),
    .D(_030_),
    .Q(dfi_rddata[27]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _430_ (
    .CLK(clk),
    .D(_031_),
    .Q(dfi_rddata[28]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _431_ (
    .CLK(clk),
    .D(_032_),
    .Q(dfi_rddata[29]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _432_ (
    .CLK(clk),
    .D(_033_),
    .Q(dfi_rddata[30]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _433_ (
    .CLK(clk),
    .D(_034_),
    .Q(dfi_rddata[31]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _434_ (
    .CLK(clk),
    .D(_035_),
    .Q(dfi_rddata[32]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _435_ (
    .CLK(clk),
    .D(_036_),
    .Q(dfi_rddata[33]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _436_ (
    .CLK(clk),
    .D(_037_),
    .Q(dfi_rddata[34]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _437_ (
    .CLK(clk),
    .D(_038_),
    .Q(dfi_rddata[35]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _438_ (
    .CLK(clk),
    .D(_039_),
    .Q(dfi_rddata[36]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _439_ (
    .CLK(clk),
    .D(_040_),
    .Q(dfi_rddata[37]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _440_ (
    .CLK(clk),
    .D(_041_),
    .Q(dfi_rddata[38]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _441_ (
    .CLK(clk),
    .D(_042_),
    .Q(dfi_rddata[39]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _442_ (
    .CLK(clk),
    .D(_043_),
    .Q(dfi_rddata[40]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _443_ (
    .CLK(clk),
    .D(_044_),
    .Q(dfi_rddata[41]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _444_ (
    .CLK(clk),
    .D(_045_),
    .Q(dfi_rddata[42]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _445_ (
    .CLK(clk),
    .D(_046_),
    .Q(dfi_rddata[43]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _446_ (
    .CLK(clk),
    .D(_047_),
    .Q(dfi_rddata[44]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _447_ (
    .CLK(clk),
    .D(_048_),
    .Q(dfi_rddata[45]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _448_ (
    .CLK(clk),
    .D(_049_),
    .Q(dfi_rddata[46]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _449_ (
    .CLK(clk),
    .D(_050_),
    .Q(dfi_rddata[47]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _450_ (
    .CLK(clk),
    .D(_051_),
    .Q(dfi_rddata[48]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _451_ (
    .CLK(clk),
    .D(_052_),
    .Q(dfi_rddata[49]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _452_ (
    .CLK(clk),
    .D(_053_),
    .Q(dfi_rddata[50]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _453_ (
    .CLK(clk),
    .D(_054_),
    .Q(dfi_rddata[51]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _454_ (
    .CLK(clk),
    .D(_055_),
    .Q(dfi_rddata[52]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _455_ (
    .CLK(clk),
    .D(_056_),
    .Q(dfi_rddata[53]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _456_ (
    .CLK(clk),
    .D(_057_),
    .Q(dfi_rddata[54]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _457_ (
    .CLK(clk),
    .D(_058_),
    .Q(dfi_rddata[55]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _458_ (
    .CLK(clk),
    .D(_059_),
    .Q(dfi_rddata[56]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _459_ (
    .CLK(clk),
    .D(_060_),
    .Q(dfi_rddata[57]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _460_ (
    .CLK(clk),
    .D(_061_),
    .Q(dfi_rddata[58]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _461_ (
    .CLK(clk),
    .D(_062_),
    .Q(dfi_rddata[59]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _462_ (
    .CLK(clk),
    .D(_063_),
    .Q(dfi_rddata[60]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _463_ (
    .CLK(clk),
    .D(_064_),
    .Q(dfi_rddata[61]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _464_ (
    .CLK(clk),
    .D(_065_),
    .Q(dfi_rddata[62]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _465_ (
    .CLK(clk),
    .D(_066_),
    .Q(dfi_rddata[63]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _466_ (
    .CLK(clk),
    .D(dfi_rddata_valid_d),
    .Q(dfi_rddata_valid),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _467_ (
    .CLK(clk),
    .D(_002_),
    .Q(dfi_rddata_valid_d),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _468_ (
    .CLK(clk),
    .D(_001_),
    .Q(ddr_dqs_p[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _469_ (
    .CLK(clk),
    .D(_000_),
    .Q(ddr_dqs_n[7]),
    .R(1'h1),
    .S(rst_n)
  );
  assign ddr_addr = dfi_addr;
  assign ddr_ba = dfi_bank;
  assign ddr_cas_n = dfi_cas_n;
  assign ddr_ck_n = ddr_dqs_n[7];
  assign ddr_ck_p = ddr_dqs_p[7];
  assign ddr_cke = dfi_ck_en;
  assign ddr_cs_n = dfi_cs_n;
  assign ddr_dq = dfi_wrdata;
  assign ddr_dqs_n[6:0] = { ddr_dqs_n[7], ddr_dqs_n[7], ddr_dqs_n[7], ddr_dqs_n[7], ddr_dqs_n[7], ddr_dqs_n[7], ddr_dqs_n[7] };
  assign ddr_dqs_p[6:0] = { ddr_dqs_p[7], ddr_dqs_p[7], ddr_dqs_p[7], ddr_dqs_p[7], ddr_dqs_p[7], ddr_dqs_p[7], ddr_dqs_p[7] };
  assign ddr_ras_n = dfi_ras_n;
  assign ddr_we_n = dfi_we_n;
  assign dqs_drive = dfi_wrdata_valid;
endmodule
