/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module i2c_master(clk, rst_n, psel, penable, pwrite, paddr, pwdata, prdata, pready, scl_pad, sda_pad, irq);
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire ack_out;
  wire [2:0] bit_idx;
  wire busy;
  input clk;
  wire clk;
  wire cmd_read;
  wire cmd_start;
  wire cmd_stop;
  wire cmd_write;
  output irq;
  wire irq;
  wire [2:0] istate;
  input [3:0] paddr;
  wire [3:0] paddr;
  input penable;
  wire penable;
  wire [1:0] phase;
  output [31:0] prdata;
  wire [31:0] prdata;
  output pready;
  wire pready;
  wire [15:0] presc_cnt;
  wire [15:0] prescale;
  input psel;
  wire psel;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  input pwrite;
  wire pwrite;
  input rst_n;
  wire rst_n;
  wire [7:0] rx_data;
  inout scl_pad;
  wire scl_pad;
  inout sda_pad;
  wire sda_pad;
  INVX1 _195_ (
    .A(presc_cnt[3]),
    .Y(_044_)
  );
  INVX1 _196_ (
    .A(presc_cnt[4]),
    .Y(_045_)
  );
  INVX1 _197_ (
    .A(presc_cnt[7]),
    .Y(_046_)
  );
  INVX1 _198_ (
    .A(presc_cnt[6]),
    .Y(_047_)
  );
  INVX1 _199_ (
    .A(presc_cnt[8]),
    .Y(_048_)
  );
  INVX1 _200_ (
    .A(presc_cnt[11]),
    .Y(_049_)
  );
  INVX1 _201_ (
    .A(presc_cnt[10]),
    .Y(_050_)
  );
  INVX1 _202_ (
    .A(presc_cnt[12]),
    .Y(_051_)
  );
  INVX1 _203_ (
    .A(istate[1]),
    .Y(_052_)
  );
  INVX1 _204_ (
    .A(istate[2]),
    .Y(_053_)
  );
  INVX1 _205_ (
    .A(bit_idx[2]),
    .Y(_054_)
  );
  INVX1 _206_ (
    .A(pwrite),
    .Y(_055_)
  );
  INVX1 _207_ (
    .A(paddr[2]),
    .Y(_056_)
  );
  INVX1 _208_ (
    .A(busy),
    .Y(irq)
  );
  INVX1 _209_ (
    .A(prescale[5]),
    .Y(_057_)
  );
  INVX1 _210_ (
    .A(prescale[9]),
    .Y(_058_)
  );
  INVX1 _211_ (
    .A(prescale[15]),
    .Y(_059_)
  );
  OR2X1 _212_ (
    .A(presc_cnt[0]),
    .B(presc_cnt[1]),
    .Y(_060_)
  );
  NOR3X1 _213_ (
    .A(presc_cnt[0]),
    .B(presc_cnt[1]),
    .C(presc_cnt[2]),
    .Y(_061_)
  );
  OR2X1 _214_ (
    .A(presc_cnt[2]),
    .B(_060_),
    .Y(_062_)
  );
  NAND3X1 _215_ (
    .A(_044_),
    .B(_045_),
    .C(_061_),
    .Y(_063_)
  );
  NOR2X1 _216_ (
    .A(presc_cnt[5]),
    .B(_063_),
    .Y(_064_)
  );
  NOR3X1 _217_ (
    .A(presc_cnt[5]),
    .B(presc_cnt[6]),
    .C(_063_),
    .Y(_065_)
  );
  INVX1 _218_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR2X1 _219_ (
    .A(presc_cnt[13]),
    .B(presc_cnt[12]),
    .Y(_067_)
  );
  NOR2X1 _220_ (
    .A(presc_cnt[15]),
    .B(presc_cnt[14]),
    .Y(_068_)
  );
  NAND2X1 _221_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  NOR2X1 _222_ (
    .A(presc_cnt[9]),
    .B(presc_cnt[8]),
    .Y(_070_)
  );
  NAND3X1 _223_ (
    .A(_049_),
    .B(_050_),
    .C(_070_),
    .Y(_071_)
  );
  NOR2X1 _224_ (
    .A(_069_),
    .B(_071_),
    .Y(_072_)
  );
  NAND3X1 _225_ (
    .A(_046_),
    .B(_065_),
    .C(_072_),
    .Y(_073_)
  );
  NOR2X1 _226_ (
    .A(prescale[0]),
    .B(_073_),
    .Y(_074_)
  );
  NOR2X1 _227_ (
    .A(presc_cnt[0]),
    .B(_074_),
    .Y(_000_[0])
  );
  NAND2X1 _228_ (
    .A(presc_cnt[0]),
    .B(presc_cnt[1]),
    .Y(_075_)
  );
  NAND2X1 _229_ (
    .A(_060_),
    .B(_075_),
    .Y(_076_)
  );
  OAI21X1 _230_ (
    .A(prescale[1]),
    .B(_073_),
    .C(_076_),
    .Y(_077_)
  );
  INVX1 _231_ (
    .A(_077_),
    .Y(_000_[1])
  );
  OAI21X1 _232_ (
    .A(presc_cnt[0]),
    .B(presc_cnt[1]),
    .C(presc_cnt[2]),
    .Y(_078_)
  );
  NOR2X1 _233_ (
    .A(prescale[2]),
    .B(_073_),
    .Y(_079_)
  );
  AOI21X1 _234_ (
    .A(_062_),
    .B(_078_),
    .C(_079_),
    .Y(_000_[2])
  );
  XNOR2X1 _235_ (
    .A(presc_cnt[3]),
    .B(_061_),
    .Y(_080_)
  );
  NOR2X1 _236_ (
    .A(prescale[3]),
    .B(_073_),
    .Y(_081_)
  );
  NOR2X1 _237_ (
    .A(_080_),
    .B(_081_),
    .Y(_000_[3])
  );
  OAI21X1 _238_ (
    .A(presc_cnt[3]),
    .B(_062_),
    .C(presc_cnt[4]),
    .Y(_082_)
  );
  NOR2X1 _239_ (
    .A(prescale[4]),
    .B(_073_),
    .Y(_083_)
  );
  AOI21X1 _240_ (
    .A(_063_),
    .B(_082_),
    .C(_083_),
    .Y(_000_[4])
  );
  AND2X1 _241_ (
    .A(presc_cnt[5]),
    .B(_063_),
    .Y(_084_)
  );
  OAI21X1 _242_ (
    .A(_064_),
    .B(_084_),
    .C(_073_),
    .Y(_085_)
  );
  OAI21X1 _243_ (
    .A(_057_),
    .B(_073_),
    .C(_085_),
    .Y(_000_[5])
  );
  NOR2X1 _244_ (
    .A(_047_),
    .B(_064_),
    .Y(_086_)
  );
  OAI22X1 _245_ (
    .A(prescale[6]),
    .B(_073_),
    .C(_086_),
    .D(_065_),
    .Y(_087_)
  );
  INVX1 _246_ (
    .A(_087_),
    .Y(_000_[6])
  );
  XNOR2X1 _247_ (
    .A(_046_),
    .B(_065_),
    .Y(_088_)
  );
  OAI21X1 _248_ (
    .A(prescale[7]),
    .B(_073_),
    .C(_088_),
    .Y(_089_)
  );
  INVX1 _249_ (
    .A(_089_),
    .Y(_000_[7])
  );
  NAND3X1 _250_ (
    .A(_046_),
    .B(_048_),
    .C(_065_),
    .Y(_090_)
  );
  OAI21X1 _251_ (
    .A(presc_cnt[7]),
    .B(_066_),
    .C(presc_cnt[8]),
    .Y(_091_)
  );
  NOR2X1 _252_ (
    .A(prescale[8]),
    .B(_073_),
    .Y(_092_)
  );
  AOI21X1 _253_ (
    .A(_090_),
    .B(_091_),
    .C(_092_),
    .Y(_000_[8])
  );
  NOR2X1 _254_ (
    .A(presc_cnt[9]),
    .B(_090_),
    .Y(_093_)
  );
  AND2X1 _255_ (
    .A(presc_cnt[9]),
    .B(_090_),
    .Y(_094_)
  );
  OAI21X1 _256_ (
    .A(_093_),
    .B(_094_),
    .C(_073_),
    .Y(_095_)
  );
  OAI21X1 _257_ (
    .A(_058_),
    .B(_073_),
    .C(_095_),
    .Y(_000_[9])
  );
  NOR3X1 _258_ (
    .A(presc_cnt[9]),
    .B(presc_cnt[10]),
    .C(_090_),
    .Y(_096_)
  );
  OAI21X1 _259_ (
    .A(_050_),
    .B(_093_),
    .C(_073_),
    .Y(_097_)
  );
  OAI22X1 _260_ (
    .A(prescale[10]),
    .B(_073_),
    .C(_096_),
    .D(_097_),
    .Y(_098_)
  );
  INVX1 _261_ (
    .A(_098_),
    .Y(_000_[10])
  );
  NAND2X1 _262_ (
    .A(_049_),
    .B(_096_),
    .Y(_099_)
  );
  XNOR2X1 _263_ (
    .A(_049_),
    .B(_096_),
    .Y(_100_)
  );
  OAI21X1 _264_ (
    .A(prescale[11]),
    .B(_073_),
    .C(_100_),
    .Y(_101_)
  );
  INVX1 _265_ (
    .A(_101_),
    .Y(_000_[11])
  );
  NAND3X1 _266_ (
    .A(_049_),
    .B(_051_),
    .C(_096_),
    .Y(_102_)
  );
  XNOR2X1 _267_ (
    .A(presc_cnt[12]),
    .B(_099_),
    .Y(_103_)
  );
  OAI21X1 _268_ (
    .A(prescale[12]),
    .B(_073_),
    .C(_103_),
    .Y(_104_)
  );
  INVX1 _269_ (
    .A(_104_),
    .Y(_000_[12])
  );
  OR2X1 _270_ (
    .A(presc_cnt[13]),
    .B(_102_),
    .Y(_105_)
  );
  XNOR2X1 _271_ (
    .A(presc_cnt[13]),
    .B(_102_),
    .Y(_106_)
  );
  OAI21X1 _272_ (
    .A(prescale[13]),
    .B(_073_),
    .C(_106_),
    .Y(_107_)
  );
  INVX1 _273_ (
    .A(_107_),
    .Y(_000_[13])
  );
  XOR2X1 _274_ (
    .A(presc_cnt[14]),
    .B(_105_),
    .Y(_108_)
  );
  NOR2X1 _275_ (
    .A(prescale[14]),
    .B(_073_),
    .Y(_109_)
  );
  NOR2X1 _276_ (
    .A(_108_),
    .B(_109_),
    .Y(_000_[14])
  );
  OAI21X1 _277_ (
    .A(presc_cnt[14]),
    .B(_105_),
    .C(presc_cnt[15]),
    .Y(_110_)
  );
  OAI21X1 _278_ (
    .A(_059_),
    .B(_073_),
    .C(_110_),
    .Y(_000_[15])
  );
  NAND2X1 _279_ (
    .A(phase[0]),
    .B(phase[1]),
    .Y(_111_)
  );
  NAND2X1 _280_ (
    .A(_052_),
    .B(istate[2]),
    .Y(_112_)
  );
  NOR2X1 _281_ (
    .A(_052_),
    .B(istate[2]),
    .Y(_113_)
  );
  INVX1 _282_ (
    .A(_113_),
    .Y(_114_)
  );
  NAND2X1 _283_ (
    .A(_112_),
    .B(_114_),
    .Y(_115_)
  );
  OAI21X1 _284_ (
    .A(_073_),
    .B(_111_),
    .C(_115_),
    .Y(_116_)
  );
  NOR2X1 _285_ (
    .A(cmd_read),
    .B(cmd_write),
    .Y(_117_)
  );
  NAND3X1 _286_ (
    .A(_052_),
    .B(_053_),
    .C(_117_),
    .Y(_118_)
  );
  OR2X1 _287_ (
    .A(bit_idx[1]),
    .B(bit_idx[0]),
    .Y(_119_)
  );
  NOR2X1 _288_ (
    .A(bit_idx[2]),
    .B(_119_),
    .Y(_120_)
  );
  OAI21X1 _289_ (
    .A(bit_idx[2]),
    .B(_119_),
    .C(_113_),
    .Y(_121_)
  );
  NAND3X1 _290_ (
    .A(_116_),
    .B(_118_),
    .C(_121_),
    .Y(_122_)
  );
  NAND2X1 _291_ (
    .A(istate[1]),
    .B(_122_),
    .Y(_123_)
  );
  OAI21X1 _292_ (
    .A(_073_),
    .B(_111_),
    .C(_113_),
    .Y(_124_)
  );
  NAND3X1 _293_ (
    .A(_053_),
    .B(_118_),
    .C(_124_),
    .Y(_125_)
  );
  OAI21X1 _294_ (
    .A(_113_),
    .B(_125_),
    .C(_123_),
    .Y(_001_)
  );
  MUX2X1 _295_ (
    .A(istate[2]),
    .B(_113_),
    .S(_122_),
    .Y(_126_)
  );
  INVX1 _296_ (
    .A(_126_),
    .Y(_002_)
  );
  NOR2X1 _297_ (
    .A(paddr[3]),
    .B(paddr[2]),
    .Y(_127_)
  );
  NAND3X1 _298_ (
    .A(penable),
    .B(psel),
    .C(pwrite),
    .Y(_128_)
  );
  INVX1 _299_ (
    .A(_128_),
    .Y(_129_)
  );
  AND2X1 _300_ (
    .A(_127_),
    .B(_129_),
    .Y(_130_)
  );
  MUX2X1 _301_ (
    .A(pwdata[0]),
    .B(prescale[0]),
    .S(_130_),
    .Y(_131_)
  );
  INVX1 _302_ (
    .A(_131_),
    .Y(_003_)
  );
  MUX2X1 _303_ (
    .A(pwdata[1]),
    .B(prescale[1]),
    .S(_130_),
    .Y(_132_)
  );
  INVX1 _304_ (
    .A(_132_),
    .Y(_004_)
  );
  MUX2X1 _305_ (
    .A(pwdata[2]),
    .B(prescale[2]),
    .S(_130_),
    .Y(_133_)
  );
  INVX1 _306_ (
    .A(_133_),
    .Y(_005_)
  );
  MUX2X1 _307_ (
    .A(pwdata[3]),
    .B(prescale[3]),
    .S(_130_),
    .Y(_134_)
  );
  INVX1 _308_ (
    .A(_134_),
    .Y(_006_)
  );
  MUX2X1 _309_ (
    .A(pwdata[4]),
    .B(prescale[4]),
    .S(_130_),
    .Y(_135_)
  );
  INVX1 _310_ (
    .A(_135_),
    .Y(_007_)
  );
  MUX2X1 _311_ (
    .A(pwdata[5]),
    .B(prescale[5]),
    .S(_130_),
    .Y(_136_)
  );
  INVX1 _312_ (
    .A(_136_),
    .Y(_008_)
  );
  MUX2X1 _313_ (
    .A(pwdata[6]),
    .B(prescale[6]),
    .S(_130_),
    .Y(_137_)
  );
  INVX1 _314_ (
    .A(_137_),
    .Y(_009_)
  );
  MUX2X1 _315_ (
    .A(pwdata[7]),
    .B(prescale[7]),
    .S(_130_),
    .Y(_138_)
  );
  INVX1 _316_ (
    .A(_138_),
    .Y(_010_)
  );
  MUX2X1 _317_ (
    .A(pwdata[8]),
    .B(prescale[8]),
    .S(_130_),
    .Y(_139_)
  );
  INVX1 _318_ (
    .A(_139_),
    .Y(_011_)
  );
  MUX2X1 _319_ (
    .A(pwdata[9]),
    .B(prescale[9]),
    .S(_130_),
    .Y(_140_)
  );
  INVX1 _320_ (
    .A(_140_),
    .Y(_012_)
  );
  MUX2X1 _321_ (
    .A(pwdata[10]),
    .B(prescale[10]),
    .S(_130_),
    .Y(_141_)
  );
  INVX1 _322_ (
    .A(_141_),
    .Y(_013_)
  );
  MUX2X1 _323_ (
    .A(pwdata[11]),
    .B(prescale[11]),
    .S(_130_),
    .Y(_142_)
  );
  INVX1 _324_ (
    .A(_142_),
    .Y(_014_)
  );
  MUX2X1 _325_ (
    .A(pwdata[12]),
    .B(prescale[12]),
    .S(_130_),
    .Y(_143_)
  );
  INVX1 _326_ (
    .A(_143_),
    .Y(_015_)
  );
  MUX2X1 _327_ (
    .A(pwdata[13]),
    .B(prescale[13]),
    .S(_130_),
    .Y(_144_)
  );
  INVX1 _328_ (
    .A(_144_),
    .Y(_016_)
  );
  MUX2X1 _329_ (
    .A(pwdata[14]),
    .B(prescale[14]),
    .S(_130_),
    .Y(_145_)
  );
  INVX1 _330_ (
    .A(_145_),
    .Y(_017_)
  );
  MUX2X1 _331_ (
    .A(pwdata[15]),
    .B(prescale[15]),
    .S(_130_),
    .Y(_146_)
  );
  INVX1 _332_ (
    .A(_146_),
    .Y(_018_)
  );
  NAND3X1 _333_ (
    .A(paddr[3]),
    .B(_056_),
    .C(_129_),
    .Y(_147_)
  );
  MUX2X1 _334_ (
    .A(cmd_read),
    .B(pwdata[1]),
    .S(_147_),
    .Y(_148_)
  );
  INVX1 _335_ (
    .A(_148_),
    .Y(_019_)
  );
  MUX2X1 _336_ (
    .A(cmd_write),
    .B(pwdata[0]),
    .S(_147_),
    .Y(_149_)
  );
  INVX1 _337_ (
    .A(_149_),
    .Y(_020_)
  );
  NAND2X1 _338_ (
    .A(_052_),
    .B(_118_),
    .Y(_150_)
  );
  AOI21X1 _339_ (
    .A(istate[2]),
    .B(_122_),
    .C(_150_),
    .Y(_151_)
  );
  OAI22X1 _340_ (
    .A(_113_),
    .B(_125_),
    .C(_151_),
    .D(irq),
    .Y(_021_)
  );
  AOI21X1 _341_ (
    .A(_112_),
    .B(_114_),
    .C(_073_),
    .Y(_152_)
  );
  NAND2X1 _342_ (
    .A(phase[0]),
    .B(_152_),
    .Y(_153_)
  );
  XOR2X1 _343_ (
    .A(phase[0]),
    .B(_152_),
    .Y(_022_)
  );
  XNOR2X1 _344_ (
    .A(phase[1]),
    .B(_153_),
    .Y(_023_)
  );
  NAND3X1 _345_ (
    .A(penable),
    .B(psel),
    .C(_055_),
    .Y(_154_)
  );
  OAI21X1 _346_ (
    .A(paddr[3]),
    .B(prescale[0]),
    .C(_056_),
    .Y(_155_)
  );
  NAND2X1 _347_ (
    .A(prdata[0]),
    .B(_154_),
    .Y(_156_)
  );
  OAI21X1 _348_ (
    .A(_154_),
    .B(_155_),
    .C(_156_),
    .Y(_024_)
  );
  NAND2X1 _349_ (
    .A(prdata[1]),
    .B(_154_),
    .Y(_157_)
  );
  NAND2X1 _350_ (
    .A(prescale[1]),
    .B(_127_),
    .Y(_158_)
  );
  OAI21X1 _351_ (
    .A(_154_),
    .B(_158_),
    .C(_157_),
    .Y(_025_)
  );
  NAND2X1 _352_ (
    .A(prdata[2]),
    .B(_154_),
    .Y(_159_)
  );
  NAND2X1 _353_ (
    .A(prescale[2]),
    .B(_127_),
    .Y(_160_)
  );
  OAI21X1 _354_ (
    .A(_154_),
    .B(_160_),
    .C(_159_),
    .Y(_026_)
  );
  NAND2X1 _355_ (
    .A(prdata[3]),
    .B(_154_),
    .Y(_161_)
  );
  NAND2X1 _356_ (
    .A(prescale[3]),
    .B(_127_),
    .Y(_162_)
  );
  OAI21X1 _357_ (
    .A(_154_),
    .B(_162_),
    .C(_161_),
    .Y(_027_)
  );
  NAND2X1 _358_ (
    .A(prdata[4]),
    .B(_154_),
    .Y(_163_)
  );
  NAND2X1 _359_ (
    .A(prescale[4]),
    .B(_127_),
    .Y(_164_)
  );
  OAI21X1 _360_ (
    .A(_154_),
    .B(_164_),
    .C(_163_),
    .Y(_028_)
  );
  NAND2X1 _361_ (
    .A(prdata[5]),
    .B(_154_),
    .Y(_165_)
  );
  NAND2X1 _362_ (
    .A(prescale[5]),
    .B(_127_),
    .Y(_166_)
  );
  OAI21X1 _363_ (
    .A(_154_),
    .B(_166_),
    .C(_165_),
    .Y(_029_)
  );
  NAND2X1 _364_ (
    .A(prdata[6]),
    .B(_154_),
    .Y(_167_)
  );
  NAND2X1 _365_ (
    .A(prescale[6]),
    .B(_127_),
    .Y(_168_)
  );
  OAI21X1 _366_ (
    .A(_154_),
    .B(_168_),
    .C(_167_),
    .Y(_030_)
  );
  NAND2X1 _367_ (
    .A(prdata[7]),
    .B(_154_),
    .Y(_169_)
  );
  NAND2X1 _368_ (
    .A(prescale[7]),
    .B(_127_),
    .Y(_170_)
  );
  OAI21X1 _369_ (
    .A(_154_),
    .B(_170_),
    .C(_169_),
    .Y(_031_)
  );
  NAND2X1 _370_ (
    .A(prdata[8]),
    .B(_154_),
    .Y(_171_)
  );
  NAND2X1 _371_ (
    .A(prescale[8]),
    .B(_127_),
    .Y(_172_)
  );
  OAI21X1 _372_ (
    .A(_154_),
    .B(_172_),
    .C(_171_),
    .Y(_032_)
  );
  NAND2X1 _373_ (
    .A(prdata[9]),
    .B(_154_),
    .Y(_173_)
  );
  NAND2X1 _374_ (
    .A(prescale[9]),
    .B(_127_),
    .Y(_174_)
  );
  OAI21X1 _375_ (
    .A(_154_),
    .B(_174_),
    .C(_173_),
    .Y(_033_)
  );
  NAND2X1 _376_ (
    .A(prdata[10]),
    .B(_154_),
    .Y(_175_)
  );
  NAND2X1 _377_ (
    .A(prescale[10]),
    .B(_127_),
    .Y(_176_)
  );
  OAI21X1 _378_ (
    .A(_154_),
    .B(_176_),
    .C(_175_),
    .Y(_034_)
  );
  NAND2X1 _379_ (
    .A(prdata[11]),
    .B(_154_),
    .Y(_177_)
  );
  NAND2X1 _380_ (
    .A(prescale[11]),
    .B(_127_),
    .Y(_178_)
  );
  OAI21X1 _381_ (
    .A(_154_),
    .B(_178_),
    .C(_177_),
    .Y(_035_)
  );
  NAND2X1 _382_ (
    .A(prdata[12]),
    .B(_154_),
    .Y(_179_)
  );
  NAND2X1 _383_ (
    .A(prescale[12]),
    .B(_127_),
    .Y(_180_)
  );
  OAI21X1 _384_ (
    .A(_154_),
    .B(_180_),
    .C(_179_),
    .Y(_036_)
  );
  NAND2X1 _385_ (
    .A(prdata[13]),
    .B(_154_),
    .Y(_181_)
  );
  NAND2X1 _386_ (
    .A(prescale[13]),
    .B(_127_),
    .Y(_182_)
  );
  OAI21X1 _387_ (
    .A(_154_),
    .B(_182_),
    .C(_181_),
    .Y(_037_)
  );
  NAND2X1 _388_ (
    .A(prdata[14]),
    .B(_154_),
    .Y(_183_)
  );
  NAND2X1 _389_ (
    .A(prescale[14]),
    .B(_127_),
    .Y(_184_)
  );
  OAI21X1 _390_ (
    .A(_154_),
    .B(_184_),
    .C(_183_),
    .Y(_038_)
  );
  NAND2X1 _391_ (
    .A(prdata[15]),
    .B(_154_),
    .Y(_185_)
  );
  NAND2X1 _392_ (
    .A(prescale[15]),
    .B(_127_),
    .Y(_186_)
  );
  OAI21X1 _393_ (
    .A(_154_),
    .B(_186_),
    .C(_185_),
    .Y(_039_)
  );
  NAND2X1 _394_ (
    .A(prdata[31]),
    .B(_154_),
    .Y(_187_)
  );
  NAND2X1 _395_ (
    .A(busy),
    .B(_127_),
    .Y(_188_)
  );
  OAI21X1 _396_ (
    .A(_154_),
    .B(_188_),
    .C(_187_),
    .Y(_040_)
  );
  OAI21X1 _397_ (
    .A(bit_idx[0]),
    .B(_120_),
    .C(_113_),
    .Y(_189_)
  );
  MUX2X1 _398_ (
    .A(bit_idx[0]),
    .B(_189_),
    .S(_125_),
    .Y(_190_)
  );
  INVX1 _399_ (
    .A(_190_),
    .Y(_041_)
  );
  AOI21X1 _400_ (
    .A(bit_idx[1]),
    .B(bit_idx[0]),
    .C(_114_),
    .Y(_191_)
  );
  OAI21X1 _401_ (
    .A(_054_),
    .B(_119_),
    .C(_191_),
    .Y(_192_)
  );
  MUX2X1 _402_ (
    .A(bit_idx[1]),
    .B(_192_),
    .S(_125_),
    .Y(_193_)
  );
  INVX1 _403_ (
    .A(_193_),
    .Y(_042_)
  );
  OAI21X1 _404_ (
    .A(_119_),
    .B(_125_),
    .C(bit_idx[2]),
    .Y(_194_)
  );
  OAI21X1 _405_ (
    .A(_113_),
    .B(_125_),
    .C(_194_),
    .Y(_043_)
  );
  DFFSR _406_ (
    .CLK(clk),
    .D(_001_),
    .Q(istate[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _407_ (
    .CLK(clk),
    .D(_002_),
    .Q(istate[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _408_ (
    .CLK(clk),
    .D(_003_),
    .Q(prescale[0]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _409_ (
    .CLK(clk),
    .D(_004_),
    .Q(prescale[1]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _410_ (
    .CLK(clk),
    .D(_005_),
    .Q(prescale[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _411_ (
    .CLK(clk),
    .D(_006_),
    .Q(prescale[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _412_ (
    .CLK(clk),
    .D(_007_),
    .Q(prescale[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _413_ (
    .CLK(clk),
    .D(_008_),
    .Q(prescale[5]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _414_ (
    .CLK(clk),
    .D(_009_),
    .Q(prescale[6]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _415_ (
    .CLK(clk),
    .D(_010_),
    .Q(prescale[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _416_ (
    .CLK(clk),
    .D(_011_),
    .Q(prescale[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _417_ (
    .CLK(clk),
    .D(_012_),
    .Q(prescale[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _418_ (
    .CLK(clk),
    .D(_013_),
    .Q(prescale[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _419_ (
    .CLK(clk),
    .D(_014_),
    .Q(prescale[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _420_ (
    .CLK(clk),
    .D(_015_),
    .Q(prescale[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _421_ (
    .CLK(clk),
    .D(_016_),
    .Q(prescale[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _422_ (
    .CLK(clk),
    .D(_017_),
    .Q(prescale[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _423_ (
    .CLK(clk),
    .D(_018_),
    .Q(prescale[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _424_ (
    .CLK(clk),
    .D(_019_),
    .Q(cmd_read),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _425_ (
    .CLK(clk),
    .D(_020_),
    .Q(cmd_write),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _426_ (
    .CLK(clk),
    .D(_021_),
    .Q(busy),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _427_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(presc_cnt[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _428_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(presc_cnt[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _429_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(presc_cnt[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _430_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(presc_cnt[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _431_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(presc_cnt[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _432_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(presc_cnt[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _433_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(presc_cnt[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _434_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(presc_cnt[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _435_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(presc_cnt[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _436_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(presc_cnt[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _437_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(presc_cnt[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _438_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(presc_cnt[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _439_ (
    .CLK(clk),
    .D(_000_[12]),
    .Q(presc_cnt[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _440_ (
    .CLK(clk),
    .D(_000_[13]),
    .Q(presc_cnt[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _441_ (
    .CLK(clk),
    .D(_000_[14]),
    .Q(presc_cnt[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _442_ (
    .CLK(clk),
    .D(_000_[15]),
    .Q(presc_cnt[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _443_ (
    .CLK(clk),
    .D(_022_),
    .Q(phase[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _444_ (
    .CLK(clk),
    .D(_023_),
    .Q(phase[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _445_ (
    .CLK(clk),
    .D(_024_),
    .Q(prdata[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _446_ (
    .CLK(clk),
    .D(_025_),
    .Q(prdata[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _447_ (
    .CLK(clk),
    .D(_026_),
    .Q(prdata[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _448_ (
    .CLK(clk),
    .D(_027_),
    .Q(prdata[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _449_ (
    .CLK(clk),
    .D(_028_),
    .Q(prdata[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _450_ (
    .CLK(clk),
    .D(_029_),
    .Q(prdata[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _451_ (
    .CLK(clk),
    .D(_030_),
    .Q(prdata[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _452_ (
    .CLK(clk),
    .D(_031_),
    .Q(prdata[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _453_ (
    .CLK(clk),
    .D(_032_),
    .Q(prdata[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _454_ (
    .CLK(clk),
    .D(_033_),
    .Q(prdata[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _455_ (
    .CLK(clk),
    .D(_034_),
    .Q(prdata[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _456_ (
    .CLK(clk),
    .D(_035_),
    .Q(prdata[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _457_ (
    .CLK(clk),
    .D(_036_),
    .Q(prdata[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _458_ (
    .CLK(clk),
    .D(_037_),
    .Q(prdata[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _459_ (
    .CLK(clk),
    .D(_038_),
    .Q(prdata[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _460_ (
    .CLK(clk),
    .D(_039_),
    .Q(prdata[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _461_ (
    .CLK(clk),
    .D(_040_),
    .Q(prdata[31]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _462_ (
    .CLK(clk),
    .D(_041_),
    .Q(bit_idx[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _463_ (
    .CLK(clk),
    .D(_042_),
    .Q(bit_idx[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _464_ (
    .CLK(clk),
    .D(_043_),
    .Q(bit_idx[2]),
    .R(rst_n),
    .S(1'h1)
  );
  assign ack_out = 1'h1;
  assign cmd_start = 1'h0;
  assign cmd_stop = 1'h0;
  assign istate[0] = 1'h0;
  assign prdata[30:16] = 15'h0000;
  assign pready = 1'h1;
  assign rx_data = 8'h00;
  assign scl_pad = 1'h0;
  assign sda_pad = 1'h0;
endmodule
