/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module reset_sync(clk, async_rst_n, sync_rst_n);
  input async_rst_n;
  wire async_rst_n;
  input clk;
  wire clk;
  wire [1:0] sync_chain;
  output sync_rst_n;
  wire sync_rst_n;
  DFFSR _0_ (
    .CLK(clk),
    .D(1'h1),
    .Q(sync_chain[0]),
    .R(async_rst_n),
    .S(1'h1)
  );
  DFFSR _1_ (
    .CLK(clk),
    .D(sync_chain[0]),
    .Q(sync_chain[1]),
    .R(async_rst_n),
    .S(1'h1)
  );
  assign sync_rst_n = sync_chain[1];
endmodule
