/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module rv_writeback(clk, rst_n, result, rd_in, reg_write, valid_in, wb_data, wb_rd, wb_we, fwd_wb_data, fwd_wb_rd, fwd_wb_valid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input clk;
  wire clk;
  output [63:0] fwd_wb_data;
  wire [63:0] fwd_wb_data;
  output [4:0] fwd_wb_rd;
  wire [4:0] fwd_wb_rd;
  output fwd_wb_valid;
  wire fwd_wb_valid;
  input [4:0] rd_in;
  wire [4:0] rd_in;
  input reg_write;
  wire reg_write;
  input [63:0] result;
  wire [63:0] result;
  input rst_n;
  wire rst_n;
  input valid_in;
  wire valid_in;
  output [63:0] wb_data;
  wire [63:0] wb_data;
  output [4:0] wb_rd;
  wire [4:0] wb_rd;
  output wb_we;
  wire wb_we;
  NOR2X1 _04_ (
    .A(rd_in[1]),
    .B(rd_in[0]),
    .Y(_03_)
  );
  NOR3X1 _05_ (
    .A(rd_in[3]),
    .B(rd_in[2]),
    .C(rd_in[4]),
    .Y(_01_)
  );
  NAND2X1 _06_ (
    .A(valid_in),
    .B(reg_write),
    .Y(_02_)
  );
  AOI21X1 _07_ (
    .A(_03_),
    .B(_01_),
    .C(_02_),
    .Y(_00_)
  );
  DFFSR _08_ (
    .CLK(clk),
    .D(result[5]),
    .Q(wb_data[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _09_ (
    .CLK(clk),
    .D(result[6]),
    .Q(wb_data[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _10_ (
    .CLK(clk),
    .D(result[7]),
    .Q(wb_data[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _11_ (
    .CLK(clk),
    .D(result[8]),
    .Q(wb_data[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _12_ (
    .CLK(clk),
    .D(result[9]),
    .Q(wb_data[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _13_ (
    .CLK(clk),
    .D(result[10]),
    .Q(wb_data[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _14_ (
    .CLK(clk),
    .D(result[11]),
    .Q(wb_data[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _15_ (
    .CLK(clk),
    .D(result[12]),
    .Q(wb_data[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _16_ (
    .CLK(clk),
    .D(result[13]),
    .Q(wb_data[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _17_ (
    .CLK(clk),
    .D(result[14]),
    .Q(wb_data[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _18_ (
    .CLK(clk),
    .D(result[15]),
    .Q(wb_data[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _19_ (
    .CLK(clk),
    .D(result[16]),
    .Q(wb_data[16]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _20_ (
    .CLK(clk),
    .D(result[17]),
    .Q(wb_data[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _21_ (
    .CLK(clk),
    .D(result[18]),
    .Q(wb_data[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _22_ (
    .CLK(clk),
    .D(result[19]),
    .Q(wb_data[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _23_ (
    .CLK(clk),
    .D(result[20]),
    .Q(wb_data[20]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _24_ (
    .CLK(clk),
    .D(result[21]),
    .Q(wb_data[21]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _25_ (
    .CLK(clk),
    .D(result[22]),
    .Q(wb_data[22]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _26_ (
    .CLK(clk),
    .D(result[23]),
    .Q(wb_data[23]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _27_ (
    .CLK(clk),
    .D(result[24]),
    .Q(wb_data[24]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _28_ (
    .CLK(clk),
    .D(result[25]),
    .Q(wb_data[25]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _29_ (
    .CLK(clk),
    .D(result[26]),
    .Q(wb_data[26]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _30_ (
    .CLK(clk),
    .D(result[27]),
    .Q(wb_data[27]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _31_ (
    .CLK(clk),
    .D(result[28]),
    .Q(wb_data[28]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _32_ (
    .CLK(clk),
    .D(result[29]),
    .Q(wb_data[29]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _33_ (
    .CLK(clk),
    .D(result[30]),
    .Q(wb_data[30]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _34_ (
    .CLK(clk),
    .D(result[31]),
    .Q(wb_data[31]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _35_ (
    .CLK(clk),
    .D(result[32]),
    .Q(wb_data[32]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _36_ (
    .CLK(clk),
    .D(result[33]),
    .Q(wb_data[33]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _37_ (
    .CLK(clk),
    .D(result[34]),
    .Q(wb_data[34]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _38_ (
    .CLK(clk),
    .D(result[35]),
    .Q(wb_data[35]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _39_ (
    .CLK(clk),
    .D(result[36]),
    .Q(wb_data[36]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _40_ (
    .CLK(clk),
    .D(result[37]),
    .Q(wb_data[37]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _41_ (
    .CLK(clk),
    .D(result[38]),
    .Q(wb_data[38]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _42_ (
    .CLK(clk),
    .D(result[39]),
    .Q(wb_data[39]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _43_ (
    .CLK(clk),
    .D(result[40]),
    .Q(wb_data[40]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _44_ (
    .CLK(clk),
    .D(result[41]),
    .Q(wb_data[41]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _45_ (
    .CLK(clk),
    .D(result[42]),
    .Q(wb_data[42]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _46_ (
    .CLK(clk),
    .D(result[43]),
    .Q(wb_data[43]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _47_ (
    .CLK(clk),
    .D(result[44]),
    .Q(wb_data[44]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _48_ (
    .CLK(clk),
    .D(result[45]),
    .Q(wb_data[45]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _49_ (
    .CLK(clk),
    .D(result[46]),
    .Q(wb_data[46]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _50_ (
    .CLK(clk),
    .D(result[47]),
    .Q(wb_data[47]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _51_ (
    .CLK(clk),
    .D(result[48]),
    .Q(wb_data[48]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _52_ (
    .CLK(clk),
    .D(result[49]),
    .Q(wb_data[49]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _53_ (
    .CLK(clk),
    .D(result[50]),
    .Q(wb_data[50]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _54_ (
    .CLK(clk),
    .D(result[51]),
    .Q(wb_data[51]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _55_ (
    .CLK(clk),
    .D(result[52]),
    .Q(wb_data[52]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _56_ (
    .CLK(clk),
    .D(result[53]),
    .Q(wb_data[53]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _57_ (
    .CLK(clk),
    .D(result[54]),
    .Q(wb_data[54]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _58_ (
    .CLK(clk),
    .D(result[55]),
    .Q(wb_data[55]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _59_ (
    .CLK(clk),
    .D(result[56]),
    .Q(wb_data[56]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _60_ (
    .CLK(clk),
    .D(result[57]),
    .Q(wb_data[57]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _61_ (
    .CLK(clk),
    .D(result[58]),
    .Q(wb_data[58]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _62_ (
    .CLK(clk),
    .D(result[59]),
    .Q(wb_data[59]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _63_ (
    .CLK(clk),
    .D(result[60]),
    .Q(wb_data[60]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _64_ (
    .CLK(clk),
    .D(result[61]),
    .Q(wb_data[61]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _65_ (
    .CLK(clk),
    .D(result[62]),
    .Q(wb_data[62]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _66_ (
    .CLK(clk),
    .D(result[63]),
    .Q(wb_data[63]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _67_ (
    .CLK(clk),
    .D(rd_in[0]),
    .Q(wb_rd[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _68_ (
    .CLK(clk),
    .D(rd_in[1]),
    .Q(wb_rd[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _69_ (
    .CLK(clk),
    .D(rd_in[2]),
    .Q(wb_rd[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _70_ (
    .CLK(clk),
    .D(rd_in[3]),
    .Q(wb_rd[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _71_ (
    .CLK(clk),
    .D(rd_in[4]),
    .Q(wb_rd[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _72_ (
    .CLK(clk),
    .D(_00_),
    .Q(wb_we),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _73_ (
    .CLK(clk),
    .D(result[0]),
    .Q(wb_data[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _74_ (
    .CLK(clk),
    .D(result[1]),
    .Q(wb_data[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _75_ (
    .CLK(clk),
    .D(result[2]),
    .Q(wb_data[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _76_ (
    .CLK(clk),
    .D(result[3]),
    .Q(wb_data[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _77_ (
    .CLK(clk),
    .D(result[4]),
    .Q(wb_data[4]),
    .R(rst_n),
    .S(1'h1)
  );
  assign fwd_wb_data = wb_data;
  assign fwd_wb_rd = wb_rd;
  assign fwd_wb_valid = wb_we;
endmodule
