/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module spi_master(clk, rst_n, psel, penable, pwrite, paddr, pwdata, prdata, pready, spi_clk, spi_mosi, spi_miso, spi_csn, irq);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire [2:0] bit_cnt;
  wire busy;
  input clk;
  wire clk;
  wire [15:0] clk_cnt;
  wire [15:0] clk_div;
  wire cpol;
  output irq;
  wire irq;
  wire mosi_r;
  input [3:0] paddr;
  wire [3:0] paddr;
  input penable;
  wire penable;
  output [31:0] prdata;
  wire [31:0] prdata;
  output pready;
  wire pready;
  input psel;
  wire psel;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  input pwrite;
  wire pwrite;
  input rst_n;
  wire rst_n;
  wire [7:0] rx_data;
  wire sclk_r;
  wire [7:0] shift_in;
  wire [7:0] shift_out;
  output spi_clk;
  wire spi_clk;
  output [3:0] spi_csn;
  wire [3:0] spi_csn;
  input spi_miso;
  wire spi_miso;
  output spi_mosi;
  wire spi_mosi;
  wire start;
  INVX1 _105_ (
    .A(paddr[2]),
    .Y(_093_)
  );
  INVX1 _106_ (
    .A(paddr[3]),
    .Y(_094_)
  );
  INVX1 _107_ (
    .A(clk_div[0]),
    .Y(_095_)
  );
  INVX1 _108_ (
    .A(clk_div[1]),
    .Y(_096_)
  );
  INVX1 _109_ (
    .A(clk_div[2]),
    .Y(_097_)
  );
  INVX1 _110_ (
    .A(clk_div[3]),
    .Y(_098_)
  );
  INVX1 _111_ (
    .A(clk_div[4]),
    .Y(_099_)
  );
  INVX1 _112_ (
    .A(clk_div[5]),
    .Y(_100_)
  );
  INVX1 _113_ (
    .A(clk_div[6]),
    .Y(_101_)
  );
  INVX1 _114_ (
    .A(clk_div[7]),
    .Y(_102_)
  );
  INVX1 _115_ (
    .A(clk_div[8]),
    .Y(_103_)
  );
  INVX1 _116_ (
    .A(clk_div[9]),
    .Y(_104_)
  );
  INVX1 _117_ (
    .A(clk_div[10]),
    .Y(_033_)
  );
  INVX1 _118_ (
    .A(clk_div[11]),
    .Y(_034_)
  );
  INVX1 _119_ (
    .A(clk_div[12]),
    .Y(_035_)
  );
  INVX1 _120_ (
    .A(clk_div[13]),
    .Y(_036_)
  );
  INVX1 _121_ (
    .A(clk_div[14]),
    .Y(_037_)
  );
  INVX1 _122_ (
    .A(clk_div[15]),
    .Y(_038_)
  );
  INVX1 _123_ (
    .A(pwdata[0]),
    .Y(_039_)
  );
  INVX1 _124_ (
    .A(pwdata[1]),
    .Y(_040_)
  );
  INVX1 _125_ (
    .A(pwdata[2]),
    .Y(_041_)
  );
  INVX1 _126_ (
    .A(pwdata[3]),
    .Y(_042_)
  );
  INVX1 _127_ (
    .A(pwdata[4]),
    .Y(_043_)
  );
  INVX1 _128_ (
    .A(pwdata[5]),
    .Y(_044_)
  );
  INVX1 _129_ (
    .A(pwdata[6]),
    .Y(_045_)
  );
  INVX1 _130_ (
    .A(pwdata[7]),
    .Y(_046_)
  );
  INVX1 _131_ (
    .A(pwdata[8]),
    .Y(_047_)
  );
  INVX1 _132_ (
    .A(pwdata[9]),
    .Y(_048_)
  );
  INVX1 _133_ (
    .A(pwdata[10]),
    .Y(_049_)
  );
  INVX1 _134_ (
    .A(pwdata[11]),
    .Y(_050_)
  );
  INVX1 _135_ (
    .A(pwdata[12]),
    .Y(_051_)
  );
  INVX1 _136_ (
    .A(pwdata[13]),
    .Y(_052_)
  );
  INVX1 _137_ (
    .A(pwdata[14]),
    .Y(_053_)
  );
  INVX1 _138_ (
    .A(pwdata[15]),
    .Y(_054_)
  );
  INVX1 _139_ (
    .A(cpol),
    .Y(_055_)
  );
  NAND2X1 _140_ (
    .A(penable),
    .B(psel),
    .Y(_056_)
  );
  OR2X1 _141_ (
    .A(pwrite),
    .B(_056_),
    .Y(_057_)
  );
  OAI21X1 _142_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[0]),
    .Y(_058_)
  );
  NAND3X1 _143_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[0]),
    .Y(_059_)
  );
  OAI21X1 _144_ (
    .A(_057_),
    .B(_059_),
    .C(_058_),
    .Y(_000_)
  );
  OAI21X1 _145_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[1]),
    .Y(_060_)
  );
  NAND3X1 _146_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[1]),
    .Y(_061_)
  );
  OAI21X1 _147_ (
    .A(_057_),
    .B(_061_),
    .C(_060_),
    .Y(_001_)
  );
  OAI21X1 _148_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[2]),
    .Y(_062_)
  );
  NAND3X1 _149_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[2]),
    .Y(_063_)
  );
  OAI21X1 _150_ (
    .A(_057_),
    .B(_063_),
    .C(_062_),
    .Y(_002_)
  );
  OAI21X1 _151_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[3]),
    .Y(_064_)
  );
  NAND3X1 _152_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[3]),
    .Y(_065_)
  );
  OAI21X1 _153_ (
    .A(_057_),
    .B(_065_),
    .C(_064_),
    .Y(_003_)
  );
  OAI21X1 _154_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[4]),
    .Y(_066_)
  );
  NAND3X1 _155_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[4]),
    .Y(_067_)
  );
  OAI21X1 _156_ (
    .A(_057_),
    .B(_067_),
    .C(_066_),
    .Y(_004_)
  );
  OAI21X1 _157_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[5]),
    .Y(_068_)
  );
  NAND3X1 _158_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[5]),
    .Y(_069_)
  );
  OAI21X1 _159_ (
    .A(_057_),
    .B(_069_),
    .C(_068_),
    .Y(_005_)
  );
  OAI21X1 _160_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[6]),
    .Y(_070_)
  );
  NAND3X1 _161_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[6]),
    .Y(_071_)
  );
  OAI21X1 _162_ (
    .A(_057_),
    .B(_071_),
    .C(_070_),
    .Y(_006_)
  );
  OAI21X1 _163_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[7]),
    .Y(_072_)
  );
  NAND3X1 _164_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[7]),
    .Y(_073_)
  );
  OAI21X1 _165_ (
    .A(_057_),
    .B(_073_),
    .C(_072_),
    .Y(_007_)
  );
  OAI21X1 _166_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[8]),
    .Y(_074_)
  );
  NAND3X1 _167_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[8]),
    .Y(_075_)
  );
  OAI21X1 _168_ (
    .A(_057_),
    .B(_075_),
    .C(_074_),
    .Y(_008_)
  );
  OAI21X1 _169_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[9]),
    .Y(_076_)
  );
  NAND3X1 _170_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[9]),
    .Y(_077_)
  );
  OAI21X1 _171_ (
    .A(_057_),
    .B(_077_),
    .C(_076_),
    .Y(_009_)
  );
  OAI21X1 _172_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[10]),
    .Y(_078_)
  );
  NAND3X1 _173_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[10]),
    .Y(_079_)
  );
  OAI21X1 _174_ (
    .A(_057_),
    .B(_079_),
    .C(_078_),
    .Y(_010_)
  );
  OAI21X1 _175_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[11]),
    .Y(_080_)
  );
  NAND3X1 _176_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[11]),
    .Y(_081_)
  );
  OAI21X1 _177_ (
    .A(_057_),
    .B(_081_),
    .C(_080_),
    .Y(_011_)
  );
  OAI21X1 _178_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[12]),
    .Y(_082_)
  );
  NAND3X1 _179_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[12]),
    .Y(_083_)
  );
  OAI21X1 _180_ (
    .A(_057_),
    .B(_083_),
    .C(_082_),
    .Y(_012_)
  );
  OAI21X1 _181_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[13]),
    .Y(_084_)
  );
  NAND3X1 _182_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[13]),
    .Y(_085_)
  );
  OAI21X1 _183_ (
    .A(_057_),
    .B(_085_),
    .C(_084_),
    .Y(_013_)
  );
  OAI21X1 _184_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[14]),
    .Y(_086_)
  );
  NAND3X1 _185_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[14]),
    .Y(_087_)
  );
  OAI21X1 _186_ (
    .A(_057_),
    .B(_087_),
    .C(_086_),
    .Y(_014_)
  );
  OAI21X1 _187_ (
    .A(pwrite),
    .B(_056_),
    .C(prdata[15]),
    .Y(_088_)
  );
  NAND3X1 _188_ (
    .A(paddr[2]),
    .B(_094_),
    .C(clk_div[15]),
    .Y(_089_)
  );
  OAI21X1 _189_ (
    .A(_057_),
    .B(_089_),
    .C(_088_),
    .Y(_015_)
  );
  NAND3X1 _190_ (
    .A(penable),
    .B(psel),
    .C(pwrite),
    .Y(_090_)
  );
  NOR3X1 _191_ (
    .A(_093_),
    .B(paddr[3]),
    .C(_090_),
    .Y(_091_)
  );
  MUX2X1 _192_ (
    .A(_039_),
    .B(_095_),
    .S(_091_),
    .Y(_016_)
  );
  MUX2X1 _193_ (
    .A(_040_),
    .B(_096_),
    .S(_091_),
    .Y(_017_)
  );
  MUX2X1 _194_ (
    .A(_041_),
    .B(_097_),
    .S(_091_),
    .Y(_018_)
  );
  MUX2X1 _195_ (
    .A(_042_),
    .B(_098_),
    .S(_091_),
    .Y(_019_)
  );
  MUX2X1 _196_ (
    .A(_043_),
    .B(_099_),
    .S(_091_),
    .Y(_020_)
  );
  MUX2X1 _197_ (
    .A(_044_),
    .B(_100_),
    .S(_091_),
    .Y(_021_)
  );
  MUX2X1 _198_ (
    .A(_045_),
    .B(_101_),
    .S(_091_),
    .Y(_022_)
  );
  MUX2X1 _199_ (
    .A(_046_),
    .B(_102_),
    .S(_091_),
    .Y(_023_)
  );
  MUX2X1 _200_ (
    .A(_047_),
    .B(_103_),
    .S(_091_),
    .Y(_024_)
  );
  MUX2X1 _201_ (
    .A(_048_),
    .B(_104_),
    .S(_091_),
    .Y(_025_)
  );
  MUX2X1 _202_ (
    .A(_049_),
    .B(_033_),
    .S(_091_),
    .Y(_026_)
  );
  MUX2X1 _203_ (
    .A(_050_),
    .B(_034_),
    .S(_091_),
    .Y(_027_)
  );
  MUX2X1 _204_ (
    .A(_051_),
    .B(_035_),
    .S(_091_),
    .Y(_028_)
  );
  MUX2X1 _205_ (
    .A(_052_),
    .B(_036_),
    .S(_091_),
    .Y(_029_)
  );
  MUX2X1 _206_ (
    .A(_053_),
    .B(_037_),
    .S(_091_),
    .Y(_030_)
  );
  MUX2X1 _207_ (
    .A(_054_),
    .B(_038_),
    .S(_091_),
    .Y(_031_)
  );
  NOR3X1 _208_ (
    .A(paddr[2]),
    .B(_094_),
    .C(_090_),
    .Y(_092_)
  );
  MUX2X1 _209_ (
    .A(_043_),
    .B(_055_),
    .S(_092_),
    .Y(_032_)
  );
  DFFSR _210_ (
    .CLK(clk),
    .D(_000_),
    .Q(prdata[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _211_ (
    .CLK(clk),
    .D(_001_),
    .Q(prdata[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _212_ (
    .CLK(clk),
    .D(_002_),
    .Q(prdata[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _213_ (
    .CLK(clk),
    .D(_003_),
    .Q(prdata[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _214_ (
    .CLK(clk),
    .D(_004_),
    .Q(prdata[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _215_ (
    .CLK(clk),
    .D(_005_),
    .Q(prdata[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _216_ (
    .CLK(clk),
    .D(_006_),
    .Q(prdata[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _217_ (
    .CLK(clk),
    .D(_007_),
    .Q(prdata[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _218_ (
    .CLK(clk),
    .D(_008_),
    .Q(prdata[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _219_ (
    .CLK(clk),
    .D(_009_),
    .Q(prdata[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _220_ (
    .CLK(clk),
    .D(_010_),
    .Q(prdata[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _221_ (
    .CLK(clk),
    .D(_011_),
    .Q(prdata[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _222_ (
    .CLK(clk),
    .D(_012_),
    .Q(prdata[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _223_ (
    .CLK(clk),
    .D(_013_),
    .Q(prdata[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _224_ (
    .CLK(clk),
    .D(_014_),
    .Q(prdata[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _225_ (
    .CLK(clk),
    .D(_015_),
    .Q(prdata[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _226_ (
    .CLK(clk),
    .D(cpol),
    .Q(sclk_r),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _227_ (
    .CLK(clk),
    .D(_016_),
    .Q(clk_div[0]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _228_ (
    .CLK(clk),
    .D(_017_),
    .Q(clk_div[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _229_ (
    .CLK(clk),
    .D(_018_),
    .Q(clk_div[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _230_ (
    .CLK(clk),
    .D(_019_),
    .Q(clk_div[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _231_ (
    .CLK(clk),
    .D(_020_),
    .Q(clk_div[4]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _232_ (
    .CLK(clk),
    .D(_021_),
    .Q(clk_div[5]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _233_ (
    .CLK(clk),
    .D(_022_),
    .Q(clk_div[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _234_ (
    .CLK(clk),
    .D(_023_),
    .Q(clk_div[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _235_ (
    .CLK(clk),
    .D(_024_),
    .Q(clk_div[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _236_ (
    .CLK(clk),
    .D(_025_),
    .Q(clk_div[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _237_ (
    .CLK(clk),
    .D(_026_),
    .Q(clk_div[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _238_ (
    .CLK(clk),
    .D(_027_),
    .Q(clk_div[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _239_ (
    .CLK(clk),
    .D(_028_),
    .Q(clk_div[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _240_ (
    .CLK(clk),
    .D(_029_),
    .Q(clk_div[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _241_ (
    .CLK(clk),
    .D(_030_),
    .Q(clk_div[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _242_ (
    .CLK(clk),
    .D(_031_),
    .Q(clk_div[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _243_ (
    .CLK(clk),
    .D(_032_),
    .Q(cpol),
    .R(rst_n),
    .S(1'h1)
  );
  assign bit_cnt = 3'h0;
  assign busy = 1'h0;
  assign clk_cnt = 16'h0000;
  assign irq = 1'h0;
  assign mosi_r = 1'h1;
  assign prdata[31:16] = 16'h0000;
  assign pready = 1'h1;
  assign rx_data = 8'hxx;
  assign shift_in = 8'h00;
  assign shift_out = 8'h00;
  assign spi_clk = sclk_r;
  assign spi_csn = 4'hf;
  assign spi_mosi = 1'h1;
  assign start = 1'h0;
endmodule
