#!/usr/bin/env python3
"""
patch_netlist_for_lec.py
========================
Prepares a synthesized Verilog netlist for Logic Equivalence Checking (LEC)
with Yosys.

PROBLEM:
  Yosys synthesis sometimes inlines / flattens parameterized submodule
  definitions (e.g. axi4_crossbar, axi4_to_ahb, reset_sync) directly
  into the top-level netlist file.  When these definitions are present,
  Yosys prefers the gate-level implementations over the behavioural
  blackbox library stubs – leading to thousands of unproven $equiv cells
  and an LEC failure.

SOLUTION:
  Strip all submodule definitions from the LEC copy of the netlist,
  keeping ONLY the top-level module (titan_x_top).
  Because no definition exists in the file, Yosys resolves the
  instantiations to the blackbox stubs loaded via  read_verilog -lib
  in lec.tcl – enabling a clean hierarchical equivalence check.

USAGE:
  python3 patch_netlist_for_lec.py \
      --input  ../04_Synthesis/Output_Files/titan_x_synth_netlist.v \
      --output titan_x_synth_netlist.v \
      --top    titan_x_top

  # Or with defaults (run from 09_LEC/):
  python3 patch_netlist_for_lec.py
"""

import argparse
import re
import sys
from pathlib import Path


def find_module_start(lines: list[str], module_name: str) -> int | None:
    """Return the 0-based line index where 'module <module_name>' begins."""
    pattern = re.compile(rf'^\s*module\s+{re.escape(module_name)}\s*[\(;]')
    for i, line in enumerate(lines):
        if pattern.match(line):
            return i
    return None


def patch_netlist(input_path: Path, output_path: Path, top_module: str) -> None:
    print(f"[INFO] Reading  : {input_path}")
    content = input_path.read_text(encoding='utf-8')
    lines = content.split('\n')
    print(f"[INFO] Total lines in input: {len(lines)}")

    # Locate the top module
    top_start = find_module_start(lines, top_module)
    if top_start is None:
        sys.exit(f"[ERROR] Module '{top_module}' not found in {input_path}")

    print(f"[INFO] '{top_module}' starts at line {top_start + 1}")

    # List submodule definitions that were stripped
    stripped = []
    for i, line in enumerate(lines[:top_start]):
        m = re.match(r'^\s*module\s+(\w+)', line)
        if m:
            stripped.append((i + 1, m.group(1)))

    if stripped:
        print(f"[INFO] Stripping {len(stripped)} submodule definition(s):")
        for lineno, name in stripped:
            print(f"       Line {lineno:>6}: {name}")
    else:
        print("[INFO] No submodule definitions found before top module – nothing to strip.")

    header = [
        "// =============================================================",
        "// LEC-ONLY netlist – generated by patch_netlist_for_lec.py",
        "// Contains only the top-level module for hierarchical LEC.",
        "// Submodule definitions are removed so Yosys resolves them",
        "// from the blackbox stubs loaded with 'read_verilog -lib'.",
        "// =============================================================",
        "",
    ]

    output_lines = header + lines[top_start:]
    output_path.write_text('\n'.join(output_lines), encoding='utf-8')
    print(f"[INFO] Written  : {output_path} ({len(output_lines)} lines)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--input',  default='../04_Synthesis/Output_Files/titan_x_synth_netlist.v',
                        help='Path to the original synthesized netlist')
    parser.add_argument('--output', default='titan_x_synth_netlist.v',
                        help='Path for the patched LEC netlist')
    parser.add_argument('--top',    default='titan_x_top',
                        help='Name of the top-level module to keep')
    args = parser.parse_args()

    patch_netlist(
        input_path  = Path(args.input),
        output_path = Path(args.output),
        top_module  = args.top,
    )
    print("[DONE] Patch complete. Run:  yosys -s lec.tcl")


if __name__ == '__main__':
    main()
