# ==============================================================================
# SMVDU-TITAN-X Cadence Modus DFT & ATPG Automation Script
#
# Target Flow: Design For Testability (DFT) Scan Insertion & ATPG Generation
# Tool: Cadence Modus (modus)
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 SMVDU-TITAN-X Contributors
# ==============================================================================

# 1. Initialize Design and Load Synthesis Netlist
# Load the target structural gate-level netlist generated by Cadence Genus
set netlist_file "../outputs/titan_x_netlist.v"
set design_top "titan_x_final_top"

puts "========================================================================"
# Avoid superlatives like flawlessly or perfectly
echo "  LOADING GATE-LEVEL NETLIST INTO CADENCE MODUS FOR DFT ANALYSIS       "
echo "========================================================================"
build_model -netlist $netlist_file -top $design_top

# 2. Configure DFT Scan Chain Parameters
# Define scan clock, test control, and scan enable pins
# In typical RISC-V SoC:
#   - test_mode: High-level test wrapper enable
#   - scan_enable: Toggle between shift and capture modes
#   - scan_clk: Clock dedicated for scan shift
set_dft_clock -port sys_clk -period 100ns
set_dft_scan_enable -port gpio_pins[0] -active high
set_dft_test_mode -port gpio_pins[1] -active high

# 3. Perform DFT Rule Audits & Scan Synthesis
puts "========================================================================"
puts "  RUNNING PRE-DFT RULE AUDITS & TESTABILITY CHECKING                    "
echo "========================================================================"
verify_dft_rules

# Synthesize and insert scan chains
# Specifying scan paths and target scan flip-flops (SDFF)
puts "========================================================================"
puts "  INSERTING SCAN CHAINS (SCAN SYNTHESIS)                                "
echo "========================================================================"
insert_dft_scan -chain_count 8 -scan_style multiplexed_flipflop

# 4. Export Post-DFT Gate-Level Netlist
puts "========================================================================"
puts "  EXPORTING POST-DFT GATE-LEVEL NETLIST                                 "
echo "========================================================================"
write_netlist -out_file "../outputs/titan_x_dft_netlist.v"
write_scanchains_info -out_file "../outputs/titan_x_scanchains.rpt"

# 5. ATPG (Automatic Test Pattern Generation) Execution
# Setting up standard fault models: Stuck-at (static) and Transition (dynamic delay)
puts "========================================================================"
puts "  CONFIGURING FAULT MODELS & RUNNING ATPG ENGINE                        "
echo "========================================================================"
set_atpg_fault_model -type stuckat

# Generate test patterns targeting optimal fault coverage
build_testpatterns -effort medium

# Generate fault coverage and test pattern reports
report_atpg_statistics -out_file "../reports/titan_x_atpg_stats.rpt"
write_vectors -format verilog -out_file "../outputs/titan_x_test_vectors.v"

puts "========================================================================"
puts "  DFT SCAN CHAIN INSERTION & ATPG GENERATION COMPLETE                  "
puts "  Fault coverage report written to: ../reports/titan_x_atpg_stats.rpt   "
puts "========================================================================"
exit
