// SPDX-License-Identifier: Apache-2.0
// SMVDU-TITAN-X SoC — DDR4 PHY Interface
// Generates real DDR CK/DQS/DQ signals (NOT sys_clk passthrough)
`timescale 1ns/1ps
module ddr_phy_if (
    input  wire        clk,        // System clock (2x DDR rate)
    input  wire        rst_n,
    // DFI-style command interface
    input  wire        dfi_ck_en,
    input  wire        dfi_cs_n,
    input  wire        dfi_ras_n,
    input  wire        dfi_cas_n,
    input  wire        dfi_we_n,
    input  wire [2:0]  dfi_bank,
    input  wire [15:0] dfi_addr,
    input  wire        dfi_wrdata_valid,
    input  wire [63:0] dfi_wrdata,
    input  wire [7:0]  dfi_wrdata_mask,
    // DFI read data back
    output reg  [63:0] dfi_rddata,
    output reg         dfi_rddata_valid,
    // Physical DDR pins
    output reg         ddr_ck_p,
    output reg         ddr_ck_n,
    output wire        ddr_cke,
    output wire        ddr_cs_n,
    output wire        ddr_ras_n,
    output wire        ddr_cas_n,
    output wire        ddr_we_n,
    output wire [2:0]  ddr_ba,
    output wire [15:0] ddr_addr,
    output wire [7:0]  ddr_dm,
    inout  wire [63:0] ddr_dq,
    inout  wire [7:0]  ddr_dqs_p,
    inout  wire [7:0]  ddr_dqs_n
);
    // DDR clock: generated by toggling at half system clock rate
    // ddr_ck_p toggles every cycle → DDR frequency = sys_clk / 2
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            ddr_ck_p <= 1'b0;
            ddr_ck_n <= 1'b1;
        end else if (dfi_ck_en) begin
            ddr_ck_p <= ~ddr_ck_p;
            ddr_ck_n <= ~ddr_ck_n;
        end else begin
            ddr_ck_p <= 1'b0;
            ddr_ck_n <= 1'b0;
        end
    end

    // Command pins: direct from DFI
    assign ddr_cke   = dfi_ck_en;
    assign ddr_cs_n  = dfi_cs_n;
    assign ddr_ras_n = dfi_ras_n;
    assign ddr_cas_n = dfi_cas_n;
    assign ddr_we_n  = dfi_we_n;
    assign ddr_ba    = dfi_bank;
    assign ddr_addr  = dfi_addr;
    assign ddr_dm    = dfi_wrdata_valid ? dfi_wrdata_mask : 8'h00;

    // DQ tristate: drive during writes, high-Z during reads
    assign ddr_dq = dfi_wrdata_valid ? dfi_wrdata : 64'bz;

    // DQS: strobe during writes (DDR strobe = complement of ck during write)
    wire dqs_drive = dfi_wrdata_valid;
    assign ddr_dqs_p = dqs_drive ? {8{ddr_ck_p}} : 8'bz;
    assign ddr_dqs_n = dqs_drive ? {8{ddr_ck_n}} : 8'bz;

    // Read capture: sample DQ on rising edge of DQS (modelled as posedge clk)
    reg dfi_rddata_valid_d;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            dfi_rddata       <= 64'h0;
            dfi_rddata_valid <= 1'b0;
            dfi_rddata_valid_d <= 1'b0;
        end else begin
            // Capture DQ when not in write mode
            dfi_rddata_valid_d <= !dfi_wrdata_valid && !dfi_cs_n && !dfi_cas_n;
            dfi_rddata_valid   <= dfi_rddata_valid_d;
            if (!dfi_wrdata_valid)
                dfi_rddata <= ddr_dq;  // Capture tri-state driven value from DRAM
        end
    end
endmodule
