import re

def insert_dft():
    # Load synthesized netlist
    with open("titan_x_soc/04_Synthesis/titan_x_synth_netlist.v", "r") as f:
        content = f.read()

    # =========================================================================
    # 1. ADD DFT PORTS TO TOP-LEVEL MODULE: titan_x_top
    # =========================================================================
    # Find top module declaration
    top_port_match = re.search(r"module titan_x_top\s*\((.*?)\);", content, re.DOTALL)
    if not top_port_match:
        print("Error: Could not find titan_x_top module declaration in netlist.")
        return

    original_top_ports = top_port_match.group(1)
    dft_top_ports = "\n    scan_in,\n    scan_enable,\n    scan_out,\n"
    new_top_ports = dft_top_ports + original_top_ports
    content = content.replace(original_top_ports, new_top_ports, 1)

    # Insert port direction declarations right after the titan_x_top module declaration
    top_directions = """
  // DFT Top-level Ports
  input scan_in;
  input scan_enable;
  output scan_out;
"""
    # Find the newly modified module declaration and append direction declarations right after it
    top_decl_match = re.search(r"module titan_x_top\s*\(.*?\);", content, re.DOTALL)
    if top_decl_match:
        decl = top_decl_match.group(0)
        content = content.replace(decl, decl + top_directions, 1)

    # =========================================================================
    # 2. CONNECT DFT PORTS IN INSTANTIATION OF u_axi2ahb INSIDE titan_x_top
    # =========================================================================
    inst_match = re.search(r"u_axi2ahb\s*\((.*?)\);", content, re.DOTALL)
    if not inst_match:
        print("Error: Could not find u_axi2ahb instantiation in top wrapper.")
        return
        
    original_inst_ports = inst_match.group(1)
    dft_inst_connections = "    .scan_in(scan_in),\n    .scan_enable(scan_enable),\n    .scan_out(scan_out),\n"
    new_inst_ports = dft_inst_connections + original_inst_ports
    content = content.replace(original_inst_ports, new_inst_ports, 1)

    # =========================================================================
    # 3. ADD DFT PORTS TO SUBMODULE DECLARATION: axi4_to_ahb
    # =========================================================================
    # Locate module declaration (uses a parameterized name generated by Yosys)
    sub_module_match = re.search(r"module \\\$paramod.*\\axi4_to_ahb\s*\((.*?)\);", content, re.DOTALL)
    if not sub_module_match:
        print("Error: Could not find axi4_to_ahb module declaration in netlist.")
        return

    original_sub_ports = sub_module_match.group(1)
    dft_sub_ports = "scan_in, scan_enable, scan_out, "
    new_sub_ports = dft_sub_ports + original_sub_ports
    content = content.replace(original_sub_ports, new_sub_ports, 1)

    # =========================================================================
    # 4. STITCH SCAN CHAIN INSIDE THE SUBMODULE
    # =========================================================================
    # Flip-flop mapping: (instance, original_D, scan_in_source, Q_output, mux_wire)
    scan_chain = [
        ("_552_", "_001_", "scan_in", "bstate[0]", "dft_mux_out_552"),
        ("_553_", "_002_", "bstate[0]", "bstate[1]", "dft_mux_out_553"),
        ("_554_", "_003_", "bstate[1]", "htrans[1]", "dft_mux_out_554"),
        ("_555_", "_004_", "htrans[1]", "s_arready", "dft_mux_out_555"),
        ("_556_", "_000_", "s_arready", "s_bvalid", "dft_mux_out_556"),
        ("_557_", "_005_", "s_bvalid", "s_awready", "dft_mux_out_557"),
        ("_558_", "_275_", "s_awready", "s_rvalid", "dft_mux_out_558"),
        ("_591_", "_038_", "s_rvalid", "s_wready", "dft_mux_out_591"),
    ]

    # Build local declarations to insert inside the submodule
    sub_declarations = """
  // DFT Submodule Ports
  input scan_in;
  input scan_enable;
  output scan_out;

  // DFT Scan Chain MUX output wires
"""
    for _, _, _, _, mux_wire in scan_chain:
        sub_declarations += f"  wire {mux_wire};\n"
    sub_declarations += "\n  // DFT Scan Out Link\n  assign scan_out = s_wready;\n\n"

    # Insert sub declarations at the start of the axi4_to_ahb module body
    # Right after the first wire declaration in axi4_to_ahb
    first_wire_in_sub = re.search(r"module \\\$paramod.*?\\axi4_to_ahb.*?\n(\s+wire _000_;)", content, re.DOTALL)
    if first_wire_in_sub:
        target = first_wire_in_sub.group(1)
        content = content.replace(target, sub_declarations + target, 1)

    # 5. Intercept each DFFSR D-input with a MUX2X1 and update DFFSR connections
    for inst, orig_d, si_source, q_out, mux_wire in scan_chain:
        # Regex to locate the specific DFFSR block inside the netlist
        dffsr_pattern = rf"DFFSR {inst} \((.*?)\);"
        dffsr_match = re.search(dffsr_pattern, content, re.DOTALL)
        
        if dffsr_match:
            dffsr_block = dffsr_match.group(0)
            
            # Replace the original D pin connection with our new MUX wire output
            new_dffsr_block = dffsr_block.replace(f".D({orig_d})", f".D({mux_wire})")
            
            # Instantiate the standard cell MUX2X1
            mux_instance = f"""  MUX2X1 u_dft_mux{inst} (
    .A({orig_d}),
    .B({si_source}),
    .S(scan_enable),
    .Y({mux_wire})
  );
"""
            # Insert the MUX2X1 right before the DFFSR instance
            content = content.replace(dffsr_block, mux_instance + "\n" + new_dffsr_block, 1)
        else:
            print(f"Warning: Could not find DFFSR {inst} in netlist.")

    # Write the completed DFT stitched netlist
    with open("titan_x_soc/03_DFT/titan_x_dft_netlist.v", "w") as f:
        f.write(content)

    print("Success: Mapped 8 real flip-flops to Scan Chain and routed scan ports successfully!")

if __name__ == "__main__":
    insert_dft()
