/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module l2_data_array(clk, rst_n, bank_sel, cs, we, wmask, addr, din, dout, dout_valid);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  input [5:0] addr;
  wire [5:0] addr;
  input bank_sel;
  wire bank_sel;
  input clk;
  wire clk;
  input cs;
  wire cs;
  wire csb0_bank0;
  wire csb0_bank1;
  input [31:0] din;
  wire [31:0] din;
  output [31:0] dout;
  wire [31:0] dout;
  output dout_valid;
  wire dout_valid;
  input rst_n;
  wire rst_n;
  wire [31:0] sram_dout_bank0;
  wire [31:0] sram_dout_bank1;
  input we;
  wire we;
  wire web0;
  input [3:0] wmask;
  wire [3:0] wmask;
  INVX1 _099_ (
    .A(we),
    .Y(web0)
  );
  INVX1 _100_ (
    .A(cs),
    .Y(_033_)
  );
  NAND2X1 _101_ (
    .A(web0),
    .B(cs),
    .Y(_034_)
  );
  INVX1 _102_ (
    .A(_034_),
    .Y(_000_)
  );
  OR2X1 _103_ (
    .A(_033_),
    .B(bank_sel),
    .Y(csb0_bank0)
  );
  NAND2X1 _104_ (
    .A(cs),
    .B(bank_sel),
    .Y(csb0_bank1)
  );
  MUX2X1 _105_ (
    .A(sram_dout_bank1[0]),
    .B(sram_dout_bank0[0]),
    .S(bank_sel),
    .Y(_035_)
  );
  OAI21X1 _106_ (
    .A(we),
    .B(_033_),
    .C(dout[0]),
    .Y(_036_)
  );
  OAI21X1 _107_ (
    .A(_034_),
    .B(_035_),
    .C(_036_),
    .Y(_001_)
  );
  MUX2X1 _108_ (
    .A(sram_dout_bank1[1]),
    .B(sram_dout_bank0[1]),
    .S(bank_sel),
    .Y(_037_)
  );
  OAI21X1 _109_ (
    .A(we),
    .B(_033_),
    .C(dout[1]),
    .Y(_038_)
  );
  OAI21X1 _110_ (
    .A(_034_),
    .B(_037_),
    .C(_038_),
    .Y(_002_)
  );
  MUX2X1 _111_ (
    .A(sram_dout_bank1[2]),
    .B(sram_dout_bank0[2]),
    .S(bank_sel),
    .Y(_039_)
  );
  OAI21X1 _112_ (
    .A(we),
    .B(_033_),
    .C(dout[2]),
    .Y(_040_)
  );
  OAI21X1 _113_ (
    .A(_034_),
    .B(_039_),
    .C(_040_),
    .Y(_003_)
  );
  MUX2X1 _114_ (
    .A(sram_dout_bank1[3]),
    .B(sram_dout_bank0[3]),
    .S(bank_sel),
    .Y(_041_)
  );
  OAI21X1 _115_ (
    .A(we),
    .B(_033_),
    .C(dout[3]),
    .Y(_042_)
  );
  OAI21X1 _116_ (
    .A(_034_),
    .B(_041_),
    .C(_042_),
    .Y(_004_)
  );
  MUX2X1 _117_ (
    .A(sram_dout_bank1[4]),
    .B(sram_dout_bank0[4]),
    .S(bank_sel),
    .Y(_043_)
  );
  OAI21X1 _118_ (
    .A(we),
    .B(_033_),
    .C(dout[4]),
    .Y(_044_)
  );
  OAI21X1 _119_ (
    .A(_034_),
    .B(_043_),
    .C(_044_),
    .Y(_005_)
  );
  MUX2X1 _120_ (
    .A(sram_dout_bank1[5]),
    .B(sram_dout_bank0[5]),
    .S(bank_sel),
    .Y(_045_)
  );
  OAI21X1 _121_ (
    .A(we),
    .B(_033_),
    .C(dout[5]),
    .Y(_046_)
  );
  OAI21X1 _122_ (
    .A(_034_),
    .B(_045_),
    .C(_046_),
    .Y(_006_)
  );
  MUX2X1 _123_ (
    .A(sram_dout_bank1[6]),
    .B(sram_dout_bank0[6]),
    .S(bank_sel),
    .Y(_047_)
  );
  OAI21X1 _124_ (
    .A(we),
    .B(_033_),
    .C(dout[6]),
    .Y(_048_)
  );
  OAI21X1 _125_ (
    .A(_034_),
    .B(_047_),
    .C(_048_),
    .Y(_007_)
  );
  MUX2X1 _126_ (
    .A(sram_dout_bank1[7]),
    .B(sram_dout_bank0[7]),
    .S(bank_sel),
    .Y(_049_)
  );
  OAI21X1 _127_ (
    .A(we),
    .B(_033_),
    .C(dout[7]),
    .Y(_050_)
  );
  OAI21X1 _128_ (
    .A(_034_),
    .B(_049_),
    .C(_050_),
    .Y(_008_)
  );
  MUX2X1 _129_ (
    .A(sram_dout_bank1[8]),
    .B(sram_dout_bank0[8]),
    .S(bank_sel),
    .Y(_051_)
  );
  OAI21X1 _130_ (
    .A(we),
    .B(_033_),
    .C(dout[8]),
    .Y(_052_)
  );
  OAI21X1 _131_ (
    .A(_034_),
    .B(_051_),
    .C(_052_),
    .Y(_009_)
  );
  MUX2X1 _132_ (
    .A(sram_dout_bank1[9]),
    .B(sram_dout_bank0[9]),
    .S(bank_sel),
    .Y(_053_)
  );
  OAI21X1 _133_ (
    .A(we),
    .B(_033_),
    .C(dout[9]),
    .Y(_054_)
  );
  OAI21X1 _134_ (
    .A(_034_),
    .B(_053_),
    .C(_054_),
    .Y(_010_)
  );
  MUX2X1 _135_ (
    .A(sram_dout_bank1[10]),
    .B(sram_dout_bank0[10]),
    .S(bank_sel),
    .Y(_055_)
  );
  OAI21X1 _136_ (
    .A(we),
    .B(_033_),
    .C(dout[10]),
    .Y(_056_)
  );
  OAI21X1 _137_ (
    .A(_034_),
    .B(_055_),
    .C(_056_),
    .Y(_011_)
  );
  MUX2X1 _138_ (
    .A(sram_dout_bank1[11]),
    .B(sram_dout_bank0[11]),
    .S(bank_sel),
    .Y(_057_)
  );
  OAI21X1 _139_ (
    .A(we),
    .B(_033_),
    .C(dout[11]),
    .Y(_058_)
  );
  OAI21X1 _140_ (
    .A(_034_),
    .B(_057_),
    .C(_058_),
    .Y(_012_)
  );
  MUX2X1 _141_ (
    .A(sram_dout_bank1[12]),
    .B(sram_dout_bank0[12]),
    .S(bank_sel),
    .Y(_059_)
  );
  OAI21X1 _142_ (
    .A(we),
    .B(_033_),
    .C(dout[12]),
    .Y(_060_)
  );
  OAI21X1 _143_ (
    .A(_034_),
    .B(_059_),
    .C(_060_),
    .Y(_013_)
  );
  MUX2X1 _144_ (
    .A(sram_dout_bank1[13]),
    .B(sram_dout_bank0[13]),
    .S(bank_sel),
    .Y(_061_)
  );
  OAI21X1 _145_ (
    .A(we),
    .B(_033_),
    .C(dout[13]),
    .Y(_062_)
  );
  OAI21X1 _146_ (
    .A(_034_),
    .B(_061_),
    .C(_062_),
    .Y(_014_)
  );
  MUX2X1 _147_ (
    .A(sram_dout_bank1[14]),
    .B(sram_dout_bank0[14]),
    .S(bank_sel),
    .Y(_063_)
  );
  OAI21X1 _148_ (
    .A(we),
    .B(_033_),
    .C(dout[14]),
    .Y(_064_)
  );
  OAI21X1 _149_ (
    .A(_034_),
    .B(_063_),
    .C(_064_),
    .Y(_015_)
  );
  MUX2X1 _150_ (
    .A(sram_dout_bank1[15]),
    .B(sram_dout_bank0[15]),
    .S(bank_sel),
    .Y(_065_)
  );
  OAI21X1 _151_ (
    .A(we),
    .B(_033_),
    .C(dout[15]),
    .Y(_066_)
  );
  OAI21X1 _152_ (
    .A(_034_),
    .B(_065_),
    .C(_066_),
    .Y(_016_)
  );
  MUX2X1 _153_ (
    .A(sram_dout_bank1[16]),
    .B(sram_dout_bank0[16]),
    .S(bank_sel),
    .Y(_067_)
  );
  OAI21X1 _154_ (
    .A(we),
    .B(_033_),
    .C(dout[16]),
    .Y(_068_)
  );
  OAI21X1 _155_ (
    .A(_034_),
    .B(_067_),
    .C(_068_),
    .Y(_017_)
  );
  MUX2X1 _156_ (
    .A(sram_dout_bank1[17]),
    .B(sram_dout_bank0[17]),
    .S(bank_sel),
    .Y(_069_)
  );
  OAI21X1 _157_ (
    .A(we),
    .B(_033_),
    .C(dout[17]),
    .Y(_070_)
  );
  OAI21X1 _158_ (
    .A(_034_),
    .B(_069_),
    .C(_070_),
    .Y(_018_)
  );
  MUX2X1 _159_ (
    .A(sram_dout_bank1[18]),
    .B(sram_dout_bank0[18]),
    .S(bank_sel),
    .Y(_071_)
  );
  OAI21X1 _160_ (
    .A(we),
    .B(_033_),
    .C(dout[18]),
    .Y(_072_)
  );
  OAI21X1 _161_ (
    .A(_034_),
    .B(_071_),
    .C(_072_),
    .Y(_019_)
  );
  MUX2X1 _162_ (
    .A(sram_dout_bank1[19]),
    .B(sram_dout_bank0[19]),
    .S(bank_sel),
    .Y(_073_)
  );
  OAI21X1 _163_ (
    .A(we),
    .B(_033_),
    .C(dout[19]),
    .Y(_074_)
  );
  OAI21X1 _164_ (
    .A(_034_),
    .B(_073_),
    .C(_074_),
    .Y(_020_)
  );
  MUX2X1 _165_ (
    .A(sram_dout_bank1[20]),
    .B(sram_dout_bank0[20]),
    .S(bank_sel),
    .Y(_075_)
  );
  OAI21X1 _166_ (
    .A(we),
    .B(_033_),
    .C(dout[20]),
    .Y(_076_)
  );
  OAI21X1 _167_ (
    .A(_034_),
    .B(_075_),
    .C(_076_),
    .Y(_021_)
  );
  MUX2X1 _168_ (
    .A(sram_dout_bank1[21]),
    .B(sram_dout_bank0[21]),
    .S(bank_sel),
    .Y(_077_)
  );
  OAI21X1 _169_ (
    .A(we),
    .B(_033_),
    .C(dout[21]),
    .Y(_078_)
  );
  OAI21X1 _170_ (
    .A(_034_),
    .B(_077_),
    .C(_078_),
    .Y(_022_)
  );
  MUX2X1 _171_ (
    .A(sram_dout_bank1[22]),
    .B(sram_dout_bank0[22]),
    .S(bank_sel),
    .Y(_079_)
  );
  OAI21X1 _172_ (
    .A(we),
    .B(_033_),
    .C(dout[22]),
    .Y(_080_)
  );
  OAI21X1 _173_ (
    .A(_034_),
    .B(_079_),
    .C(_080_),
    .Y(_023_)
  );
  MUX2X1 _174_ (
    .A(sram_dout_bank1[23]),
    .B(sram_dout_bank0[23]),
    .S(bank_sel),
    .Y(_081_)
  );
  OAI21X1 _175_ (
    .A(we),
    .B(_033_),
    .C(dout[23]),
    .Y(_082_)
  );
  OAI21X1 _176_ (
    .A(_034_),
    .B(_081_),
    .C(_082_),
    .Y(_024_)
  );
  MUX2X1 _177_ (
    .A(sram_dout_bank1[24]),
    .B(sram_dout_bank0[24]),
    .S(bank_sel),
    .Y(_083_)
  );
  OAI21X1 _178_ (
    .A(we),
    .B(_033_),
    .C(dout[24]),
    .Y(_084_)
  );
  OAI21X1 _179_ (
    .A(_034_),
    .B(_083_),
    .C(_084_),
    .Y(_025_)
  );
  MUX2X1 _180_ (
    .A(sram_dout_bank1[25]),
    .B(sram_dout_bank0[25]),
    .S(bank_sel),
    .Y(_085_)
  );
  OAI21X1 _181_ (
    .A(we),
    .B(_033_),
    .C(dout[25]),
    .Y(_086_)
  );
  OAI21X1 _182_ (
    .A(_034_),
    .B(_085_),
    .C(_086_),
    .Y(_026_)
  );
  MUX2X1 _183_ (
    .A(sram_dout_bank1[26]),
    .B(sram_dout_bank0[26]),
    .S(bank_sel),
    .Y(_087_)
  );
  OAI21X1 _184_ (
    .A(we),
    .B(_033_),
    .C(dout[26]),
    .Y(_088_)
  );
  OAI21X1 _185_ (
    .A(_034_),
    .B(_087_),
    .C(_088_),
    .Y(_027_)
  );
  MUX2X1 _186_ (
    .A(sram_dout_bank1[27]),
    .B(sram_dout_bank0[27]),
    .S(bank_sel),
    .Y(_089_)
  );
  OAI21X1 _187_ (
    .A(we),
    .B(_033_),
    .C(dout[27]),
    .Y(_090_)
  );
  OAI21X1 _188_ (
    .A(_034_),
    .B(_089_),
    .C(_090_),
    .Y(_028_)
  );
  MUX2X1 _189_ (
    .A(sram_dout_bank1[28]),
    .B(sram_dout_bank0[28]),
    .S(bank_sel),
    .Y(_091_)
  );
  OAI21X1 _190_ (
    .A(we),
    .B(_033_),
    .C(dout[28]),
    .Y(_092_)
  );
  OAI21X1 _191_ (
    .A(_034_),
    .B(_091_),
    .C(_092_),
    .Y(_029_)
  );
  MUX2X1 _192_ (
    .A(sram_dout_bank1[29]),
    .B(sram_dout_bank0[29]),
    .S(bank_sel),
    .Y(_093_)
  );
  OAI21X1 _193_ (
    .A(we),
    .B(_033_),
    .C(dout[29]),
    .Y(_094_)
  );
  OAI21X1 _194_ (
    .A(_034_),
    .B(_093_),
    .C(_094_),
    .Y(_030_)
  );
  MUX2X1 _195_ (
    .A(sram_dout_bank1[30]),
    .B(sram_dout_bank0[30]),
    .S(bank_sel),
    .Y(_095_)
  );
  OAI21X1 _196_ (
    .A(we),
    .B(_033_),
    .C(dout[30]),
    .Y(_096_)
  );
  OAI21X1 _197_ (
    .A(_034_),
    .B(_095_),
    .C(_096_),
    .Y(_031_)
  );
  MUX2X1 _198_ (
    .A(sram_dout_bank1[31]),
    .B(sram_dout_bank0[31]),
    .S(bank_sel),
    .Y(_097_)
  );
  OAI21X1 _199_ (
    .A(we),
    .B(_033_),
    .C(dout[31]),
    .Y(_098_)
  );
  OAI21X1 _200_ (
    .A(_034_),
    .B(_097_),
    .C(_098_),
    .Y(_032_)
  );
  DFFSR _201_ (
    .CLK(clk),
    .D(_001_),
    .Q(dout[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _202_ (
    .CLK(clk),
    .D(_002_),
    .Q(dout[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _203_ (
    .CLK(clk),
    .D(_003_),
    .Q(dout[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _204_ (
    .CLK(clk),
    .D(_004_),
    .Q(dout[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _205_ (
    .CLK(clk),
    .D(_005_),
    .Q(dout[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _206_ (
    .CLK(clk),
    .D(_006_),
    .Q(dout[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _207_ (
    .CLK(clk),
    .D(_007_),
    .Q(dout[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _208_ (
    .CLK(clk),
    .D(_008_),
    .Q(dout[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _209_ (
    .CLK(clk),
    .D(_009_),
    .Q(dout[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _210_ (
    .CLK(clk),
    .D(_010_),
    .Q(dout[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _211_ (
    .CLK(clk),
    .D(_011_),
    .Q(dout[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _212_ (
    .CLK(clk),
    .D(_012_),
    .Q(dout[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _213_ (
    .CLK(clk),
    .D(_013_),
    .Q(dout[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _214_ (
    .CLK(clk),
    .D(_014_),
    .Q(dout[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _215_ (
    .CLK(clk),
    .D(_015_),
    .Q(dout[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _216_ (
    .CLK(clk),
    .D(_016_),
    .Q(dout[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _217_ (
    .CLK(clk),
    .D(_017_),
    .Q(dout[16]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _218_ (
    .CLK(clk),
    .D(_018_),
    .Q(dout[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _219_ (
    .CLK(clk),
    .D(_019_),
    .Q(dout[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _220_ (
    .CLK(clk),
    .D(_020_),
    .Q(dout[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _221_ (
    .CLK(clk),
    .D(_021_),
    .Q(dout[20]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _222_ (
    .CLK(clk),
    .D(_022_),
    .Q(dout[21]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _223_ (
    .CLK(clk),
    .D(_023_),
    .Q(dout[22]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _224_ (
    .CLK(clk),
    .D(_024_),
    .Q(dout[23]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _225_ (
    .CLK(clk),
    .D(_025_),
    .Q(dout[24]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _226_ (
    .CLK(clk),
    .D(_026_),
    .Q(dout[25]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _227_ (
    .CLK(clk),
    .D(_027_),
    .Q(dout[26]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _228_ (
    .CLK(clk),
    .D(_028_),
    .Q(dout[27]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _229_ (
    .CLK(clk),
    .D(_029_),
    .Q(dout[28]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _230_ (
    .CLK(clk),
    .D(_030_),
    .Q(dout[29]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _231_ (
    .CLK(clk),
    .D(_031_),
    .Q(dout[30]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _232_ (
    .CLK(clk),
    .D(_032_),
    .Q(dout[31]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _233_ (
    .CLK(clk),
    .D(_000_),
    .Q(dout_valid),
    .R(rst_n),
    .S(1'h1)
  );
  sram_32x64_180nm u_sram_bank0 (
    .addr0(addr),
    .clk0(clk),
    .csb0(csb0_bank0),
    .din0(din),
    .dout0(sram_dout_bank0),
    .web0(web0),
    .wmask0(wmask)
  );
  sram_32x64_180nm u_sram_bank1 (
    .addr0(addr),
    .clk0(clk),
    .csb0(csb0_bank1),
    .din0(din),
    .dout0(sram_dout_bank1),
    .web0(web0),
    .wmask0(wmask)
  );
endmodule
