/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module pcie_top(clk, rst_n, s_arvalid, s_arready, s_araddr, s_rvalid, s_rready, s_rdata, s_rresp, s_awvalid, s_awready, s_awaddr, s_wvalid, s_wready, s_wdata, s_wstrb, s_bvalid, s_bready, s_bresp, m_awvalid, m_awready
, m_awaddr, m_wvalid, m_wready, m_wdata, m_wstrb, m_bvalid, m_bready, m_arvalid, m_arready, m_araddr, m_rvalid, m_rready, m_rdata, m_rresp, pcie_txp, pcie_txn, pcie_rxp, pcie_rxn, pcie_refclk_p, pcie_refclk_n, pcie_perst_n
, irq);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire ar_ack;
  wire aw_ack;
  wire bvalid_r;
  input clk;
  wire clk;
  output irq;
  wire irq;
  wire [2:0] link_state;
  wire link_up;
  wire [19:0] lt_timer;
  output [39:0] m_araddr;
  wire [39:0] m_araddr;
  input m_arready;
  wire m_arready;
  output m_arvalid;
  wire m_arvalid;
  output [39:0] m_awaddr;
  wire [39:0] m_awaddr;
  input m_awready;
  wire m_awready;
  output m_awvalid;
  wire m_awvalid;
  output m_bready;
  wire m_bready;
  input m_bvalid;
  wire m_bvalid;
  input [63:0] m_rdata;
  wire [63:0] m_rdata;
  output m_rready;
  wire m_rready;
  input [1:0] m_rresp;
  wire [1:0] m_rresp;
  input m_rvalid;
  wire m_rvalid;
  output [63:0] m_wdata;
  wire [63:0] m_wdata;
  input m_wready;
  wire m_wready;
  output [7:0] m_wstrb;
  wire [7:0] m_wstrb;
  output m_wvalid;
  wire m_wvalid;
  output pcie_perst_n;
  wire pcie_perst_n;
  input pcie_refclk_n;
  wire pcie_refclk_n;
  input pcie_refclk_p;
  wire pcie_refclk_p;
  input [3:0] pcie_rxn;
  wire [3:0] pcie_rxn;
  input [3:0] pcie_rxp;
  wire [3:0] pcie_rxp;
  wire [1:0] pcie_status;
  output [3:0] pcie_txn;
  wire [3:0] pcie_txn;
  output [3:0] pcie_txp;
  wire [3:0] pcie_txp;
  wire [63:0] rdata_r;
  input rst_n;
  wire rst_n;
  wire rvalid_r;
  input [39:0] s_araddr;
  wire [39:0] s_araddr;
  output s_arready;
  wire s_arready;
  input s_arvalid;
  wire s_arvalid;
  input [39:0] s_awaddr;
  wire [39:0] s_awaddr;
  output s_awready;
  wire s_awready;
  input s_awvalid;
  wire s_awvalid;
  input s_bready;
  wire s_bready;
  output [1:0] s_bresp;
  wire [1:0] s_bresp;
  output s_bvalid;
  wire s_bvalid;
  output [63:0] s_rdata;
  wire [63:0] s_rdata;
  input s_rready;
  wire s_rready;
  output [1:0] s_rresp;
  wire [1:0] s_rresp;
  output s_rvalid;
  wire s_rvalid;
  input [63:0] s_wdata;
  wire [63:0] s_wdata;
  output s_wready;
  wire s_wready;
  input [7:0] s_wstrb;
  wire [7:0] s_wstrb;
  input s_wvalid;
  wire s_wvalid;
  wire wack;
  INVX1 _093_ (
    .A(pcie_status[1]),
    .Y(_059_)
  );
  INVX1 _094_ (
    .A(link_state[1]),
    .Y(_060_)
  );
  INVX1 _095_ (
    .A(link_state[0]),
    .Y(_061_)
  );
  INVX1 _096_ (
    .A(lt_timer[3]),
    .Y(_062_)
  );
  INVX1 _097_ (
    .A(lt_timer[9]),
    .Y(_063_)
  );
  INVX1 _098_ (
    .A(lt_timer[8]),
    .Y(_064_)
  );
  INVX1 _099_ (
    .A(lt_timer[16]),
    .Y(_065_)
  );
  INVX1 _100_ (
    .A(lt_timer[18]),
    .Y(_066_)
  );
  INVX1 _101_ (
    .A(lt_timer[19]),
    .Y(_067_)
  );
  INVX1 _102_ (
    .A(rdata_r[0]),
    .Y(_068_)
  );
  AND2X1 _103_ (
    .A(s_wvalid),
    .B(aw_ack),
    .Y(_000_)
  );
  NOR2X1 _104_ (
    .A(_060_),
    .B(_061_),
    .Y(_069_)
  );
  NAND2X1 _105_ (
    .A(link_state[1]),
    .B(link_state[0]),
    .Y(_070_)
  );
  AND2X1 _106_ (
    .A(lt_timer[13]),
    .B(lt_timer[12]),
    .Y(_071_)
  );
  NAND3X1 _107_ (
    .A(lt_timer[15]),
    .B(lt_timer[14]),
    .C(_071_),
    .Y(_072_)
  );
  AND2X1 _108_ (
    .A(lt_timer[1]),
    .B(lt_timer[0]),
    .Y(_073_)
  );
  NAND3X1 _109_ (
    .A(lt_timer[1]),
    .B(lt_timer[0]),
    .C(lt_timer[2]),
    .Y(_074_)
  );
  NOR2X1 _110_ (
    .A(_062_),
    .B(_074_),
    .Y(_075_)
  );
  NAND2X1 _111_ (
    .A(lt_timer[5]),
    .B(lt_timer[4]),
    .Y(_076_)
  );
  NOR3X1 _112_ (
    .A(_062_),
    .B(_074_),
    .C(_076_),
    .Y(_077_)
  );
  AND2X1 _113_ (
    .A(lt_timer[6]),
    .B(_077_),
    .Y(_078_)
  );
  NAND3X1 _114_ (
    .A(lt_timer[7]),
    .B(lt_timer[6]),
    .C(_077_),
    .Y(_079_)
  );
  NAND2X1 _115_ (
    .A(lt_timer[9]),
    .B(lt_timer[8]),
    .Y(_080_)
  );
  NOR2X1 _116_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  NAND3X1 _117_ (
    .A(lt_timer[11]),
    .B(lt_timer[10]),
    .C(_081_),
    .Y(_082_)
  );
  OR2X1 _118_ (
    .A(_072_),
    .B(_082_),
    .Y(_083_)
  );
  NOR3X1 _119_ (
    .A(_063_),
    .B(_064_),
    .C(_079_),
    .Y(_084_)
  );
  NAND2X1 _120_ (
    .A(lt_timer[10]),
    .B(_084_),
    .Y(_085_)
  );
  NAND3X1 _121_ (
    .A(lt_timer[11]),
    .B(lt_timer[10]),
    .C(_084_),
    .Y(_086_)
  );
  NOR3X1 _122_ (
    .A(_065_),
    .B(_072_),
    .C(_086_),
    .Y(_087_)
  );
  NAND3X1 _123_ (
    .A(lt_timer[17]),
    .B(_070_),
    .C(_087_),
    .Y(_088_)
  );
  NOR2X1 _124_ (
    .A(_066_),
    .B(_088_),
    .Y(_089_)
  );
  NOR3X1 _125_ (
    .A(_066_),
    .B(_067_),
    .C(_088_),
    .Y(_090_)
  );
  XNOR2X1 _126_ (
    .A(_061_),
    .B(_090_),
    .Y(_001_)
  );
  NOR2X1 _127_ (
    .A(_066_),
    .B(_067_),
    .Y(_091_)
  );
  NAND3X1 _128_ (
    .A(lt_timer[17]),
    .B(_087_),
    .C(_091_),
    .Y(_092_)
  );
  OAI21X1 _129_ (
    .A(_061_),
    .B(_092_),
    .C(_060_),
    .Y(_002_)
  );
  XOR2X1 _130_ (
    .A(lt_timer[0]),
    .B(_070_),
    .Y(_003_)
  );
  AOI21X1 _131_ (
    .A(lt_timer[0]),
    .B(_070_),
    .C(lt_timer[1]),
    .Y(_026_)
  );
  AOI21X1 _132_ (
    .A(_070_),
    .B(_073_),
    .C(_026_),
    .Y(_004_)
  );
  NOR2X1 _133_ (
    .A(_069_),
    .B(_074_),
    .Y(_027_)
  );
  AOI21X1 _134_ (
    .A(_070_),
    .B(_073_),
    .C(lt_timer[2]),
    .Y(_028_)
  );
  NOR2X1 _135_ (
    .A(_027_),
    .B(_028_),
    .Y(_005_)
  );
  OAI21X1 _136_ (
    .A(_060_),
    .B(_061_),
    .C(_075_),
    .Y(_029_)
  );
  INVX1 _137_ (
    .A(_029_),
    .Y(_030_)
  );
  OAI21X1 _138_ (
    .A(lt_timer[3]),
    .B(_027_),
    .C(_029_),
    .Y(_031_)
  );
  INVX1 _139_ (
    .A(_031_),
    .Y(_006_)
  );
  XNOR2X1 _140_ (
    .A(lt_timer[4]),
    .B(_029_),
    .Y(_007_)
  );
  AOI21X1 _141_ (
    .A(lt_timer[4]),
    .B(_030_),
    .C(lt_timer[5]),
    .Y(_032_)
  );
  AOI21X1 _142_ (
    .A(_070_),
    .B(_077_),
    .C(_032_),
    .Y(_008_)
  );
  AOI21X1 _143_ (
    .A(_070_),
    .B(_077_),
    .C(lt_timer[6]),
    .Y(_033_)
  );
  AOI21X1 _144_ (
    .A(_070_),
    .B(_078_),
    .C(_033_),
    .Y(_009_)
  );
  NOR2X1 _145_ (
    .A(_069_),
    .B(_079_),
    .Y(_034_)
  );
  AOI21X1 _146_ (
    .A(_070_),
    .B(_078_),
    .C(lt_timer[7]),
    .Y(_035_)
  );
  NOR2X1 _147_ (
    .A(_034_),
    .B(_035_),
    .Y(_010_)
  );
  XNOR2X1 _148_ (
    .A(_064_),
    .B(_034_),
    .Y(_011_)
  );
  AOI21X1 _149_ (
    .A(lt_timer[8]),
    .B(_034_),
    .C(lt_timer[9]),
    .Y(_036_)
  );
  AOI21X1 _150_ (
    .A(_070_),
    .B(_084_),
    .C(_036_),
    .Y(_012_)
  );
  AOI21X1 _151_ (
    .A(_070_),
    .B(_084_),
    .C(lt_timer[10]),
    .Y(_037_)
  );
  NOR2X1 _152_ (
    .A(_069_),
    .B(_085_),
    .Y(_038_)
  );
  NOR2X1 _153_ (
    .A(_037_),
    .B(_038_),
    .Y(_013_)
  );
  NOR2X1 _154_ (
    .A(lt_timer[11]),
    .B(_038_),
    .Y(_039_)
  );
  NOR2X1 _155_ (
    .A(_069_),
    .B(_086_),
    .Y(_040_)
  );
  NOR2X1 _156_ (
    .A(_039_),
    .B(_040_),
    .Y(_014_)
  );
  XOR2X1 _157_ (
    .A(lt_timer[12]),
    .B(_040_),
    .Y(_015_)
  );
  AND2X1 _158_ (
    .A(_071_),
    .B(_040_),
    .Y(_041_)
  );
  AOI21X1 _159_ (
    .A(lt_timer[12]),
    .B(_040_),
    .C(lt_timer[13]),
    .Y(_042_)
  );
  NOR2X1 _160_ (
    .A(_041_),
    .B(_042_),
    .Y(_016_)
  );
  XOR2X1 _161_ (
    .A(lt_timer[14]),
    .B(_041_),
    .Y(_017_)
  );
  AOI21X1 _162_ (
    .A(lt_timer[14]),
    .B(_041_),
    .C(lt_timer[15]),
    .Y(_043_)
  );
  NOR2X1 _163_ (
    .A(_069_),
    .B(_083_),
    .Y(_044_)
  );
  NOR2X1 _164_ (
    .A(_043_),
    .B(_044_),
    .Y(_018_)
  );
  NOR2X1 _165_ (
    .A(lt_timer[16]),
    .B(_044_),
    .Y(_045_)
  );
  AND2X1 _166_ (
    .A(_070_),
    .B(_087_),
    .Y(_046_)
  );
  NOR2X1 _167_ (
    .A(_045_),
    .B(_046_),
    .Y(_019_)
  );
  OAI21X1 _168_ (
    .A(lt_timer[17]),
    .B(_046_),
    .C(_088_),
    .Y(_047_)
  );
  INVX1 _169_ (
    .A(_047_),
    .Y(_020_)
  );
  XNOR2X1 _170_ (
    .A(lt_timer[18]),
    .B(_088_),
    .Y(_021_)
  );
  XNOR2X1 _171_ (
    .A(_067_),
    .B(_089_),
    .Y(_022_)
  );
  NOR2X1 _172_ (
    .A(s_araddr[9]),
    .B(s_araddr[11]),
    .Y(_048_)
  );
  NOR2X1 _173_ (
    .A(s_araddr[5]),
    .B(s_araddr[8]),
    .Y(_049_)
  );
  NOR2X1 _174_ (
    .A(s_araddr[7]),
    .B(s_araddr[10]),
    .Y(_050_)
  );
  NAND2X1 _175_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  NOR2X1 _176_ (
    .A(s_araddr[3]),
    .B(s_araddr[6]),
    .Y(_052_)
  );
  NOR2X1 _177_ (
    .A(_059_),
    .B(s_araddr[4]),
    .Y(_053_)
  );
  NAND2X1 _178_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  NOR2X1 _179_ (
    .A(_051_),
    .B(_054_),
    .Y(_055_)
  );
  NAND3X1 _180_ (
    .A(rst_n),
    .B(_048_),
    .C(_055_),
    .Y(_056_)
  );
  OAI21X1 _181_ (
    .A(_068_),
    .B(rst_n),
    .C(_056_),
    .Y(_023_)
  );
  NAND2X1 _182_ (
    .A(link_state[1]),
    .B(_061_),
    .Y(_057_)
  );
  OAI21X1 _183_ (
    .A(_092_),
    .B(_057_),
    .C(_059_),
    .Y(_024_)
  );
  NOR2X1 _184_ (
    .A(link_up),
    .B(_069_),
    .Y(_058_)
  );
  OAI21X1 _185_ (
    .A(_092_),
    .B(_057_),
    .C(_058_),
    .Y(_025_)
  );
  DFFSR _186_ (
    .CLK(clk),
    .D(_001_),
    .Q(link_state[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _187_ (
    .CLK(clk),
    .D(_002_),
    .Q(link_state[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _188_ (
    .CLK(clk),
    .D(_003_),
    .Q(lt_timer[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _189_ (
    .CLK(clk),
    .D(_004_),
    .Q(lt_timer[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _190_ (
    .CLK(clk),
    .D(_005_),
    .Q(lt_timer[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _191_ (
    .CLK(clk),
    .D(_006_),
    .Q(lt_timer[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _192_ (
    .CLK(clk),
    .D(_007_),
    .Q(lt_timer[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _193_ (
    .CLK(clk),
    .D(_008_),
    .Q(lt_timer[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _194_ (
    .CLK(clk),
    .D(_009_),
    .Q(lt_timer[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _195_ (
    .CLK(clk),
    .D(_010_),
    .Q(lt_timer[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _196_ (
    .CLK(clk),
    .D(_011_),
    .Q(lt_timer[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _197_ (
    .CLK(clk),
    .D(_012_),
    .Q(lt_timer[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _198_ (
    .CLK(clk),
    .D(_013_),
    .Q(lt_timer[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _199_ (
    .CLK(clk),
    .D(_014_),
    .Q(lt_timer[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _200_ (
    .CLK(clk),
    .D(_015_),
    .Q(lt_timer[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _201_ (
    .CLK(clk),
    .D(_016_),
    .Q(lt_timer[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _202_ (
    .CLK(clk),
    .D(_017_),
    .Q(lt_timer[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _203_ (
    .CLK(clk),
    .D(_018_),
    .Q(lt_timer[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _204_ (
    .CLK(clk),
    .D(_019_),
    .Q(lt_timer[16]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _205_ (
    .CLK(clk),
    .D(_020_),
    .Q(lt_timer[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _206_ (
    .CLK(clk),
    .D(_021_),
    .Q(lt_timer[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _207_ (
    .CLK(clk),
    .D(_022_),
    .Q(lt_timer[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFPOSX1 _208_ (
    .CLK(clk),
    .D(_023_),
    .Q(rdata_r[0])
  );
  DFFSR _209_ (
    .CLK(clk),
    .D(s_arvalid),
    .Q(ar_ack),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _210_ (
    .CLK(clk),
    .D(ar_ack),
    .Q(rvalid_r),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _211_ (
    .CLK(clk),
    .D(s_awvalid),
    .Q(aw_ack),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _212_ (
    .CLK(clk),
    .D(_000_),
    .Q(wack),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _213_ (
    .CLK(clk),
    .D(wack),
    .Q(bvalid_r),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _214_ (
    .CLK(clk),
    .D(_024_),
    .Q(pcie_status[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _215_ (
    .CLK(clk),
    .D(_025_),
    .Q(link_up),
    .R(rst_n),
    .S(1'h1)
  );
  assign irq = link_up;
  assign link_state[2] = 1'h0;
  assign m_araddr = 40'h0000000000;
  assign m_arvalid = 1'h0;
  assign m_awaddr = 40'h0000000000;
  assign m_awvalid = 1'h0;
  assign m_bready = 1'h1;
  assign m_rready = 1'h1;
  assign m_wdata = 64'h0000000000000000;
  assign m_wstrb = 8'h00;
  assign m_wvalid = 1'h0;
  assign pcie_perst_n = rst_n;
  assign pcie_status[0] = pcie_status[1];
  assign pcie_txn = 4'h0;
  assign pcie_txp = 4'hf;
  assign rdata_r[63:1] = { 62'h0000000000000000, rdata_r[0] };
  assign s_arready = 1'h1;
  assign s_awready = 1'h1;
  assign s_bresp = 2'h0;
  assign s_bvalid = bvalid_r;
  assign s_rdata = { 62'h0000000000000000, rdata_r[0], rdata_r[0] };
  assign s_rresp = 2'h0;
  assign s_rvalid = rvalid_r;
  assign s_wready = 1'h1;
endmodule
