/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module trng(clk, rst_n, psel, penable, pwrite, paddr, pwdata, prdata, pready, irq);
  wire [5:0] _000_;
  wire [31:0] _001_;
  wire [2:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire [5:0] bit_cnt;
  input clk;
  wire clk;
  output irq;
  wire irq;
  wire [31:0] lfsr;
  wire lfsr_feedback;
  input [3:0] paddr;
  wire [3:0] paddr;
  input penable;
  wire penable;
  output [31:0] prdata;
  wire [31:0] prdata;
  output pready;
  wire pready;
  input psel;
  wire psel;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  input pwrite;
  wire pwrite;
  wire [2:0] ring_osc;
  wire [31:0] rnd_out;
  input rst_n;
  wire rst_n;
  wire valid;
  INVX1 _112_ (
    .A(bit_cnt[0]),
    .Y(_000_[0])
  );
  INVX1 _113_ (
    .A(bit_cnt[3]),
    .Y(_036_)
  );
  INVX1 _114_ (
    .A(pwrite),
    .Y(_037_)
  );
  INVX1 _115_ (
    .A(paddr[2]),
    .Y(_038_)
  );
  NAND2X1 _116_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .Y(_039_)
  );
  NAND3X1 _117_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .C(bit_cnt[2]),
    .Y(_040_)
  );
  NOR2X1 _118_ (
    .A(_036_),
    .B(_040_),
    .Y(_041_)
  );
  NAND2X1 _119_ (
    .A(bit_cnt[4]),
    .B(_041_),
    .Y(_042_)
  );
  NOR2X1 _120_ (
    .A(bit_cnt[5]),
    .B(_042_),
    .Y(_003_)
  );
  XOR2X1 _121_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .Y(_000_[1])
  );
  XNOR2X1 _122_ (
    .A(bit_cnt[2]),
    .B(_039_),
    .Y(_000_[2])
  );
  XNOR2X1 _123_ (
    .A(bit_cnt[3]),
    .B(_040_),
    .Y(_000_[3])
  );
  XOR2X1 _124_ (
    .A(bit_cnt[4]),
    .B(_041_),
    .Y(_000_[4])
  );
  AND2X1 _125_ (
    .A(bit_cnt[5]),
    .B(_042_),
    .Y(_000_[5])
  );
  XOR2X1 _126_ (
    .A(ring_osc[2]),
    .B(ring_osc[0]),
    .Y(_002_[2])
  );
  XOR2X1 _127_ (
    .A(lfsr[21]),
    .B(lfsr[31]),
    .Y(_043_)
  );
  XNOR2X1 _128_ (
    .A(lfsr[1]),
    .B(_043_),
    .Y(_044_)
  );
  XNOR2X1 _129_ (
    .A(lfsr[0]),
    .B(_044_),
    .Y(lfsr_feedback)
  );
  XOR2X1 _130_ (
    .A(lfsr[0]),
    .B(ring_osc[1]),
    .Y(_001_[1])
  );
  XOR2X1 _131_ (
    .A(ring_osc[2]),
    .B(lfsr[1]),
    .Y(_001_[2])
  );
  XOR2X1 _132_ (
    .A(ring_osc[0]),
    .B(lfsr_feedback),
    .Y(_001_[0])
  );
  NAND3X1 _133_ (
    .A(penable),
    .B(psel),
    .C(_037_),
    .Y(_045_)
  );
  NOR2X1 _134_ (
    .A(paddr[3]),
    .B(_038_),
    .Y(_046_)
  );
  NOR2X1 _135_ (
    .A(paddr[3]),
    .B(paddr[2]),
    .Y(_047_)
  );
  AOI22X1 _136_ (
    .A(rnd_out[0]),
    .B(_046_),
    .C(_047_),
    .D(valid),
    .Y(_048_)
  );
  NAND2X1 _137_ (
    .A(prdata[0]),
    .B(_045_),
    .Y(_049_)
  );
  OAI21X1 _138_ (
    .A(_045_),
    .B(_048_),
    .C(_049_),
    .Y(_004_)
  );
  NAND2X1 _139_ (
    .A(prdata[1]),
    .B(_045_),
    .Y(_050_)
  );
  NAND2X1 _140_ (
    .A(rnd_out[1]),
    .B(_046_),
    .Y(_051_)
  );
  OAI21X1 _141_ (
    .A(_045_),
    .B(_051_),
    .C(_050_),
    .Y(_005_)
  );
  NAND2X1 _142_ (
    .A(prdata[2]),
    .B(_045_),
    .Y(_052_)
  );
  NAND2X1 _143_ (
    .A(rnd_out[2]),
    .B(_046_),
    .Y(_053_)
  );
  OAI21X1 _144_ (
    .A(_045_),
    .B(_053_),
    .C(_052_),
    .Y(_006_)
  );
  NAND2X1 _145_ (
    .A(prdata[3]),
    .B(_045_),
    .Y(_054_)
  );
  NAND2X1 _146_ (
    .A(rnd_out[3]),
    .B(_046_),
    .Y(_055_)
  );
  OAI21X1 _147_ (
    .A(_045_),
    .B(_055_),
    .C(_054_),
    .Y(_007_)
  );
  NAND2X1 _148_ (
    .A(prdata[4]),
    .B(_045_),
    .Y(_056_)
  );
  NAND2X1 _149_ (
    .A(rnd_out[4]),
    .B(_046_),
    .Y(_057_)
  );
  OAI21X1 _150_ (
    .A(_045_),
    .B(_057_),
    .C(_056_),
    .Y(_008_)
  );
  NAND2X1 _151_ (
    .A(prdata[5]),
    .B(_045_),
    .Y(_058_)
  );
  NAND2X1 _152_ (
    .A(rnd_out[5]),
    .B(_046_),
    .Y(_059_)
  );
  OAI21X1 _153_ (
    .A(_045_),
    .B(_059_),
    .C(_058_),
    .Y(_009_)
  );
  NAND2X1 _154_ (
    .A(prdata[6]),
    .B(_045_),
    .Y(_060_)
  );
  NAND2X1 _155_ (
    .A(rnd_out[6]),
    .B(_046_),
    .Y(_061_)
  );
  OAI21X1 _156_ (
    .A(_045_),
    .B(_061_),
    .C(_060_),
    .Y(_010_)
  );
  NAND2X1 _157_ (
    .A(prdata[7]),
    .B(_045_),
    .Y(_062_)
  );
  NAND2X1 _158_ (
    .A(rnd_out[7]),
    .B(_046_),
    .Y(_063_)
  );
  OAI21X1 _159_ (
    .A(_045_),
    .B(_063_),
    .C(_062_),
    .Y(_011_)
  );
  NAND2X1 _160_ (
    .A(prdata[8]),
    .B(_045_),
    .Y(_064_)
  );
  NAND2X1 _161_ (
    .A(rnd_out[8]),
    .B(_046_),
    .Y(_065_)
  );
  OAI21X1 _162_ (
    .A(_045_),
    .B(_065_),
    .C(_064_),
    .Y(_012_)
  );
  NAND2X1 _163_ (
    .A(prdata[9]),
    .B(_045_),
    .Y(_066_)
  );
  NAND2X1 _164_ (
    .A(rnd_out[9]),
    .B(_046_),
    .Y(_067_)
  );
  OAI21X1 _165_ (
    .A(_045_),
    .B(_067_),
    .C(_066_),
    .Y(_013_)
  );
  NAND2X1 _166_ (
    .A(prdata[10]),
    .B(_045_),
    .Y(_068_)
  );
  NAND2X1 _167_ (
    .A(rnd_out[10]),
    .B(_046_),
    .Y(_069_)
  );
  OAI21X1 _168_ (
    .A(_045_),
    .B(_069_),
    .C(_068_),
    .Y(_014_)
  );
  NAND2X1 _169_ (
    .A(prdata[11]),
    .B(_045_),
    .Y(_070_)
  );
  NAND2X1 _170_ (
    .A(rnd_out[11]),
    .B(_046_),
    .Y(_071_)
  );
  OAI21X1 _171_ (
    .A(_045_),
    .B(_071_),
    .C(_070_),
    .Y(_015_)
  );
  NAND2X1 _172_ (
    .A(prdata[12]),
    .B(_045_),
    .Y(_072_)
  );
  NAND2X1 _173_ (
    .A(rnd_out[12]),
    .B(_046_),
    .Y(_073_)
  );
  OAI21X1 _174_ (
    .A(_045_),
    .B(_073_),
    .C(_072_),
    .Y(_016_)
  );
  NAND2X1 _175_ (
    .A(prdata[13]),
    .B(_045_),
    .Y(_074_)
  );
  NAND2X1 _176_ (
    .A(rnd_out[13]),
    .B(_046_),
    .Y(_075_)
  );
  OAI21X1 _177_ (
    .A(_045_),
    .B(_075_),
    .C(_074_),
    .Y(_017_)
  );
  NAND2X1 _178_ (
    .A(prdata[14]),
    .B(_045_),
    .Y(_076_)
  );
  NAND2X1 _179_ (
    .A(rnd_out[14]),
    .B(_046_),
    .Y(_077_)
  );
  OAI21X1 _180_ (
    .A(_045_),
    .B(_077_),
    .C(_076_),
    .Y(_018_)
  );
  NAND2X1 _181_ (
    .A(prdata[15]),
    .B(_045_),
    .Y(_078_)
  );
  NAND2X1 _182_ (
    .A(rnd_out[15]),
    .B(_046_),
    .Y(_079_)
  );
  OAI21X1 _183_ (
    .A(_045_),
    .B(_079_),
    .C(_078_),
    .Y(_019_)
  );
  NAND2X1 _184_ (
    .A(prdata[16]),
    .B(_045_),
    .Y(_080_)
  );
  NAND2X1 _185_ (
    .A(rnd_out[16]),
    .B(_046_),
    .Y(_081_)
  );
  OAI21X1 _186_ (
    .A(_045_),
    .B(_081_),
    .C(_080_),
    .Y(_020_)
  );
  NAND2X1 _187_ (
    .A(prdata[17]),
    .B(_045_),
    .Y(_082_)
  );
  NAND2X1 _188_ (
    .A(rnd_out[17]),
    .B(_046_),
    .Y(_083_)
  );
  OAI21X1 _189_ (
    .A(_045_),
    .B(_083_),
    .C(_082_),
    .Y(_021_)
  );
  NAND2X1 _190_ (
    .A(prdata[18]),
    .B(_045_),
    .Y(_084_)
  );
  NAND2X1 _191_ (
    .A(rnd_out[18]),
    .B(_046_),
    .Y(_085_)
  );
  OAI21X1 _192_ (
    .A(_045_),
    .B(_085_),
    .C(_084_),
    .Y(_022_)
  );
  NAND2X1 _193_ (
    .A(prdata[19]),
    .B(_045_),
    .Y(_086_)
  );
  NAND2X1 _194_ (
    .A(rnd_out[19]),
    .B(_046_),
    .Y(_087_)
  );
  OAI21X1 _195_ (
    .A(_045_),
    .B(_087_),
    .C(_086_),
    .Y(_023_)
  );
  NAND2X1 _196_ (
    .A(prdata[20]),
    .B(_045_),
    .Y(_088_)
  );
  NAND2X1 _197_ (
    .A(rnd_out[20]),
    .B(_046_),
    .Y(_089_)
  );
  OAI21X1 _198_ (
    .A(_045_),
    .B(_089_),
    .C(_088_),
    .Y(_024_)
  );
  NAND2X1 _199_ (
    .A(prdata[21]),
    .B(_045_),
    .Y(_090_)
  );
  NAND2X1 _200_ (
    .A(rnd_out[21]),
    .B(_046_),
    .Y(_091_)
  );
  OAI21X1 _201_ (
    .A(_045_),
    .B(_091_),
    .C(_090_),
    .Y(_025_)
  );
  NAND2X1 _202_ (
    .A(prdata[22]),
    .B(_045_),
    .Y(_092_)
  );
  NAND2X1 _203_ (
    .A(rnd_out[22]),
    .B(_046_),
    .Y(_093_)
  );
  OAI21X1 _204_ (
    .A(_045_),
    .B(_093_),
    .C(_092_),
    .Y(_026_)
  );
  NAND2X1 _205_ (
    .A(prdata[23]),
    .B(_045_),
    .Y(_094_)
  );
  NAND2X1 _206_ (
    .A(rnd_out[23]),
    .B(_046_),
    .Y(_095_)
  );
  OAI21X1 _207_ (
    .A(_045_),
    .B(_095_),
    .C(_094_),
    .Y(_027_)
  );
  NAND2X1 _208_ (
    .A(prdata[24]),
    .B(_045_),
    .Y(_096_)
  );
  NAND2X1 _209_ (
    .A(rnd_out[24]),
    .B(_046_),
    .Y(_097_)
  );
  OAI21X1 _210_ (
    .A(_045_),
    .B(_097_),
    .C(_096_),
    .Y(_028_)
  );
  NAND2X1 _211_ (
    .A(prdata[25]),
    .B(_045_),
    .Y(_098_)
  );
  NAND2X1 _212_ (
    .A(rnd_out[25]),
    .B(_046_),
    .Y(_099_)
  );
  OAI21X1 _213_ (
    .A(_045_),
    .B(_099_),
    .C(_098_),
    .Y(_029_)
  );
  NAND2X1 _214_ (
    .A(prdata[26]),
    .B(_045_),
    .Y(_100_)
  );
  NAND2X1 _215_ (
    .A(rnd_out[26]),
    .B(_046_),
    .Y(_101_)
  );
  OAI21X1 _216_ (
    .A(_045_),
    .B(_101_),
    .C(_100_),
    .Y(_030_)
  );
  NAND2X1 _217_ (
    .A(prdata[27]),
    .B(_045_),
    .Y(_102_)
  );
  NAND2X1 _218_ (
    .A(rnd_out[27]),
    .B(_046_),
    .Y(_103_)
  );
  OAI21X1 _219_ (
    .A(_045_),
    .B(_103_),
    .C(_102_),
    .Y(_031_)
  );
  NAND2X1 _220_ (
    .A(prdata[28]),
    .B(_045_),
    .Y(_104_)
  );
  NAND2X1 _221_ (
    .A(rnd_out[28]),
    .B(_046_),
    .Y(_105_)
  );
  OAI21X1 _222_ (
    .A(_045_),
    .B(_105_),
    .C(_104_),
    .Y(_032_)
  );
  NAND2X1 _223_ (
    .A(prdata[29]),
    .B(_045_),
    .Y(_106_)
  );
  NAND2X1 _224_ (
    .A(rnd_out[29]),
    .B(_046_),
    .Y(_107_)
  );
  OAI21X1 _225_ (
    .A(_045_),
    .B(_107_),
    .C(_106_),
    .Y(_033_)
  );
  NAND2X1 _226_ (
    .A(prdata[30]),
    .B(_045_),
    .Y(_108_)
  );
  NAND2X1 _227_ (
    .A(rnd_out[30]),
    .B(_046_),
    .Y(_109_)
  );
  OAI21X1 _228_ (
    .A(_045_),
    .B(_109_),
    .C(_108_),
    .Y(_034_)
  );
  NAND2X1 _229_ (
    .A(prdata[31]),
    .B(_045_),
    .Y(_110_)
  );
  NAND2X1 _230_ (
    .A(rnd_out[31]),
    .B(_046_),
    .Y(_111_)
  );
  OAI21X1 _231_ (
    .A(_045_),
    .B(_111_),
    .C(_110_),
    .Y(_035_)
  );
  DFFSR _232_ (
    .CLK(clk),
    .D(_004_),
    .Q(prdata[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _233_ (
    .CLK(clk),
    .D(_005_),
    .Q(prdata[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _234_ (
    .CLK(clk),
    .D(_006_),
    .Q(prdata[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _235_ (
    .CLK(clk),
    .D(_007_),
    .Q(prdata[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _236_ (
    .CLK(clk),
    .D(_008_),
    .Q(prdata[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _237_ (
    .CLK(clk),
    .D(_009_),
    .Q(prdata[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _238_ (
    .CLK(clk),
    .D(_010_),
    .Q(prdata[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _239_ (
    .CLK(clk),
    .D(_011_),
    .Q(prdata[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _240_ (
    .CLK(clk),
    .D(_012_),
    .Q(prdata[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _241_ (
    .CLK(clk),
    .D(_013_),
    .Q(prdata[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _242_ (
    .CLK(clk),
    .D(_014_),
    .Q(prdata[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _243_ (
    .CLK(clk),
    .D(_015_),
    .Q(prdata[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _244_ (
    .CLK(clk),
    .D(_016_),
    .Q(prdata[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _245_ (
    .CLK(clk),
    .D(_017_),
    .Q(prdata[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _246_ (
    .CLK(clk),
    .D(_018_),
    .Q(prdata[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _247_ (
    .CLK(clk),
    .D(_019_),
    .Q(prdata[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _248_ (
    .CLK(clk),
    .D(_020_),
    .Q(prdata[16]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _249_ (
    .CLK(clk),
    .D(_021_),
    .Q(prdata[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _250_ (
    .CLK(clk),
    .D(_022_),
    .Q(prdata[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _251_ (
    .CLK(clk),
    .D(_023_),
    .Q(prdata[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _252_ (
    .CLK(clk),
    .D(_024_),
    .Q(prdata[20]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _253_ (
    .CLK(clk),
    .D(_025_),
    .Q(prdata[21]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _254_ (
    .CLK(clk),
    .D(_026_),
    .Q(prdata[22]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _255_ (
    .CLK(clk),
    .D(_027_),
    .Q(prdata[23]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _256_ (
    .CLK(clk),
    .D(_028_),
    .Q(prdata[24]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _257_ (
    .CLK(clk),
    .D(_029_),
    .Q(prdata[25]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _258_ (
    .CLK(clk),
    .D(_030_),
    .Q(prdata[26]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _259_ (
    .CLK(clk),
    .D(_031_),
    .Q(prdata[27]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _260_ (
    .CLK(clk),
    .D(_032_),
    .Q(prdata[28]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _261_ (
    .CLK(clk),
    .D(_033_),
    .Q(prdata[29]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _262_ (
    .CLK(clk),
    .D(_034_),
    .Q(prdata[30]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _263_ (
    .CLK(clk),
    .D(_035_),
    .Q(prdata[31]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _264_ (
    .CLK(clk),
    .D(lfsr_feedback),
    .Q(rnd_out[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _265_ (
    .CLK(clk),
    .D(rnd_out[0]),
    .Q(rnd_out[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _266_ (
    .CLK(clk),
    .D(rnd_out[1]),
    .Q(rnd_out[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _267_ (
    .CLK(clk),
    .D(rnd_out[2]),
    .Q(rnd_out[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _268_ (
    .CLK(clk),
    .D(rnd_out[3]),
    .Q(rnd_out[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _269_ (
    .CLK(clk),
    .D(rnd_out[4]),
    .Q(rnd_out[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _270_ (
    .CLK(clk),
    .D(rnd_out[5]),
    .Q(rnd_out[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _271_ (
    .CLK(clk),
    .D(rnd_out[6]),
    .Q(rnd_out[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _272_ (
    .CLK(clk),
    .D(rnd_out[7]),
    .Q(rnd_out[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _273_ (
    .CLK(clk),
    .D(rnd_out[8]),
    .Q(rnd_out[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _274_ (
    .CLK(clk),
    .D(rnd_out[9]),
    .Q(rnd_out[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _275_ (
    .CLK(clk),
    .D(rnd_out[10]),
    .Q(rnd_out[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _276_ (
    .CLK(clk),
    .D(rnd_out[11]),
    .Q(rnd_out[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _277_ (
    .CLK(clk),
    .D(rnd_out[12]),
    .Q(rnd_out[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _278_ (
    .CLK(clk),
    .D(rnd_out[13]),
    .Q(rnd_out[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _279_ (
    .CLK(clk),
    .D(rnd_out[14]),
    .Q(rnd_out[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _280_ (
    .CLK(clk),
    .D(rnd_out[15]),
    .Q(rnd_out[16]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _281_ (
    .CLK(clk),
    .D(rnd_out[16]),
    .Q(rnd_out[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _282_ (
    .CLK(clk),
    .D(rnd_out[17]),
    .Q(rnd_out[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _283_ (
    .CLK(clk),
    .D(rnd_out[18]),
    .Q(rnd_out[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _284_ (
    .CLK(clk),
    .D(rnd_out[19]),
    .Q(rnd_out[20]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _285_ (
    .CLK(clk),
    .D(rnd_out[20]),
    .Q(rnd_out[21]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _286_ (
    .CLK(clk),
    .D(rnd_out[21]),
    .Q(rnd_out[22]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _287_ (
    .CLK(clk),
    .D(rnd_out[22]),
    .Q(rnd_out[23]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _288_ (
    .CLK(clk),
    .D(rnd_out[23]),
    .Q(rnd_out[24]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _289_ (
    .CLK(clk),
    .D(rnd_out[24]),
    .Q(rnd_out[25]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _290_ (
    .CLK(clk),
    .D(rnd_out[25]),
    .Q(rnd_out[26]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _291_ (
    .CLK(clk),
    .D(rnd_out[26]),
    .Q(rnd_out[27]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _292_ (
    .CLK(clk),
    .D(rnd_out[27]),
    .Q(rnd_out[28]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _293_ (
    .CLK(clk),
    .D(rnd_out[28]),
    .Q(rnd_out[29]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _294_ (
    .CLK(clk),
    .D(rnd_out[29]),
    .Q(rnd_out[30]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _295_ (
    .CLK(clk),
    .D(rnd_out[30]),
    .Q(rnd_out[31]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _296_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(bit_cnt[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _297_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(bit_cnt[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _298_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(bit_cnt[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _299_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(bit_cnt[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _300_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(bit_cnt[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _301_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(bit_cnt[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _302_ (
    .CLK(clk),
    .D(_003_),
    .Q(valid),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _303_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(lfsr[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _304_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(lfsr[1]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _305_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(lfsr[2]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _306_ (
    .CLK(clk),
    .D(lfsr[2]),
    .Q(lfsr[3]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _307_ (
    .CLK(clk),
    .D(lfsr[3]),
    .Q(lfsr[4]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _308_ (
    .CLK(clk),
    .D(lfsr[4]),
    .Q(lfsr[5]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _309_ (
    .CLK(clk),
    .D(lfsr[5]),
    .Q(lfsr[6]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _310_ (
    .CLK(clk),
    .D(lfsr[6]),
    .Q(lfsr[7]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _311_ (
    .CLK(clk),
    .D(lfsr[7]),
    .Q(lfsr[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _312_ (
    .CLK(clk),
    .D(lfsr[8]),
    .Q(lfsr[9]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _313_ (
    .CLK(clk),
    .D(lfsr[9]),
    .Q(lfsr[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _314_ (
    .CLK(clk),
    .D(lfsr[10]),
    .Q(lfsr[11]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _315_ (
    .CLK(clk),
    .D(lfsr[11]),
    .Q(lfsr[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _316_ (
    .CLK(clk),
    .D(lfsr[12]),
    .Q(lfsr[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _317_ (
    .CLK(clk),
    .D(lfsr[13]),
    .Q(lfsr[14]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _318_ (
    .CLK(clk),
    .D(lfsr[14]),
    .Q(lfsr[15]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _319_ (
    .CLK(clk),
    .D(lfsr[15]),
    .Q(lfsr[16]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _320_ (
    .CLK(clk),
    .D(lfsr[16]),
    .Q(lfsr[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _321_ (
    .CLK(clk),
    .D(lfsr[17]),
    .Q(lfsr[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _322_ (
    .CLK(clk),
    .D(lfsr[18]),
    .Q(lfsr[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _323_ (
    .CLK(clk),
    .D(lfsr[19]),
    .Q(lfsr[20]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _324_ (
    .CLK(clk),
    .D(lfsr[20]),
    .Q(lfsr[21]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _325_ (
    .CLK(clk),
    .D(lfsr[21]),
    .Q(lfsr[22]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _326_ (
    .CLK(clk),
    .D(lfsr[22]),
    .Q(lfsr[23]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _327_ (
    .CLK(clk),
    .D(lfsr[23]),
    .Q(lfsr[24]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _328_ (
    .CLK(clk),
    .D(lfsr[24]),
    .Q(lfsr[25]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _329_ (
    .CLK(clk),
    .D(lfsr[25]),
    .Q(lfsr[26]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _330_ (
    .CLK(clk),
    .D(lfsr[26]),
    .Q(lfsr[27]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _331_ (
    .CLK(clk),
    .D(lfsr[27]),
    .Q(lfsr[28]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _332_ (
    .CLK(clk),
    .D(lfsr[28]),
    .Q(lfsr[29]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _333_ (
    .CLK(clk),
    .D(lfsr[29]),
    .Q(lfsr[30]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _334_ (
    .CLK(clk),
    .D(lfsr[30]),
    .Q(lfsr[31]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _335_ (
    .CLK(clk),
    .D(ring_osc[1]),
    .Q(ring_osc[0]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _336_ (
    .CLK(clk),
    .D(ring_osc[2]),
    .Q(ring_osc[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _337_ (
    .CLK(clk),
    .D(_002_[2]),
    .Q(ring_osc[2]),
    .R(1'h1),
    .S(rst_n)
  );
  assign _001_[31:3] = lfsr[30:2];
  assign _002_[1:0] = ring_osc[2:1];
  assign irq = valid;
  assign pready = 1'h1;
endmodule
